### ISSUE TITLE
Minimal working example test.asy doesn't work on Ubuntu

### ISSUE THREAD

**Issue by NAThompson** [vectorgraphics/asymptote#101]
The minimal example described [here](http://asymptote.sourceforge.net/doc/Drawing-in-batch-mode.html#Drawing-in-batch-mode) does not work on Ubuntu. To wit, after compiling and putting `draw((0,0)--(100,100));` into `test.asy`, I get the following error message:

```bash
~/asymptote$ ./asy -V test.asy
error: could not load module 'plain'
```

**Comment by johncbowman** [comment]
You need to specify the location of the base directory if you haven't yet done a make install:
./asy -dir base -V test.asy
