### ISSUE TITLE
latexmkrc not working when asy files in folder

### ISSUE THREAD

**Issue by bartverm** [vectorgraphics/asymptote#102]
When using the latexmkrc provided with asysmptote with the .asy files in a folder, latexmk is outputting the generated files in the wrong location, and latexmk returns with an error.

A simple solution is to add 
`-o '$_[0]'`
in the system call to asymptote in the latexmkrc file, which makes sure the files are generated in the right folder.

**Comment by johncbowman** [comment]
Yes, that is exactly what we do in latexmkrc_asydir
