### ISSUE TITLE
asymtote crashes on ppc64

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#103]
https://bugs.debian.org/931824
https://buildd.debian.org/status/logs.php?pkg=asymptote&arch=ppc64

Since 2.48 we experience that asy crashes when compiling samples, which are processed during build process:

../asy -dir ../base -config "" -render=0 -f pdf -noprc errorbars.asy
../base/plain_shipout.asy: 102.11: runtime: Segmentation fault

Are you aware of this issue? If you need help (core dumps, back traces) please call back.

**Comment by johncbowman** [comment]
Yes, please send us a traceback. If you know how to use git bisect, it would help to know at exactly what revision this problem first appearred.

**Comment by hpreusse** [comment]
I tried to reproduce in an qemu emulating a ppc64 CPU...and failed. We suspect that the issue was caused by an issue in the build tools. We triggered a re-upload of asymptote into Debian which will cause a rebuild of the package. Hopefully the issue will be gone then. Please put the ticket on hold.

**Comment by hpreusse** [comment]
Today the package built fine on ppc64. We suspect some error in the build tools, which in turn generated a broken binary. The tools were upgraded so the issue was solved.
