### ISSUE TITLE
Tries to install non-existing files

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#107]
Your main Makefile refers to python code, which is gone.
```
PYFILES = $(wildcard GUI/pyUIClass/*.py) GUI/icons_rc.py
```
and later on
```
${INSTALL} -p -m 644 GUI/pyUIClass/*.py $(GUIdir)/pyUIClass
```
Please remove the code if it is obsolete. Thanks!

**Comment by hpreusse** [comment]
...just two examples. There is more obsolete code, which needs to be reviewed in that file.

**Comment by johncbowman** [comment]
The files are not "gone" and the code is not obsolete. These files are prebuilt for you and distributed in our releases. If you are compiling from git and want to use xasy (the graphical front-end for asy), you need to install pyuic5 and pyrcc5.
