### ISSUE TITLE
Spelling errors in source code

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#108]
Our nice spelling tool determined spelling errors in the source code. The attached patch solves them and should apply w/ some line offsets. Consider to apply it. Thanks!

[typos.txt](https://github.com/vectorgraphics/asymptote/files/3480743/typos.txt)

**Comment by johncbowman** [comment]
Thanks; this patch was applied. Note that the typos in the git log (which is used to generate Changelog)
cannot be fixed.
