### ISSUE TITLE
Asymptote SIGFPE when processing sample file

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#109]
https://bugs.launchpad.net/ubuntu/+source/asymptote/+bug/1470662

Long standing issue, still present in 2.51, did not check git checkout. A gdb backtrace is attached, but the issue should be easily reproducible on your side. Thanks!

[asy_backtrace.txt](https://github.com/vectorgraphics/asymptote/files/3481944/asy_backtrace.txt)

**Comment by johncbowman** [comment]
This is not reproducible; it looks like a bug in your software rendering library swrast_dri.so.
Try upgrading your mesa library or install a native driver for your graphics card.
The output should like the example on the gallery.
