### ISSUE TITLE
Please link dynamically GLEW on Linux

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#110]
In the latest release you decided to deliver the GLEW Library and link it statically into the asy binary. This makes absolutely sense on MacOS, but it is quite annoying on Linux, where the distributions contain a separate libGLEW package.

Please re-enable dynamic linking w/ GLEW Lib on Linux. Many thanks!

**Comment by johncbowman** [comment]
The GLEW library is such a small package and is missing on so many systems that by popular demand by Linux and FreeBSD users, it is now linked statically. It is very stable and there have been no new releases in the last 2 years. It is not yet clear that is is required under MacOS; that was not the reason for the change (which was made after careful consideration).

**Comment by hpreusse** [comment]
No, we don't use clang, just plain gcc/g++. What I call annoying is that our (Debian) nice checker tool notices that some code is hard coded into the binary, which is also available as dynamic link library. This is considered an error in the package.
Yes I understand the rationale behind that error and therefore patched the Debian package to link dynamically instead of hard code.

**Comment by supakorn-ras** [comment]
Agreed on this one. As an asymptote developer myself, I prefer a (possibly
non-default option) that links dynamically to glew.c. this way, those who
need static linking can have that, and those others do not have to spend
more time compiling what they already have.

-- Jamie
