### ISSUE TITLE
libm false negative with musl libc

### ISSUE THREAD

**Issue by svenper** [vectorgraphics/asymptote#111]
musl includes libm in libc, which makes this check fail:

```
checking for gamma in -lm... no
configure: error: *** Please install libm on your system ***
```

It should be possible to check for gamma in libc instead.

> On musl, the entire standard library is included in a single library file — libc.a for static linking, and libc.so for dynamic linking. This significantly improves the efficiency of dynamic linking, and avoids all sorts of symbol interposition bugs that arise when you split the libraries up — bugs which have plagued glibc for more than a decade.
>
> [– musl FAQ](https://www.musl-libc.org/faq.html)

**Comment by johncbowman** [comment]
This was already reported and fixed 3 months ago:

commit 71f10dc1f8ebd3e696f87c220c3e9918ff3b80c1
Author: John Bowman <bowman@ualberta.ca>
Date:   Sun May 26 22:56:21 2019 +1000

    Detect gamma instead of sqrt function in libm.

**Comment by svenper** [comment]
That is related, but it isn't the issue here. Checking for anything in lib**m** will fail on musl, because that standard library has no separate lib**m**, as it is absorbed into lib**c**.

**Comment by johncbowman** [comment]
Sorry, I had no idea what musl is and misunderstood. Changing libm to libc as you suggest would break configuration on other systems. Does this patch work for you?

diff --git a/configure.ac b/configure.ac
index ab5de7e5..79c1a12f 100644
--- a/configure.ac
+++ b/configure.ac
@@ -241,7 +241,7 @@ AC_SUBST(INCL)
 AC_SUBST(OPTIONS)
 
 # Checks for libraries.
-AC_CHECK_LIB([m], [gamma],,
+AC_SEARCH_LIBS([gamma],[m c],,
 AC_MSG_ERROR([*** Please install libm on your system ***]))
 AC_CHECK_LIB([z], [deflate],,
 AC_MSG_ERROR([*** Please install libz or zlib-devel on your system ***]))

**Comment by svenper** [comment]
On closer inspection, while GNU libc has deprecated gamma in favor of **l**gamma (and kept an alias), musl libc has only kept the new **l**gamma (with no alias). So it works if we simply add an **l** to your change:

```diff
-AC_CHECK_LIB([m], [gamma],,
+AC_SEARCH_LIBS([lgamma],[m c],,
```

From the [gamma(3)](http://man7.org/linux/man-pages/man3/gamma.3.html) man page:

> These functions are deprecated: instead, use either the [tgamma(3)](http://man7.org/linux/man-pages/man3/tgamma.3.html) or the [lgamma(3)](http://man7.org/linux/man-pages/man3/lgamma.3.html) functions, as appropriate.<br>...<dl><dt>glibc version</dt><dd>Glibc has a <b>gamma</b>() function that is equivalent to <a href="http://man7.org/linux/man-pages/man3/lgamma.3.html">lgamma(3)</a> and computes the natural logarithm of the Gamma function.</dd>
