### ISSUE TITLE
[RFC] [DOC] asymptote.pdf use relative paths

### ISSUE THREAD

**Issue by vp1981** [vectorgraphics/asymptote#112]
Hello,
currently ```asymptote.texi``` (file in ```doc/``` directory) uses only names for ```@image``` command but this leads to full path in PDF file. The full path is unfortunate (due to "reproducible builds"). The relative path, e.g. ```@image{./logo}```, works fine. I have patch for ```doc/asymptote.texi``` to change image paths to relative, though it is very simple.

**Comment by johncbowman** [comment]
Done.
