### ISSUE TITLE
Build fails on Linux Mint 19.2

### ISSUE THREAD

**Issue by ashinpan** [vectorgraphics/asymptote#113]
I  tried to compile the latest trunk on my Linux Mint 19.2 machine, and the compilation fāiled with the following message:

----------------------

glew.o: In function `_glewInit_GL_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:9258: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9259: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9260: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9261: undefined reference to `glXGetProcAddressARB'
glew.o: In function `_glewInit_GL_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:9274: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:9275: more undefined references to `glXGetProcAddressARB' follow
glew.o: In function `glxewGetExtension':
/home/pan/devel-asymptote/GL/glew.c:20530: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:19981: undefined reference to `glXGetProcAddressARB'
glew.o: In function `glxewInit':
/home/pan/devel-asymptote/GL/glew.c:20554: undefined reference to `glXQueryVersion'
/home/pan/devel-asymptote/GL/glew.c:20574: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:19994: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19995: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19996: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19997: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19998: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:19999: more undefined references to `glXGetProcAddressARB' follow
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'asy' failed
make: *** [asy] Error 1

**Comment by ashinpan** [comment]
Both the first and second methods do not work. 

First method error message 
-------------------

glew.o: In function `_glewInit_GL_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:9258: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9259: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9260: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9261: undefined reference to `glXGetProcAddressARB'
glew.o: In function `_glewInit_GL_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:9274: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:9275: more undefined references to `glXGetProcAddressARB' follow
glew.o: In function `glxewGetExtension':
/home/pan/devel-asymptote/GL/glew.c:20530: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:19981: undefined reference to `glXGetProcAddressARB'
glew.o: In function `glxewInit':
/home/pan/devel-asymptote/GL/glew.c:20554: undefined reference to `glXQueryVersion'
/home/pan/devel-asymptote/GL/glew.c:20574: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:19994: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19995: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19996: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19997: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19998: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:19999: more undefined references to `glXGetProcAddressARB' follow
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'asy' failed
make: *** [asy] Error 1
 
Second method error message
--------------

glew.o: In function `_glewInit_GL_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:9258: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9259: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9260: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9261: undefined reference to `glXGetProcAddressARB'
glew.o: In function `_glewInit_GL_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:9274: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:9275: more undefined references to `glXGetProcAddressARB' follow
glew.o: In function `glxewGetExtension':
/home/pan/devel-asymptote/GL/glew.c:20530: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:19981: undefined reference to `glXGetProcAddressARB'
glew.o: In function `glxewInit':
/home/pan/devel-asymptote/GL/glew.c:20554: undefined reference to `glXQueryVersion'
/home/pan/devel-asymptote/GL/glew.c:20574: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:19994: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19995: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19996: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19997: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19998: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:19999: more undefined references to `glXGetProcAddressARB' follow
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'asy' failed
make: *** [asy] Error 1

**Comment by ashinpan** [comment]
The third method doesn't work too. 

The error message
-----------------

glew.o: In function `_glewInit_GL_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:9258: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9259: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9260: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:9261: undefined reference to `glXGetProcAddressARB'
glew.o: In function `_glewInit_GL_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:9274: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:9275: more undefined references to `glXGetProcAddressARB' follow
glew.o: In function `glxewGetExtension':
/home/pan/devel-asymptote/GL/glew.c:20530: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_2':
/home/pan/devel-asymptote/GL/glew.c:19981: undefined reference to `glXGetProcAddressARB'
glew.o: In function `glxewInit':
/home/pan/devel-asymptote/GL/glew.c:20554: undefined reference to `glXQueryVersion'
/home/pan/devel-asymptote/GL/glew.c:20574: undefined reference to `glXGetClientString'
glew.o: In function `_glewInit_GLX_VERSION_1_3':
/home/pan/devel-asymptote/GL/glew.c:19994: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19995: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19996: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19997: undefined reference to `glXGetProcAddressARB'
/home/pan/devel-asymptote/GL/glew.c:19998: undefined reference to `glXGetProcAddressARB'
glew.o:/home/pan/devel-asymptote/GL/glew.c:19999: more undefined references to `glXGetProcAddressARB' follow
collect2: error: ld returned 1 exit status
Makefile:117: recipe for target 'asy' failed
make: *** [asy] Error 1

**Comment by johncbowman** [comment]
Fixed in e547942219cdd1ac6b4dc55785e9148cb1eb9a67.
