### ISSUE TITLE
Rendering on macOS 10.14.6

### ISSUE THREAD

**Issue by nutsenf** [vectorgraphics/asymptote#116]
My issue is described here: https://tex.stackexchange.com/questions/509315/why-am-i-getting-empty-asymptote-output-and-empty-error-files

**Comment by johncbowman** [comment]
What version of Asymptote are you using? 3D OpenGL under MacOS requires at least
Asymptote version 2.53.

**Comment by mojca** [comment]
TeX Live 2019 still ships version 2.49.

**Comment by johncbowman** [comment]
Yes, it sounds like the poster is using an obsolete version of Asymptote, so I will close this issue. 
Note: Version 2.53 is available on MacPorts (and version 2.54, which includes WebGL support, will be officially released later today).
