### ISSUE TITLE
Intersection point of line and hyperbola error.

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#120]
I have a problem with geometry.asy package in code bellow. When I find intersection points of line and hyperbola, I get error: plain_shipout.asy: 108.11: runtime: shipout failed.

But I change point A to point A=(1.5,4.5), this error not show.

Help me to fix this error.

`\begin{asy}
import geometry;
unitsize(1cm);
defaultpen(fontsize(11pt));

point A=(1.5,4); dot(Label("$A$",align=NW),A);
point B=(0,0); dot(Label("$B$",align=SW),B);
point C=(7,0); dot(Label("$C$",align=SE),C);
draw(A--B--C--A);

triangle t=triangle(A,B,C);
draw(circle(A,B,C)); draw(incircle(t));
point O=circle(A,B,C).C; dot(Label("$O$",align=NE),O);
point I=incenter(t); dot(Label("$I$",align=NE),I);

circle inC=incircle(t);
hyperbola hypA=hyperbola(B,inC.C,inC.r/2); draw(hypA);
line bis = bisector(B,C); draw(bis);
point[] t=intersectionpoints(hypA,bis);
dot(Label("$t_0$",align=NE),t[0]);

\end{asy}`

**Comment by johncbowman** [comment]
Thanks for reporting this numerical precision issue (the bisector and one asymptote of the hyperbola are parallel). There may be other similar instances as well; this one is now fixed in 436af6420b9ac380acc457ad433f1f119187f5f1.
