### ISSUE TITLE
the file piicon.png should be added in the installed example folder

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#121]
Hi, John, today I try to draw an external image in the Asymptote, and I searched the example code, I found the file: "C:\Program Files\Asymptote\examples\orthocenter.asy", and it has some code snippet:

~~~
label(graphic("piicon.png","width=2.5cm, bb=0 0 147 144"),Ap,5ENE); 
~~~

But when I run the code, I see that the piicon.png file can't be found.
I just copy the png file from the git repo to the "C:\Program Files\Asymptote\examples", and everything works fine.

BTW: It is really **great** that Asymptote now support loading the external image file directly, thanks for your great work!

**Comment by johncbowman** [comment]
Thanks for pointing this out.

Actually Asymptote always supported loading in any external image format supported by includegraphics and the given TeX engine. What has changed is this now also works for embedding PNG, JPEG, and external vector EPS and PDF images within SVG output, with dvisvgm 2.8.
Nonvector images (like the old piicon.eps) file should be first converted to a PNG file.
