### ISSUE TITLE
dvips error unknown keyword

### ISSUE THREAD

**Issue by matthuszagh** [vectorgraphics/asymptote#124]
I'm getting an error related to dvips in texlive 2019. For example with the following file (file.asy)
```asy
settings.outformat="pdf";
import graph;
size(300,0);

real f(real x) { return exp(x); }
pair F(real x) { return (x, f(x)); }
xaxis("$x$");
yaxis("$y$", 0);

draw(graph(f,-4,2,operator ..),red);
labely(1,E);
label("$e^x$",F(1),SE);
```

I get the error
```
dvips: Unknown keyword ("file_0".eps) in \special will be ignored
dvips: No \special psfile was given; figure will be blank
```
The output pdf then fails to include the plot line and axes.
![file](https://user-images.githubusercontent.com/7377393/69107535-8be07700-0a26-11ea-9f5e-cac10f28e70d.png)

I'm using asy v2.61 and texlive 2019 (dvips 5.999). My texlive installation includes epsf.

**Comment by johncbowman** [comment]
Probably you have a path problem and are actually using some other version of dvips. I just verified that dvips 5.999 shipped in TeXLive 2019 works. I also checked the most up-to-date version of TeXLive 2019:
```
tlmgr update --self
tlmgr update --all
```
You can verify the actual dvips version you are using like this:

`asy -V file -vv`

This does not seem to be an Asymptote issue.

**Comment by matthuszagh** [comment]
I checked `asy -V file -vv` and dvips is indeed the correct version. 

I've tried several different tex engines to see if one works. `pdflatex` works fine, `latex` and `lualatex` do not. I've already reported the `latex` error. `lualatex` gives
```
! LaTeX Error: File `file_0' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55 \includegraphics{file_0}
```

If I add the `-k` option when using lualatex I see that `file_0.pdf` does exist and manually running `lualatex` (version 1.10.0) shows the same error.

**Comment by matthuszagh** [comment]
Ok, you were right, this is not asymptote's fault. This apparently requires a really new version of grffile (from 8 days ago) to work. When that's up-to-date everything works as expected. Thanks for the help!
