### ISSUE TITLE
Error when install asymptote on MACOS

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#127]
I install asymptote on MACOS Mojave. When I use command: make all, I get error:

`g++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -DUSEGC  -D_THREAD_SAFE -pthread -DFFTWPP_SINGLE_THREAD  -I. -Igc-8.0.4/include -I/usr/include/tirpc -std=c++11 -g -O3 -o revision.o -c revision.cc;
error: unable to open output file 'revision.o': 'Operation not permitted'
1 error generated.
make: *** [version] Error 1
`

How to solve it?

**Comment by johncbowman** [comment]
This looks like a permissions issue. Perhaps you did a previous command as root
and now you don't own revision.o. Try starting over in a new directory.
