### ISSUE TITLE
Encoding of the source files

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#128]
Hi, I noticed that `geometry.asy` is not UTF-8 encoded, but Windows-1252 or ISO-8859-1, e.g.

https://github.com/vectorgraphics/asymptote/blob/master/base/geometry.asy#L25
https://github.com/vectorgraphics/asymptote/blob/master/base/geometry.asy#L1505
https://github.com/vectorgraphics/asymptote/blob/master/base/geometry.asy#L6505
https://github.com/vectorgraphics/asymptote/blob/master/base/geometry.asy#L7050

Do we have some agreement on using UTF-8 encoding for source files? Considering this happens only within comments for `geometry.asy`, will everything work correctly if I change the encoding to UTF-8?

Kind regards, Ivan

**Comment by johncbowman** [comment]
Thanks for pointing this out. I removed the non-ASCII characters.

**Comment by ivankokan** [comment]
So, only ASCII?

**Comment by johncbowman** [comment]
I don't really know enough about encodings to answer your question (I'm from the old days, when everything was ASCII and there was no unicode or wide characters :-). But it makes sense to use a uniform encoding for the asy modules.
