### ISSUE TITLE
All 3D graphics fail without render = 0

### ISSUE THREAD

**Issue by nickbclifford** [vectorgraphics/asymptote#130]
I was testing out Asymptote with the samples provided on the Sourceforge gallery and noticed that all of the 2D examples build perfectly fine and give the intended output, whereas the 3D examples produce either a fully black output or mostly black with some weird artifacting. However, when running with either `-render 0` or `settings.render = 0`, the 3D ones suddenly build without a problem.

For example, the output from `elevation.asy`:
![elevation](https://user-images.githubusercontent.com/11001606/70015640-9bda7980-1543-11ea-97a0-8a6a1e857cad.png)

The output from `axis3.asy`:
![axis3](https://user-images.githubusercontent.com/11001606/70015648-a268f100-1543-11ea-9c9d-e020eca383c0.png)

The output from `Gouraudcontour.asy`:
![Gouraudcontour](https://user-images.githubusercontent.com/11001606/70015682-b57bc100-1543-11ea-952d-d75436cc0cc9.png)

The only non-default option I'm using is `-f png`.

**Comment by johncbowman** [comment]
Make sure that you are using version 2.61; we don't support obsolete versions. If you still have problems, then you likely have an issue with your graphics libraries or card. See if glxgears and
glmark2 run for you. If you can't get OpenGL working on your system, you can always generate WebGL output for 3D figures with -fhtml.

There are 5 output formats for viewing 3D figures:
https://asymptote.sourceforge.io/doc/three.html#index-outformat

One doesn't normally use settings.render=0; it is just a rough approximation (see the description in the link).

**Comment by nickbclifford** [comment]
I'm running off the most recent git commit. OpenGL seems to be working just fine, glxgears and glmark2 both run successfully. I'm trying to embed these as raster inside a LaTeX file, and after compiling and testing `latexusage.tex`, the 3D plot inside it shows the same black square. I'm not getting any useful error messages from `asy -vvv` either. Is there something else I should be trying to debug?

**Comment by johncbowman** [comment]
What operating system and architecture do you have? Is it 64 bit? And what GPU card do you have?
Don't use -f png until we get first get OpenGL working. In the meantime, I'll reopen this.

**Comment by nickbclifford** [comment]
I'm using Arch Linux x64 with an Nvidia GTX 1070 and the latest Nvidia drivers.

**Comment by johncbowman** [comment]
Does this example work:
asy -V examples/teapot
I suspect that it does and that your problem is only with -fpng. What version of ghostscript (gs) do you have?

**Comment by nickbclifford** [comment]
Nope, teapot doesn't work either. I'm using Ghostscript 9.50.

**Comment by johncbowman** [comment]
When you say all 3D graphics fails, does
asy -V -f html examples/teapot
also fail?

Also check asy version 2.58 and let me know if that fails too. Thanks!

**Comment by nickbclifford** [comment]
Alright, well, I didn't change anything, but suddenly the latest commit started working again. I think I was accidentally using the package manager version without realizing it, which does still break. I'll just install it from git this time. Thank you for your help!

**Comment by LarsHaalck** [comment]
I have a similar problem and I tried different versions of Asymptote (git commit 4283a1d and versions 2.61, 2.62). In all versions I can use "-f html" to view it in my browser, but "asy -V examples/teapot" or "asy -f png examples/teapot" yield black results.
I run Arch Linux with Nvidia driver 440.40. 

I built from sources with:
```bash
./autogen.sh
./configure --prefix=<some_folder> CXXFLAGS="-I<absolute_folder_to_source_dir>"
make all
```
using gcc 9.2.0. Make runs without problems. The part with CXXFLAGS seems to be needed because it fails to build due to missing "config.h" otherwise. 

configure output: https://gist.github.com/LarsHaalck/4cb3a2a0ad610487d6b7f70a280d72dc
"asy -vvv -V examples/teapot" output: https://gist.github.com/LarsHaalck/7746147715c88b6c0d5e3b0d29bc0c88

**Comment by johncbowman** [comment]
Note that `-render=0` is an experimental attempt at flattening 3D graphics that is not complete and not for normal use. 

I notice that you are using the system version of gc. Maybe try `./configure --enable-gc=8.0.4`
I am using NVIDIA 440.36 on a GeForce GTX 1060 GPU without problems. The
CXXFLAGS issue you are having suggests a problem with your build tools or environment variables.
I am compiling with g++ 9.2.1.

**Comment by LarsHaalck** [comment]
Thank you very much. When using `-enable-gc=8.0.4` after downloading the correct files, everything works fine (even the CXXFLAGS problem) and the examples work again.

**Comment by akhob** [comment]
I have the same problem. I can see the output in my browser using "asy -V -f html examples/teapot" but "asy -V examples/teapot" gives me error "C:/texlive/2020/texmf-dist\asymptote/three.asy: 2885.13: runtime:". 

How can I fix the issue to get png or pdf output?

I am using Windows 10 64 and Nvidia quadro rtx4000 with the latest updates.

Thanks

**Comment by johncbowman** [comment]
Make sure you are using the latest stable version of Asymptote, version 2.67.
If you still can't get it to work, there may be a problem with your graphics driver.
In that case, you can always use the Asymptote Web Application:
http://asymptote.ualberta.ca/
which uses software rendering, without relying on your graphics card, to produce png bitmaps.
