### ISSUE TITLE
filldraw problem with hatch and dotted

### ISSUE THREAD

**Issue by oguibe** [vectorgraphics/asymptote#133]
Following https://tex.stackexchange.com/questions/519810/how-to-draw-this-pattern-in-pstricks-and-its-equivalent-in-asymptote
It seems that under some parameters `hatch` with `dotted` filldraw do not give the right picture.
Perhaps a periodicity problem in the clipping and distributing the pattern

~~~ asy
import patterns;
unitsize(1cm); 
add("fillB",hatch(1.5mm,dotted+blue+1.5bp));
fill(unitcircle,pattern("fillB"));
~~~

**Comment by johncbowman** [comment]
Hi Olivier,
To use a dotted pen in a PostScript fill pattern, one needs to disable automatic scaling and line length
adjustment:

`import patterns;
unitsize(1cm); 
pen dotted=linetype(new real[] {0,4},offset=1,scale=false,adjust=false);
add("fillB",hatch(1.5mm,blue+1.5bp+dotted));
fill(unitcircle,pattern("fillB"));
`
