### ISSUE TITLE
Spurious Spaces from texfile.{h,cc}

### ISSUE THREAD

**Issue by kdamkjer** [vectorgraphics/asymptote#134]
Would it be possible to add more end of line comments to the inline tex output from texfile.{h,cc} to avoid spurious spaces? These are the lines I've found, but there may be others:

texfile.h:

190:`        << p.Lineskip()*settings::ps2tex << "}\\selectfont%" << newl;`

texfile.cc:

107:`    *out << "\\setlength{\\unitlength}{1pt}%" << newl;`
199:`         << p.black() << "}\\color{ASYcolor}%" << newl;`
206:`         << "}\\color{ASYcolor}%" << newl;`
211:`         << "}\\color{ASYcolor}%" << newl;`

I understand that not every line needs to end in a comment. Line 107 appears to be necessary for inline tex from asyinclude, though. Others may not be needed.

Thanks.

**Comment by johncbowman** [comment]
Done.
