### ISSUE TITLE
Errors "File `foo_0' not found." and "Unknown keyword ("foo_0".eps)"

### ISSUE THREAD

**Issue by magula** [vectorgraphics/asymptote#135]
When I'm trying to compile a simple [graph plotting example](https://asymptote.sourceforge.io/gallery/tanh.asy) from the documentation's gallery using `asy -tex lualatex foo.asy`, a log is printed, saying

```
This is LuaTeX, Version 1.10.0 (TeX Live 2019/Arch Linux) 
 restricted system commands enabled.
LaTeX2e <2019-10-01> patch level 1

[...]

(/usr/share/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))

! LaTeX Error: File `foo_0' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.55 \includegraphics{foo_0}
                          %
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./foo_.aux))
[...]
```

When I'm using `asy -tex latex foo.asy` instead, a log is printed, saying
```
dvips: Unknown keyword ("foo_0".eps) in \special will be ignored
dvips: No \special psfile was given; figure will be blank
```

When I'm using `asy -tex [pdflatex|tex] foo.asy`, everything seems to work as expected.

The same happens for at least another [example](https://asymptote.sourceforge.io/gallery/cardioid.asy) from the gallery (but not for all of them), but it's not limited to graphs -- e.g., the following will produce the same errors (but not if you remove any one of the last two lines):
```
pair P = (350.794, 102.062);
pair Q = (-P.y, P.x);

label(rotate(angle(P)/3.1415926*180)*Label("Lion King"), 68pt * unit(P) + 12pt * unit(Q), align = unit(P), darkgray);
clip(scale(7.5cm)*unitsquare);
```

I know that the last example worked fine until recently, so the issue seems to be pretty new.

**Comment by lemniscati** [comment]
Is it related to an issue on grffile (https://github.com/ho-tex/grffile/issues/1) ?

**Comment by johncbowman** [comment]
Yes, this is likely related to the grffile file bug; you may need to update grffile as described in the above bug report. Make sure you are using the latest version (2.61 or later) of asy.
