### ISSUE TITLE
Errors "File `"""logo"-eps-converted-to.pdf'" and "Unknown keyword ("logo".eps)"

### ISSUE THREAD

**Issue by magula** [vectorgraphics/asymptote#136]
When trying to compile
```
label(graphic("logo.eps", "scale=0.55"), (0,0), N+E);
```
using `asy -tex pdflatex bar.asy`, a log is printed, saying

```
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2019-10-01> patch level 1

[...]

(/usr/share/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))

! Package pdftex.def Error: File `"""logo"-eps-converted-to.pdf' not found: usi
ng draft setting.

See the pdftex.def package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.58 ...000,-0.500000){\includegraphics{logo.eps}}
                                                  %
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./bar_.aux) )

[...]
```
The same happens with `lualatex`.
When using `asy -tex latex bar.asy` instead, it gives
```
dvips: Unknown keyword ("logo".eps) in \special will be ignored
dvips: No \special psfile was given; figure will be blank
```

However, `logo.eps` exists. A more complicated version of this snippet worked until recently, but raises this error now.

Possibly related to #135, but here, even the `pdflatex` version doesn't work, and the error is about a file that's explicitly included in the code. Also, the error message is somewhat different.

**Comment by johncbowman** [comment]
You should first remove the .eps extension from the filename logo.eps; that way pdflatex will look for logo.pdf and latex will look for logo.eps. If you are still having problems then there may be a problem with your TeX installation. You should first get this to work:
pdflatex bar.tex

where bar.tex contains:
```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{logo}
\end{document}

```

**Comment by johncbowman** [comment]
Since so many users still have a broken grffile and the functionality of grffile has now been moved into latex, making the import of grffile a null operation, I have removed `\usepackage[space]{grffile}` and related patches; this required bumping asymptote.sty to version 1.35.

So you may wish to try out the latest git version of asy, which should work even on systems with a broken grffile (note that handling spaces in file names will require updating latex to the latest version).
