### ISSUE TITLE
Clipped outer box

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#138]
Hi, I experience "clipped" outer box in the first page of this MWE compiled with version 2.44, which is not the case in the second page.

```
import geometry;
import graph;

unitsize(10mm);

void mymark(picture pic, pair xy, path p, pen f = nullpen) {
  xy = xy - (0.5, 0.5);
  unfill(pic, shift(xy) * p);
  filldraw(shift(xy) * p, f, linewidth(3bp));
  label(pic, "$\bullet$", xy, N + S);
}

picture base = new picture;
for (int i = 1; i <= 5; ++i) {
  for (int j = 1; j <= 5; ++j) {
    label(base, "$\bullet$", (i, j) - (0.5, 0.5), N + S);
  }
}

path diamond = scale(1.6) * ((1, 0) -- (0, 1) -- (-1, 0) -- (0, -1) -- cycle);

mymark(base, (3, 3), diamond, gray(0.8));
clip(scale(5) * unitsquare);
add(base, grid(5, 5, linewidth(0.2bp)));
add(base);
draw(scale(5) * unitsquare, linewidth(3bp));
newpage();

mymark(base, (4, 5), diamond, gray(0.8));
clip(scale(5) * unitsquare);
add(base, grid(5, 5, linewidth(0.2bp)));
add(base);
draw(scale(5) * unitsquare, linewidth(3bp));
newpage();
```

[test.pdf](https://github.com/vectorgraphics/asymptote/files/4070956/test.pdf)

What could be the reason for such behavior? If this is a bug, can you check what happens with the recent version?

**Comment by laolux** [comment]
Change the position when you clip. If you clip right before `newpage();`, then both pages look the same. At least with version 2.62.

**Comment by johncbowman** [comment]
The solution offered by laolux appears to solve this issue.

**Comment by ivankokan** [comment]
Hi @laolux, @johncbowman.

`clip` statements are placed immediately after `mymark` statements because I first wanted to clear everything (diamonds) outside the square of length `5`, and then add a "border" on top of everything.

Clipping right before the `newpage();` makes both page edges equal, but "borders" have only half of the width (`3bp/2`) as the outer part is clipped.

**Comment by ivankokan** [comment]
Hi @laolux, @johncbowman. I hope you got my previous explanation.

The issue remains with freshly installed `Asymptote version 2.66 [(C) 2004 Andy Hammerlindl, John C. Bowman, Tom Prince]`.

**Comment by johncbowman** [comment]
Consider this minimal example:
 
```
size(1cm);
draw(unitsquare,linewidth(1mm));
newpage();
clip(unitsquare);

```
As explained at https://sourceforge.net/p/asymptote/bugs/182/
the clipping has no notion of depth; it transcends layers and even pages. However, you can use a temporary picture to localize the clipping like this:

```
size(1cm);
draw(unitsquare,linewidth(1mm));
newpage();
picture pic;
size(pic);
clip(pic,unitsquare);
add(pic);

```

So your example should be modified to:
```
import geometry;
import graph;

unitsize(10mm);

void mymark(picture pic, pair xy, path p, pen f = nullpen) {
  xy = xy - (0.5, 0.5);
  unfill(pic, shift(xy) * p);
  filldraw(shift(xy) * p, f, linewidth(3bp));
  label(pic, "$\bullet$", xy, N + S);
}

picture base = new picture;
for (int i = 1; i <= 5; ++i) {
  for (int j = 1; j <= 5; ++j) {
    label(base, "$\bullet$", (i, j) - (0.5, 0.5), N + S);
  }
}

path diamond = scale(1.6) * ((1, 0) -- (0, 1) -- (-1, 0) -- (0, -1) -- cycle);

picture pic;
mymark(pic, (3, 3), diamond, gray(0.8));
clip(pic,scale(5) * unitsquare);
add(base,pic);
add(base, grid(5, 5, linewidth(0.2bp)));
add(base);
draw(scale(5) * unitsquare, linewidth(3bp));
newpage();

picture pic2;
mymark(pic2, (4, 5), diamond, gray(0.8));
clip(pic2,scale(5) * unitsquare);
add(base,pic2);
add(base, grid(5, 5, linewidth(0.2bp)));
add(base);
draw(scale(5) * unitsquare, linewidth(3bp));
newpage();
```
