### ISSUE TITLE
Possible Bug with time() Command in version 2.62

### ISSUE THREAD

**Issue by jjpuzzles** [vectorgraphics/asymptote#141]
I recently upgraded to version 2.62 using the Windows binary.  The time() command now returns a string containing the time format description instead of a nicely formatted time string.  For example,

`write(time());`

returns...

`%a %b %d %T %Z %Y`

**Comment by johncbowman** [comment]
Perhaps this is a cygwin issue. I'll look into it during the upcoming a2.63 build.

**Comment by johncbowman** [comment]
I tracked down the problem. It is fixed in commit 9beb5b6c72ce47c8fad8c33f14b78015c9baa40f.
This and other disabled functions will work properly again in the upcoming 2.63 release.
Thanks for reporting this; we'll try to get this release out soon to meet the Feb. 15 TeXLive 2020 deadline.

**Comment by jjpuzzles** [comment]
Thank you for creating and maintaining my favorite language!
