### ISSUE TITLE
tube(path3,unitsquare) does not display properly in animation

### ISSUE THREAD

**Issue by bilibili-233** [vectorgraphics/asymptote#146]
When i want to show a tube with a static cross section in a square,it behaves like it rotates in version 2.64.Later,it works normal in version 2.62.Maybe you should call back some parameters.
Here are an example:

import three;
import tube;
import animation;
unitsize(200);
void drawlink(transform3 tbase,transform3 tend,pen objstyle)
{
 triple pStart=tbase*O;
 triple pEnd  =tend*O;
  path3 p=pStart--pEnd;
  draw(tube(p,scale(0.2)*unitsquare),objstyle);  
}
transform3 t1=shift((0,0,1));
transform3 t2=shift((0,0,-1))*rotate(-20,Y)*shift((0,3,2));
animation B;
for(int i=0;i<10;++i)
{
save();
drawlink(t1,t2,red);
B.add();
restore();
}
B.movie(delay=100);

**Comment by johncbowman** [comment]
You need to use <> to properly format your code. Do you perhaps mean

```
triple pStart=tbase*O;
triple pEnd =tend*O;
```

With this change, I can't see any difference between the gif file created with 2.62 and 2.64.
Can you please also post the expected output file?

**Comment by bilibili-233** [comment]
Sorry,this is my first time to review.I  don't know how to put GIF here.
This example maybe relatively clear.Thank you for your reply.

`settings.render=4;
settings.prc=false;
import solids;
import tube;
import three;
import graph3;
import palette;
import animate;
unitsize(150);

currentprojection=perspective(
camera=(13.3596389245356,8.01038090435314,14.4864483364785),
up=(-0.0207054323419367,-0.00472438375047319,0.0236460907598947),
target=(-1.06042550499095,2.68154529985845,0.795007562120261));
defaultpen(fontsize(30pt));

void DrawLink(transform3 TBase, transform3 TEnd, pen objStyle,string s)
{
  real h=1;
  real r=0.5;
  path3 generator=(0.5*r,0,h)--(r,0,h)--(r,0,0)--(0.5*r,0,0);
  revolution vase=revolution(O,generator,0,360);
  surface objSurface=surface(vase);
    
  render render=render(merge=true);

  // draw two cylinders
  draw(TBase*objSurface,objStyle,render);
  draw(TEnd*shift((0,0,-h))*objSurface,objStyle,render);
	
  // draw the link between two cylinders
  triple pStart=TBase*(0.5*h*Z);
  triple pEnd  =TEnd*(-0.5*h*Z);
  triple pControl1=0.25*(pEnd-pStart)+TBase*(0,0,h);
  triple pControl2=-0.25*(pEnd-pStart)+TEnd*(0,0,-h);
  path3 p=pStart..controls pControl1 and pControl2..pEnd;
  draw(tube(p,scale(0.2)*unitsquare),objStyle,render);   
}
transform3 t1=shift((0,0,1));
transform3 t2=shift((0,0,-1))*rotate(-20,Y)*shift((0,3,2));
transform3 t3=t2*rotate(40,Z)*shift((0,3,1.5))*rotate(-30,Y)*shift(-1.5*Z);
animation B;
for(int i=0;i<=5;++i){
save();
DrawLink(t1,t2,palegreen,"i-1");
DrawLink(t2,t3,lightmagenta,"i");
B.add();
restore();
}
erase();
B.movie(delay=200);

`

**Comment by johncbowman** [comment]
As far as I can tell, the output from 2.64 (and 2.65-3git) looks good to me. Is this what you were expecting?
![testtube2](https://user-images.githubusercontent.com/13231852/77230842-cbe27280-6b5c-11ea-9b38-5dad0cfc0f3e.gif)

**Comment by bilibili-233** [comment]
Thank you for your replay.
Actually,the path is static,so the link should be static.In 2.62 version,this animation meets my expectations.As for the moving part, I did not put it in this code.
![2 62version](https://user-images.githubusercontent.com/62465857/77239703-c21e4500-6c18-11ea-82bd-7ca4dcf79cd5.gif)

**Comment by johncbowman** [comment]
This is fixed in 48777621e61327bf6c8e3492739066495693b91c; you can either upgrade to the latest git version or simply replace your copy of three_tube.asy with
https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/base/three_tube.asy

**Comment by asmwarrior** [comment]
Great work John. In-fact, bilibili-233 is my friend and he would like to generate some animation about the pipe.asy(this is the DH parameter coordinates in robotics).

BTW: I'm still hoping some day, the WebGL output can support animation natively.

**Comment by bilibili-233** [comment]
Thank you for your immediate fix. I admire your persistence in maintaining this software.
