### ISSUE TITLE
function parabola 5 point error?

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#147]
I use function:
parabola parabola(point M1, point M2, point M3, point M4, point M5)

but get error: /usr/local/texlive/2019/texmf-dist/asymptote/geometry.asy: 3029.71: parabola: the given equation is not an equation of a parabola.

How to fix it?

**Comment by ivankokan** [comment]
Hi @quanhinh9. Does your set of five points create degenerate parabola? (Degenerate cases are not so well supported, check https://github.com/vectorgraphics/asymptote/pull/126#issuecomment-573552189).

Can you provide the MWE?

**Comment by quanhinh9** [comment]
Hi ivankokan,

Sorry, this is my mistake, five points are on a hyperbola.

**Comment by ivankokan** [comment]
So, this can be closed?
