### ISSUE TITLE
Make libtirpc dependency explicit and optional

### ISSUE THREAD

**Issue by tifv** [vectorgraphics/asymptote#148]
Asymptote's configure script will detect whether libtirpc is installed and define `HAVE_RPC_RPC_H`, which apparently enables Asymptote to read XDR files (honestly, I've never heard of them, but maybe it is an important feature, I don't know).

Thing is, this also creates a runtime dependency on libtirpc.so. Which can get uninstalled later (or, in my particular case, would not get installed at all, because I was compiling asymptote for a different target system). So, this kinda breaks packaging, especially on systems that compile packages from source. That is, unless you make libtirpc a required dependency.

May I suggest making some sort of --enable-rpc flag that will allow disabling libtirpc dependency? Or mentioning it in documentation as a requirement.

**Comment by johncbowman** [comment]
Since our upcoming v3d binary vector graphics format will require XDR, it would be best to make libtirpc-devel a required package. I have added it to asymptote.spec. XDR is a well-established portable binary format.
