### ISSUE TITLE
Is `operator ^^` usable from LaTeX?

### ISSUE THREAD

**Issue by 8573** [vectorgraphics/asymptote#153]
From LaTeX, I'm trying to use the `operator ^^` as seen in, e.g., <https://asymptote.sourceforge.io/doc/Paths.html> and finding that `^^` is apparently very special to TeX (e.g., <https://tex.stackexchange.com/questions/504244>), such that getting TeX to produce a sequence of two `^` in the necessary `.asy` file seems beyond my capabilities.

I'm surprised to see no previous issue about this (searching for "caret", "circumflex", or "operator"). Has this problem not been encountered before, or is there some easy solution I'm missing (besides not putting one's Asymptote code inside TeX code)?

**Comment by johncbowman** [comment]
You can't use `operator ^^` from LaTeX as that is not a LaTex operator. But you can of course use it in Asymptote embedded within a LaTeX document. I've attached a gzipped example.
[latexusage.tex.gz](https://github.com/vectorgraphics/asymptote/files/4534515/latexusage.tex.gz)

**Comment by 8573** [comment]
By "From LaTeX" I meant in Asymptote embedded within LaTeX — but now of course it works for me; I don't know what I was doing wrong before. Apologies!
