### ISSUE TITLE
Expose abs2 function for pair and triple

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#158]
There are several places in the codebase where using and having internal `abs2` function exposed would be very convenient and (semantically) useful, instead of doing `abs()^2`, expanding the expression in `x^2 + y^2`-fashion, or using `dot(z, z)`.

**Comment by johncbowman** [comment]
Yes, I sometimes miss having those functions too. I only implemented the scalar versions, to avoid
function bloat:
commit 448695a92747861476497f92e23e6d779596ed16
    Implement real abs2(pair) and real abs2(triple).

**Comment by ivankokan** [comment]
@johncbowman It would be convenient to have them mentioned in the manual along with `abs`, wouldn't it?

**Comment by ivankokan** [comment]
@johncbowman It would be convenient to have them mentioned in the manual along with abs, wouldn't it?

**Comment by johncbowman** [comment]
Done.
