### ISSUE TITLE
xasy crashes on windows when opening settings

### ISSUE THREAD

**Issue by mikofski** [vectorgraphics/asymptote#160]
asymptote 2.65
windows-10
python-3

the default editor is 'vi'
the override for windows isn't reached because "windows" is lower cased in `xasyConfig.cson`
the check for overrides in `xasyOptions.py` calls `platform.system()` which returns capitalized "Windows"
but the check doesn't use lower, so it fails

fixes:
* option a: capitalize "Windows" `xasyConfig.cson` override
* option b: add `.lower()` to `xasyOptions.py`

**Comment by johncbowman** [comment]
Thank you for pointing this out; I just pushed option a.
