### ISSUE TITLE
open .asy file in Xasy crashes on windows

### ISSUE THREAD

**Issue by mikofski** [vectorgraphics/asymptote#162]
asymptote-2.65
python-3
windows-10

the path to the `tempDir` folder is repeated twice `asyfy.py`
EG: `./xasyData_hr7_72ot/xasyData_hr7_72ot/_1.svg` instead of just `./xasyData_hr7_72ot/_1.svg`
https://github.com/vectorgraphics/asymptote/blob/56f89ede630ce95f6d0e57c5adf58bc925229ad8/GUI/xasy2asy.py#L779

this causes a file not found error

one fix that works is to comment out the lines that change the working directory to the `tempDir`, because the file in the item already has the full path to the `tempDir`and is already an absolute path.

The `tempDir`works independent of where `xasy.py` is located or from where it is executed.
The `tempDir` is located in whatever folder `xasy.py` is started from and clean up just works.

**Comment by johncbowman** [comment]
Thanks for pointing this out; this is fixed in 503273b5f076f3a46083922b6e0f8a892001a763
and the upcoming 2.66 release.
