### ISSUE TITLE
Better support for generics (templates) and/or macros

### ISSUE THREAD

**Issue by charlesstaats** [vectorgraphics/asymptote#165]
Currently it is possible to parametrize Asymptote code over types using code like the following (hypothetical) example:

~~~asymptote
typedef MyKeyType K;
typedef MyValType V;
include define_map_datastructure;
typedef map_datastructure map_MyKeyType_MyValType;
map_MyKeyType_MyValType map_MyKeyType_MyValType(/*constructor args*/) {
  return map_datastructure(/*constructor args*/);
}
~~~

However, this is pretty cumbersome. It's also hard to write libraries like this because the library code generates compiler errors when run on its own. And it's even more complicated if you want to, say, nest one parameterized type in another. Consequently, in my experience, this feature is almost never used.

It's also possible to use TeX-based macros if you put all your asymptote code inside tex files and use the `asypictureB` package rather than the `asymptote` package (see page 13 of [the asypictureB documentation](http://mirrors.ctan.org/graphics/asypictureb/asypictureB.pdf) for a mergesort macro example) but that also comes with so many caveats that, in practice, no one uses it to write libraries.

So, my request is for Asymptote to (eventually) include a less cumbersome way of writing and instantiating type-parameterized functions.

**Comment by johncbowman** [comment]
I agree. Here is a better method for parametrizing Asymptote code:

https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/base/map.asy.

This module creates a struct parameterized by the types specified in strings key and value,
mapping keys to values with a specified default:

```
import map;
mapTemplate(name="map",key="string",value="int",default="-1");
map M;

M.add("z",2);
M.add("a",3);
M.add("d",4);
write(M.lookup("a"));
write(M.lookup("y"));

```
