### ISSUE TITLE
Wrong dot style for all except the last rendered dot

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#168]
Hi, here is the weird behavior I have experienced for at least two years.

First, the original with no issues (note that I intentionally use separate pictures `pic1` and `pic2` to overcome the issue described below):
```
import geometry;
import graph;

size(0, 30mm);

dotfactor *= 2;

point pB = origin;
point pC = (1, 0);
point pA = intersectionpoint(line(pB, rotate(+60, pB) * pC), line(pC, rotate(-60, pC) * pB));

picture pic1;
draw(pic1, pA -- pB);
draw(pic1, pA -- pC);
dot(pic1, pA, UnFill);
dot(pic1, pB, UnFill);
dot(pic1, pC, UnFill);
label(pic1, "$A$", pA, 2N);
label(pic1, "$B$", pB, 2SW);
label(pic1, "$C$", pC, 2SE);
add(pic1);

newpage();

picture pic2;
draw(pic2, pB -- pC);
dot(pic2, pA, UnFill);
dot(pic2, pB, UnFill);
dot(pic2, pC, UnFill);
label(pic2, "$A$", pA, 2N);
label(pic2, "$B$", pB, 2SW);
label(pic2, "$C$", pC, 2SE);
add(pic2);
```

[v1.pdf](https://github.com/vectorgraphics/asymptote/files/4897947/v1.pdf)

Now, the original in which one can note that the last dot on the second page (either for `pC` or second `pB` when uncommented) gets drawn with wrong style (ignoring the common setup or maybe doubling rendering or whatever).
```
import geometry;
import graph;

size(0, 30mm);

dotfactor *= 2;

point pB = origin;
point pC = (1, 0);
point pA = intersectionpoint(line(pB, rotate(+60, pB) * pC), line(pC, rotate(-60, pC) * pB));

draw(pA -- pB);
draw(pA -- pC);
dot(pA, UnFill);
dot(pB, UnFill);
dot(pC, UnFill);
label("$A$", pA, 2N);
label("$B$", pB, 2SW);
label("$C$", pC, 2SE);

newpage();

draw(pB -- pC);
dot(pA, UnFill);
dot(pB, UnFill);
dot(pC, UnFill);
// dot(pB, UnFill); ***
label("$A$", pA, 2N);
label("$B$", pB, 2SW);
label("$C$", pC, 2SE);
```

[v2.pdf](https://github.com/vectorgraphics/asymptote/files/4897971/v2.pdf)

I doubt this is just a rendering artifact. Regards, Ivan

**EDIT: Actually, that last dot seems to be OK. All others - all on the first page and all except the last one on the second page - are not.**

**Comment by ivankokan** [comment]
Hi again. Here is a somewhat better example of weird and unexpected behavior:
```
import geometry;
import graph;

size(0, 30mm);

point pB = origin;
point pC = (1, 0);
point pA = intersectionpoint(line(pB, rotate(+60, pB) * pC), line(pC, rotate(-60, pC) * pB));


dotfactor *= 3;

draw(pA -- pB);
draw(pA -- pC);
dot(pA, red, UnFill);
dot(pB, UnFill);
dot(pC, UnFill);
label("$A_1$", pA, N);
label("$B_1$", pB, SW);
label("$C_1$", pC, SE);

newpage();

dotfactor *= 3;

draw(pB -- pC);
dot(pA, UnFill);
dot(pB, UnFill);
dot(pC, UnFill);
// dot(pB, UnFill); ***
label("$A_2$", pA, N);
label("$B_2$", pB, SW);
label("$C_2$", pC, SE);
```

![image](https://user-images.githubusercontent.com/1058211/88388677-49d9b300-cdb5-11ea-8e48-db08bd388dd6.png)
![image](https://user-images.githubusercontent.com/1058211/88388686-4fcf9400-cdb5-11ea-8405-06444e61c880.png)

I notice the following:
1. All dots except the one labeled by `$C_2$` have line thinner than they should have.
2. Labels `$A_1$`, `$B_1$` and `$C_1$` should have been placed on top of the dots, just like `$A_2$`, `$B_2$` and `$C_2$` are (note that `label` statements are executed after `dot` statements).
3. I expected dots on the second page to be larger than ones on the first page (note the second `dotfactor *= 3;`).

I consider 1 and 2 to be bugs, not sure about 3?

**Comment by johncbowman** [comment]
3. The global variable dotfactor isn't used until the picture is fit to a frame (at shipout time) so the change applies to the whole picture.

**Comment by johncbowman** [comment]
Issues 1 and 2 are duplicates of https://github.com/vectorgraphics/asymptote/issues/138 and  https://sourceforge.net/p/asymptote/bugs/182.

The solution is to clip to temporary pictures `pic`:
```
import geometry;
import graph;

size(0, 30mm);

point pB = origin;
point pC = (1, 0);
point pA = intersectionpoint(line(pB, rotate(+60, pB) * pC), line(pC, rotate(-60, pC) * pB));


dotfactor *= 3;

picture pic;
draw(pic,pA -- pB);
draw(pic,pA -- pC);
dot(pic,pA, red, UnFill);
dot(pic,pB, UnFill);
dot(pic,pC, UnFill);
add(pic);
label("$A_1$", pA, N);
label("$B_1$", pB, SW);
label("$C_1$", pC, SE);

newpage();

dotfactor *= 3;

picture pic;
draw(pic,pB -- pC);
dot(pic,pA, UnFill);
dot(pic,pB, UnFill);
dot(pic,pC, UnFill);
add(pic);
// dot(pB, UnFill); ***
label("$A_2$", pA, N);
label("$B_2$", pB, SW);
label("$C_2$", pC, SE);

```

**Comment by ivankokan** [comment]
I understand.

Do you consider using separate pictures whenever `newpage()` is used a rule of thumb (even if unfill operation is not used)?

**Comment by johncbowman** [comment]
No, this is only necessary with unfill and clip.
