### ISSUE TITLE
Misplaced graphics/text using inlinetex

### ISSUE THREAD

**Issue by jbaum98** [vectorgraphics/asymptote#169]
I'm having an issue integrating Asymptote and Latex. If I use the `asy` latex environment, everything looks good.

![image](https://user-images.githubusercontent.com/5283991/88689042-05595a80-d0c8-11ea-89c4-43dd2a24fc93.png)

 If I manually run `asy -inlinetex circle.asy` and try to include the graphic using `circle.pre` and `circle.tex`, the graphics and text are misplaced. I made a [gist](https://gist.github.com/jbaum98/1053899bf05711b9bb77a06bf62452bb) to reproduce the issue.

![image](https://user-images.githubusercontent.com/5283991/88689024-ff637980-d0c7-11ea-9194-6df1b7cc28dd.png)

**Comment by johncbowman** [comment]
If for some reason you want to bypass the normal inlinetex workflow, you need to specify consistent command-line options to achieve the same behaviour:

asy circle -inlinetex -tex pdflatex
