### ISSUE TITLE
Log scale doesn’t respect tick label formats

### ISSUE THREAD

**Issue by cagprado** [vectorgraphics/asymptote#17]
Hi!!!

If I want do draw a graph in log scale (regardless if it’s in x or y direction) and draw the axis it will not respect any label format.

This is a simple code to illustrate the problem in case of log scale in the y direction:

```
include graph;

size(10cm,7cm,false);
scale(Linear,Log);

dot((0,-1));
dot((20,log10(20)));

ticks myticks = Ticks(format = "$A = %.4g$");
xaxis("$x$",BottomTop,myticks);
yaxis("$y$",LeftRight,myticks);`
```

Now the "A = NUMBER" appears in the x axis but not in the y axis. The exact opposite is accomplished if the line:
`scale(Linear,Log);`
is changed by:
`scale(Log,Linear);`

Thank you! Cheers,

**Comment by chezbgone** [comment]
I believe the format specifier `%.4g` requires the argument to be a float, but in the logarithmic case, the number that we wish to display is a string of the form `base^{exponent}`.

**Comment by johncbowman** [comment]
That explanation is correct. Perhaps something like this was intended:

```
include graph;

size(10cm,7cm,false);
scale(Linear,Log);

dot((0,-1));
dot((20,log10(20)));

ticks myticks=Ticks(format="$A=%.4g$");
ticks mylogticks=Ticks(new string(real x) {
    string exponent=format("%.4f",log(x)/log(10));
    return find(exponent,".") == -1 ?
      "$A="+(string) 10+"^{"+exponent+"}$" : format(x);
  });

xaxis("$x$",BottomTop,myticks);
yaxis("$y$",LeftRight,mylogticks);
```
