### ISSUE TITLE
no images defined error for wavepacket animation example

### ISSUE THREAD

**Issue by matthuszagh** [vectorgraphics/asymptote#171]
When I attempt to run the `wavepacket.asy` example, I'm getting an error:

```
$ asy wavepacket.asy 
convert: no images defined `gif:wavepacket.gif' @ error/convert.c/ConvertImageCommand/3226.
/nix/store/401fyjrv5z4ycqh3smllad3d8d4gzdhz-asymptote-2.65/share/asymptote/animation.asy: 84.15: merge failed
```

Have you encountered this before? Is this a problem with my installation of asymptote? I'm using version 2.65.

**Comment by johncbowman** [comment]
This is not an Asymptote problem; you simply need to update ImageMagick. I'm running version 7.0.10-25, which works fine; try out the latest version 7.0.10-27 from  https://imagemagick.org/script/download.php

**Comment by matthuszagh** [comment]
Unfortunately I'm still seeing the issue with imagemagick 7.0.10-25:

```
$ convert --version
Version: ImageMagick 7.0.10-25 Q16 x86_64 2020-08-05 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fontconfig freetype heic jng jp2 jpeg lcms lzma openexr png rsvg tiff webp x xml zlib

$ asy wavepacket.asy 
convert: no images defined `gif:wavepacket.gif' @ error/convert.c/ConvertImageCommand/3285.
/nix/store/f561ixzyyv3wsakyghv3s6i3hkhc2hda-asymptote-2.66/share/asymptote/animation.asy: 84.15: merge failed
```

**Comment by matthuszagh** [comment]
Nevermind, this is an error on my end. Thanks for the pointer!

**Comment by johncbowman** [comment]
Here is a minimal example to first get working:

`convert -loop 0 -delay 1 -alpha Off -dispose Background wavepacket+0.eps  gif:wavepacket.gif
`
on this frame:

http://www.math.ualberta.ca/~bowman/wavepacket+0.eps

**Comment by matthuszagh** [comment]
It's all working now. Thanks for all the help @johncbowman!
