### ISSUE TITLE
Embedding to reveal.js

### ISSUE THREAD

**Issue by CsatiZoltan** [vectorgraphics/asymptote#174]
Is it possible to embed executable Asymptote code into [reveal.js](https://github.com/hakimel/reveal.js)? That would allow creating interactive presentations. If not possible, is there a solution to embed the exported HTML code into reveal.js?

**Comment by johncbowman** [comment]
This is an interesting possibility. By "executable Asymptote code", you are asking whether you can embed AsyGL code in reveal.js. That is probably a question best asked of the developers of reveal.js. As long as you can import the asygl library and enter your own code, it should be possible.

**Comment by CsatiZoltan** [comment]
By executable Asymptote code, I mean: if I enter e.g.
```
size(200);
import labelpath3;

path3 g=(1,0,0)..(0,1,1)..(-1,0,0)..(0,-1,1)..cycle;
path3 g2=shift(-Z)*reverse(unitcircle3);

string txt1="\hbox{This is a test of \emph{curved} 3D labels in
\textbf{Asymptote} (implemented with {\tt texpath}).}";

string txt2="This is a test of curved labels in Asymptote\\(implemented
without the {\tt PSTricks pstextpath} macro).";

draw(surface(g),paleblue+opacity(0.5));
draw(labelpath(txt1,subpath(g,0,reltime(g,0.95)),angle=-90),orange);

draw(g2,1bp+red);
draw(labelpath(txt2,subpath(g2,0,3.9),angle=180,optional=rotate(-70,X)*Z));
```
it will display a rotatable figure in the reveal.js html presentation.

What should I specifically ask from the developers of reveal.js? I have no experience in web programming.

**Comment by johncbowman** [comment]
No you can't embed Asymptote code directly within JavaScript; you first need to produce html output and embed that into your slide project. There's a good chance it will work right out of the box, if reveal.js supports JavaScript. So give it a try. Good luck!

**Comment by CsatiZoltan** [comment]
Yes, it does support. I tried but didn't work. Probably I cannot embed the whole html just the relevant part of it. I will ask it on the reveal.js site how to do that, and will come back if I have a result.
