### ISSUE TITLE
ghostscript-9.53.0 breaks asy install

### ISSUE THREAD

**Issue by balducci** [vectorgraphics/asymptote#176]
hello

recently released ghostscript-9.53.0 breaks asy install (make install)
with:

    ----8<----
    ../asy -dir ../base -config "" -render=0 -f pdf -noprc GaussianSurface.asy
    GPL Ghostscript 9.53.0: 
       *** EPS files may not contain multiple pages.
       *** Use of the %d filename format is required to output pages to multiple EPS files.
    GPL Ghostscript 9.53.0: Unrecoverable error, exit code 1
    ---->8----

No problems whatsoever using ghostscript-9.52

thanks a lot for your valuable work

ciao
-gabriele

**Comment by vitlav** [comment]
./asy -dir ../base -config "" -render=0 -h 2>&1 | grep -iv Asymptote > options
../asy -dir ../base -config "" -render=0 -f pdf -noprc axis3.asy
GPL Ghostscript 9.53.1: 
   *** EPS files may not contain multiple pages.
   *** Use of the %d filename format is required to output pages to multiple EPS files.
GPL Ghostscript 9.53.1: Unrecoverable error, exit code 1

**Comment by johncbowman** [comment]
Try 
`asy -epsdriver=ps2write test.asy`

**Comment by johncbowman** [comment]
This solution is now implemented (where needed) in commit 3361214340d58235f4dbb8f24017d0cd5d94da72.

**Comment by balducci** [comment]
> This solution is now implemented (where needed) in commit [3361214]

just to let you know that I have built master vs ghostscript-9.53.3 (current) and everything was fine

thank you very much

ciao
-gabriele

**Comment by PaulTorfs** [comment]
With GPL Ghostscript 9.54.0 (2021-03-30) and Asymptote version 2.70 I used with success the following workaround:

asy -f svg -k foo.asy
