### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by salexud** [vectorgraphics/asymptote#177]
Hello!

I just tried to compile asymptote 2.67 on a Linux box running Slackware-current with gcc 9.3.0 and gc 8.0.4 but it didn't succeed:

g++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -DUSEGC  -pthread -DFFTWPP_SINGLE_THREAD  -I. -I/usr/include/gc -I/usr/include/gc -I/usr/include/tirpc -std=c++11 -O2 -fPIC -fno-var-tracking -o drawpath.o -c drawpath.cc
In file included from drawelement.h:21,
                 from drawpath.h:11,
                 from drawpath.cc:12:
glrender.h: In constructor ‘camp::vertexData::vertexData(const camp::triple&, const camp::triple&)’:
glrender.h:219:14: error: ‘MaterialIndex’ was not declared in this scope
  219 |     material=MaterialIndex;
      |              ^~~~~~~~~~~~~
glrender.h: In constructor ‘camp::VertexData::VertexData(const camp::triple&, const camp::triple&)’:
glrender.h:238:14: error: ‘MaterialIndex’ was not declared in this scope
  238 |     material=MaterialIndex;
      |              ^~~~~~~~~~~~~
glrender.h: In constructor ‘camp::VertexData::VertexData(const camp::triple&, const camp::triple&, GLfloat*)’:
glrender.h:247:14: error: ‘MaterialIndex’ was not declared in this scope
  247 |     material=MaterialIndex;
      |              ^~~~~~~~~~~~~
glrender.h: In constructor ‘camp::vertexData0::vertexData0(const camp::triple&, double)’:
glrender.h:265:14: error: ‘MaterialIndex’ was not declared in this scope
  265 |     material=MaterialIndex;
      |              ^~~~~~~~~~~~~
glrender.h: At global scope:
glrender.h:284:15: error: ‘Material’ was not declared in this scope; did you mean ‘glMateriali’?
  284 |   std::vector<Material> materials;
      |               ^~~~~~~~
      |               glMateriali
glrender.h:284:23: error: template argument 1 is invalid
  284 |   std::vector<Material> materials;
      |                       ^
glrender.h:284:23: error: template argument 2 is invalid
glrender.h: In member function ‘void camp::vertexBuffer::clear()’:
glrender.h:305:15: error: request for member ‘clear’ in ‘((camp::vertexBuffer*)this)->camp::vertexBuffer::materials’, which is of non-class type ‘int’
  305 |     materials.clear();
      |               ^~~~~
make: *** [Makefile:365: drawpath.o] Error 1

Help is highly appreciated.

Best regards,
Serban

**Comment by johncbowman** [comment]
Can you check your configure log and let us know which include you are missing (maybe GLUT or GLM)?
Then we can disable OpenGL in this corner case. Of course, for normal usage you would want to fix
the missing dependency to get a fully functional asy.

**Comment by salexud** [comment]
Hello,
and thank you very much for the quick feedback. From the configure log it's clear that I'm missing glm:

configure: *** Could not find glm header files: will compile without WebGL or OpenGL support ***

However GLUT should be OK:

checking for glutMainLoop in -lglut... yes

But the message regarding glm is such, that I expected the compile to go on and the resulting executable to just have reduced functionality.
In the meantime I tried to install glm 0.9.9.8 but got stuck. "make install" doesn't work and there actually is a message in the changelog, that install scripts got removed since v. 0.9.9.6. However I could not find any instructions of what to do and didn't get a feedback to my question until now. Thus, I'll let you know if compilation works after I get glm installed.

Best regards,
Serban

PS. In "Compiling from UNIX source" glm doesn't appear to be mentioned as a dependency.

**Comment by johncbowman** [comment]
Just install glm-devel from your distribution and you should be fine.
Without this package, you won't be able to produce any 3D graphics at all,
not even
WebGL. If you are using ubuntu you can satisfy all dependencies with:

sudo cp /etc/apt/sources.list /etc/apt/sources.list~
sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
sudo apt-get update
sudo apt-get build-dep asymptote

sudo apt-get install libcurl4-openssl-dev
