### ISSUE TITLE
Proposal: Introduce `bool isIsometry()` method for `transform` class

### ISSUE THREAD

**Issue by ivankokan** [vectorgraphics/asymptote#178]
Proposal: we could benefit from introducing `bool isIsometry()` method for `transform` class.

_Originally posted by @ivankokan in https://github.com/vectorgraphics/asymptote/issues/164#issuecomment-668321780_

**Comment by johncbowman** [comment]
bool  isometry(transform) is now implemented in a36959ecbdc74fe83720dd28a009d65e16a0302a.
