### ISSUE TITLE
Installation of asy.vim for newer versions of vim

### ISSUE THREAD

**Issue by Ian2020** [vectorgraphics/asymptote#180]
Hi,

How can asymptote be updated to install asy.vim for newer versions of vim? I am on asymptote 2.62 and the RPM adds links to asy.vim at these locations:

```
/usr/share/vim/vim63/syntax/asy.vim
/usr/share/vim/vim64/syntax/asy.vim
/usr/share/vim/vim70/syntax/asy.vim
/usr/share/vim/vim71/syntax/asy.vim
/usr/share/vim/vim72/syntax/asy.vim
/usr/share/vim/vim73/syntax/asy.vim
```

However vim has moved on to vim82 on my system. I can't see how this is done in the .spec, makefile or elsewhere in the repo. Could you point me in the right direction to update this?

Thanks

**Comment by johncbowman** [comment]
This is something done by the Fedora package managers; you should contact them instead.
We welcome any updates to the spec file that they provided back in 2006, which has had minimal updates since then.

**Comment by Ian2020** [comment]
Thanks, I've raised it with them: https://bugzilla.redhat.com/show_bug.cgi?id=1884684

**Comment by avidseeker** [comment]
Not sure if this discussion has been had before, but wouldn't moving maintenance of the syntax file to upstream Vim be better? It would solve these kinds of issues and users would have syntax working out-of-the-box without having to manually copy config files.

**Comment by johncbowman** [comment]
It would make sense for a Vim user to contact the Vim developers and give them a copy of the latest asy.vim file.
