### ISSUE TITLE
Need output figure in pdf format with custom name

### ISSUE THREAD

**Issue by HumHongeKamyaab** [vectorgraphics/asymptote#183]
I want to have "customname" for the figures produced in pdf format by asymptote using following latex file. The latexmkrc used to run this minimal example is provided below. 

I have found following option to change the name of the output figure in pdf format but it is commented in `foo.tex` file to make sure it is running. Uncommenting this line in the following tex file will give error while compiling it using `latexmk`.
```
defaultfilename="customname1"
```

--------------------------------------------------------------------------------------------------

`foo.tex` file
```
\documentclass[12pt]{article}
\usepackage[inline]{asymptote}

\begin{document}
\def\asydir{figs}

\begin{center}
\begin{asy}[width=\the\linewidth,inline=true]
//defaultfilename="customname1";
pair z1=(2,0);
pair z2=(5,0);
draw(z1--z2);
\end{asy}
\end{center}

\begin{center}
\begin{asy}[width=\the\linewidth,inline=true]
//defaultfilename="customname2";
pair z1=(2,0);
pair z2=(5,0);
draw(z1--z2);
\end{asy}
\end{center}

\end{document}
```

`latexmkrc` file
```
sub asy {return system("asy -o figs/ '$_[0]'");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
```
`~/.latexmkrc` file
```
$pdf_mode = 1;
$latex = 'latex  %O  --shell-escape %S';
$pdflatex = 'pdflatex  %O  --shell-escape %S';
```

Want following files, 
```
figs/customname1_0.pdf
figs/customname2_0.pdf
```
instead of default
```
figs/foo-1_0.pdf
figs/foo-2_0.pdf
```

Can someone suggest changes in `foo.tex` to achieve `customname` pdf files. Or is there way to change `latexmkrc` file (without hardcoding it) so that it can be achieved.

**Comment by johncbowman** [comment]
The whole point of including inline asy code like this in a TeX document is so you don't have to invent an arbitrary name for each
figure in the document. If you already have custom names in mind, the solution is to put each named figure in a separate file like customname1.asy and use \asyinclude{customname1} to include it.
