### ISSUE TITLE
Transpose non rectangular array

### ISSUE THREAD

**Issue by axiopost** [vectorgraphics/asymptote#189]
When you apply the transpose function to a dynamic array, the sizes of the result are not the expected ones :
```
write("Asymptote version ",VERSION);
int[][] a=new int[3][];
a[0][1]=1; a[1][0]=2; a[2][2]=3;
write(a);
write("");
write(a[0].length, a[1].length, a[2].length);

write("After transposition");

a=transpose(a);
write(a);
write("");
write(a[0].length, a[1].length, a[2].length);
```

Result :
```
Asymptote version 2.67
	1
2
		3

2	1	3
After transposition
	2	
1		
		3

3	3	3
```
As you can see, all lines of the result have length 3. So we get arrays with the last element undefined `write(a[0][a[0].length-1]);` returns
`15.6: read uninitialized value from array at index 2`

I am not sure this is really an issue. But it seems strange that transposing twice an array does not give the original one.

**Comment by johncbowman** [comment]
Fix in b1ab048d6cf6b703a992a296c870d3b1c5a63b3e.
