### ISSUE TITLE
CC and CXX env variables are not respected when building GC

### ISSUE THREAD

**Issue by mojca** [vectorgraphics/asymptote#19]
If I set
~~~~~bash
export CC=/path/to/my/compiler/gcc
export CXX=/path/to/my/compiler/g++
~~~~~
those settings get ignored during configuration/compilation of GC and in on one particular setup that I use this leads to an error (and completely wrong behaviour).

The following patch helped:
~~~~~diff
--- a/Makefile.in
+++ b/Makefile.in
@@ -160,7 +160,7 @@
          mv gc-7.2 gc-7.2d; \
        fi
        cd $(GC) && \
-       ./configure $(GCOPTIONS); \
+       ./configure CC="$(CC)" CXX="$(CXX)" $(GCOPTIONS); \
        $(MAKE) check
 
 $(GCPPLIB): $(GCLIB)
~~~~~
but most likely `CFLAGS`, `CXXFLAGS`, `LDFLAGS`, `CPPFLAGS` etc. would also be needed.

I suspect this is also the reason why universal build [fails on MacPorts](https://trac.macports.org/ticket/48520).

**Comment by johncbowman** [comment]
Thanks; I added this patch (without CFLAGS and CXXFLAGS, to avoid compilation errors).

**Comment by mojca** [comment]
Commit: 0d7435b299f721fbe4d788edc3f5334f8bddabb9

Thank you very much. The only remaining "problem" is that a standard way to compile for a different architecture on Mac is usually something like
```bash
export CFLAGS="-arch i386"
export CXXFLAGS="-arch i386"
export LDFLAGS="-arch i386"
```
or (used by MacPorts)
```bash
export CPPFLAGS="-arch i386"
```
and those flags wouldn't be promoted to GC builds. But I have to give this a bit more thought. A valid way to achieve the goal is still
```bash
export CC="clang -arch i386"
export CXX="clang++ -arch i386"
```

For now that should do it. Thank you very much for accepting the patch.
