### ISSUE TITLE
Memory leaks and build failures on macOS with Macports

### ISSUE THREAD

**Issue by snowflake** [vectorgraphics/asymptote#190]
Over on the Macports bug reporter we are trying to find some fixes for severe memory leaks (many GB) and also some build failures on recent checkouts using the latest macOS. and also some old versions of macOS

If interested, please take a look here: https://trac.macports.org/ticket/61536

**Comment by johncbowman** [comment]
I've fixed the minor compilation issue reported with the latest git version on Catalina.

**Comment by johncbowman** [comment]
I just tried the latest git version with 'make all' under Catalina with clang-12.0.0 and it works fine without any memory leaks. I'm using gc-8.0.4 and libatomic-ops-7.6.10. I will try out Big Sur too before the 2.68 release.

**Comment by snowflake** [comment]
Thank you very much for the speedy fix. It's working fine building with Macports.

**Comment by johncbowman** [comment]
Good to hear. Everything seems fine under Big Sur too.
