### ISSUE TITLE
Redirect from tickets on Sourceforge?

### ISSUE THREAD

**Issue by natkuhn** [vectorgraphics/asymptote#192]
It would be great if you could leave an open ticket on Sourceforge telling people to come here to Github for bugs. The link on the [main asymptote page](https://sourceforge.net/p/asymptote/discussion/409349/thread/d934b0ace3/) is correct, but if you go to the forum first, you can spend a lot of time swearing at the [grayed-out "Create Ticket" button](https://sourceforge.net/p/asymptote/bugs/)! Thanks!

**Comment by johncbowman** [comment]
Done. It's always best to first look at the documentation, which directs the user here.
