### ISSUE TITLE
Add variable opacity to palette?

### ISSUE THREAD

**Issue by cagprado** [vectorgraphics/asymptote#198]
Hi! I want to make a color gradient but I'd like to vary the opacity throughout the palette! I suppose this is not possible yet or maybe I haven't found the right way of doing it. I don't really know if that would be possible from the ghostscript side of things either. In any case I'd appreciate any feedback or ideas on that!

Basically, I'd like to do something like this, but changing the inner loop contents for the commented line.

```asymptote
import palette;
size(200);

int n = 300;
pen[][] v = new pen[n][n];
for (int i = 0; i < n; ++i)
  for (int j = 0; j < n; ++j)
    v[i][j] = gray(1-i*j/n**2);
    //v[i][j] = opacity(1-i*j/n**2);
image(v, (0, 0), (1, 1));
```

**Comment by johncbowman** [comment]
The forum is a better place for help (this issues list is for bugs and feature requests). Anyway, here is how to add opacity to your pen:

`v[i][j] = gray(1-i*j/n**2)+opacity(1-i*j/n**2);`

**Comment by cagprado** [comment]
This is a feature request! I'm sorry if I didn't make it clear before. The point is, as of now (I'm using the current master), Asymptote won't use a varying opacity throughout the palette, it will instead choose the first opacity it sees and set it for the whole image object. So in the above example, if I use:

    v[i][j] = gray(1-i*j/n**2)+opacity(1-i*j/n**2);

the whole picture will be opaque and the gray gradient will be fully visible. If I change it to, for example:

    v[i][j] = gray(1-i*j/n**2)+opacity(i*j/n**2);

I get a fully white picture (i.e. the gray gradient is completely invisible).

Instead, I'd like the opacity to be different for every element of the `v` array and the opacity in the final picture reflect that.

**Comment by johncbowman** [comment]
I see. Unfortunately, according to page 334 of the PDF Reference (Sixth Edition, Version 1.7), it sound likes like you may be out of luck (no mention of an alpha channel):

_Each sample in the array consists of as many color components as are needed for the color space in which they are specified—for example, one component for DeviceGray, three for DeviceRGB, four for DeviceCMYK, or whatever number is required by a particular DeviceN space._

**Comment by cagprado** [comment]
That does sound very unfortunate! Thanks for looking into it!
