### ISSUE TITLE
Error when compiling 3D example

### ISSUE THREAD

**Issue by axiopost** [vectorgraphics/asymptote#199]
Hi,

> Release Notes for Version 2.68 
> [...] Suport for Ghostscript 9.53 was implemented. [...]

I have installed Ghostscript v9.53 and Asymptote v2.68 (from asymptote-2.68-setup.exe found in the Home/2.68/ folder).
When I try to compile the axis3.asy example, the result is
`asy examples/axis3.asy`
**freeglut (asy): fgInitGL2: fghGenBuffers is NULL
      0 [main] asy 982 cygwin_exception::open_stackdumpfile: Dumping stack trace to asy.exe.stackdump**

When installed with the asymptote-2.68-setup-i386_32.exe version, the error is
**freeglut (asy): fgInitGL2: fghGenBuffers is NULL
   4667 [main] asy 6752 cygwin_exception::open_stackdumpfile: Dumping stack trace to asy.exe.stackdump**

Any idea ?

**Comment by johncbowman** [comment]
That means that your hardware or graphics driver doesn't support OpenGL 3 (for example, this happens when running under VirtualBox or VMWare). Use a different machine or generate WebGL output with 
`settings.outformat="html";`
