### ISSUE TITLE
Provide a configure-time option to disable sigsegv

### ISSUE THREAD

**Issue by mojca** [vectorgraphics/asymptote#20]
It would be helpful to have an option to disable sigsegv for cases when asy is compiled on a computer with sigsegv installed for another computer without it.

Perhaps an option like `--without-sigsegv` or `--disable-sigsegv` would do.

**Comment by johncbowman** [comment]
--disable-sigsegv is implemented in b9ca1650f3086a265eb9d39649261680fe032ba5
