### ISSUE TITLE
graph.asy is broken

### ISSUE THREAD

**Issue by graphine** [vectorgraphics/asymptote#200]
D:\OneDrive\Asymptote\animate>asy -f pdf wheel.asy
  pair width=0.5*size(d);
  ^
C:\Program Files\MiKTeX 2.9/asymptote/graph.asy: 427.3: runtime:

**Comment by johncbowman** [comment]
That doesn't mean graph.asy is broken. 

This looks more like a segmentation fault, perhaps triggered by a missing support utility.

Be sure to use the latest version of Asymptote (2.68). If you are, please post the output of
asy -f pdf wheel -vvv -nothreads
and the details of the platform you are using (presumably MSWindows but what version?)

**Comment by graphine** [comment]
It appears that MikTex Console installs 2.67 whenever I run asy in terminal while the latest version is 2.68 now.

**Comment by graphine** [comment]
removed MiKTex and installed Texlive that uses 2.65, no problems so far.
