### ISSUE TITLE
Scaling problems in 3D using orthographic projection and keepAspect==false

### ISSUE THREAD

**Issue by cagprado** [vectorgraphics/asymptote#201]
Hi, I noticed a problem that can be illustrated in the example below:

```asymptote
import graph3;
draw(unitsphere, red);

size(8cm, 5cm, keepAspect=true);
shipout("test1.pdf");                     // OK

size(8cm, 5cm, keepAspect=false);
shipout("test2.pdf");                     // OK

currentprojection=orthographic(3, 3, 3);

size(8cm, 5cm, keepAspect=true);
shipout("test3.pdf");                     // OK

size(8cm, 5cm, keepAspect=false);
shipout("test4.pdf");                     // Weird!!!
```

When using perspective projection, the picture scaling seems to behave flawlessly by keeping the picture inside the size bounds when `keepAspect==true` and "stretching" it when `keepAspect==false`. In addition, using orthographic projection with `keepAspect==true` still leads to a picture correctly restricted in size by the given values.

However, when using orthographic projection and setting `keepAspect` to `false`, the final picture size is completely off. In this example, I get a picture with width 7.3cm and height 5.5cm, both skinnier and taller than intended.

    version=2.68-18 (archlinux build, no disabled options)

**Comment by johncbowman** [comment]
Fixed in ab6c72c152ec8ad0e052706ac16023bf044ab550.
