### ISSUE TITLE
Wrong pen after adding many images with xelatex

### ISSUE THREAD

**Issue by Harniver** [vectorgraphics/asymptote#206]
The following simple asymptote file:
```
unitsize(1cm);
settings.tex = "xelatex";
fill((-1,-1) -- (10,-1) -- (10,10) -- (-1,10) -- cycle, mediumgray);
for (int y=0; y<10; ++y) {
    for (int x=0; x<10; ++x) {
        label(scale(0.2)*graphic("bar.png"), (x,y-.25));
        label(scale(0.8)*"foo", (x,y+.25), white);
    }
}
```
compiled with `-f pdf` should produce a grid of white foos. Instead, from the 64th replica the foos become black.
I tried with few different images PNG or JPG with no difference in the result.
This issue does not appear with pdflatex; so I assume it comes from the interaction between asymptote and xelatex.
My system is a MacBook Pro (16-inch 2019) with macOS Big Sur 11.1.

**Comment by johncbowman** [comment]
Here's a minimal example that illustrates the issue:
```
unitsize(1cm);
settings.tex = "xelatex";

for (int y=0; y<8; ++y) {
    for (int x=0; x<8; ++x) {
      label(scale(0.2)*"A", (x,y-.25));
     label(scale(0.8)*"B", (x,y+.25), red);
     }
}

```

**Comment by johncbowman** [comment]
This is a xelatex bug. Could you kindly send the attached minimal tex file to the XeLaTeX developers? Thanks!

[test.tex.gz](https://github.com/vectorgraphics/asymptote/files/5937932/test.tex.gz)

**Comment by Harniver** [comment]
I finally sent the bug to xelatex developers, and they suggested that this is not a xelatex bug; instead, it is a mixture of a texlive limitation, and a poor code writing choice, which actually asymptote could address. I copy-paste their reply:

> I think this is a problem at the macro level rather than in the xetex engine itself. As far as I can see, each \color{...} command here expands into a \special{color push ...} in the output, so that the output driver pushes a new color onto its stack; but the colors are never popped from the stack, and eventually it reaches its maximum size (looks like 128 entries).

> If you put each usage of \color{....} <text> inside a group, by surrounding it with { ... } braces, the problem goes away because the color stack gets popped at the end of the group.

> According to the color package documentation the expected behavior of \color is that it "will stay in effect until the end of the current TeX group". It seems the implementation of this relies on a color stack in the output driver, and that stack has a limited depth. These are implementation details that could perhaps be improved (as far as I can see, at the macro level, there's no point in pushing all the colors onto the stack; only the color in effect at the beginning of the group needs to be saved so that it can be restored at the end; and the output driver's color stack could be made dynamic rather than fixed-depth).

> These issues would be best reported somewhere like the TeX Live mailing list, I think, as they're not bugs in the xetex engine itself. As for the original problem, probably the easiest workaround is to ensure that each colored fragment of output is appropriately grouped, to avoid continually pushing new stack entries.

I think that their suggestion of adding `{ ... }` groups is actually sensible and would make sense to implement it in asymptote.

**Comment by Harniver** [comment]
This problem is still persisting.

**Comment by Harniver** [comment]
@johncbowman I am a programmer, although not familiar (yet) with the internals of the asymptote project. If you give me just an outline/guide of what to do (with a quick search it seems to me that the offending code is in `texfile.{h,cc}`), I should be able to help and produce a pull request for this. Let me know!

**Comment by johncbowman** [comment]
It's not quite so simple as we don't want to break more complicated examples:

```
unitsize(1cm);
settings.tex = "xelatex";

for (int y=0; y<8; ++y) {
    for (int x=0; x<8; ++x) {
      label(scale(0.2)*"A", (x,y-.25));
      tex("\def\test{hello}");
     label(scale(0.8)*"B", (x,y+.25), red);
     }
}
tex("\test");

```

**Comment by johncbowman** [comment]
Given the awkward way that the color.sty macros are implemented, pushing onto a fixed-depth stack, the sensible solution is to abandon this package completely and handle color directly, using the same specials already used by non-Latex TeX engines.
