### ISSUE TITLE
Error in tutorial, up is (0,1) not (1,0)

### ISSUE THREAD

**Issue by programaths** [vectorgraphics/asymptote#208]
On page 10 of the tutorial (https://asymptote.sourceforge.io/asymptote_tutorial.pdf) , it reads:

Note that up is really just short for **(1,0)**

While it should be:

Note that up is really just short for **(0,1)**

**Comment by johncbowman** [comment]
Thanks; I forwarded your report directly to the author.

**Comment by johncbowman** [comment]
The online version of asymptote_tutorial.pdf has now been updated.
