### ISSUE TITLE
What's the correct way to start xasy under Windows

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#209]
I have `WinPython-64bit-3.5.3.1Qt5`, and I have also installed the cson and other dependencies as the manual pdf said.

When I run the command, I got such result.

~~~~
C:\Program Files\Asymptote\GUI>python xasy.py
Traceback (most recent call last):
  File "xasy.py", line 19, in <module>
    sys.exit(main(sys.argv) or 0)
  File "xasy.py", line 13, in main
    mainWin1 = MainWindow1()
  File "C:\Program Files\Asymptote\GUI\Window1.py", line 131, in __init__
    self.asyEngine.start()
  File "C:\Program Files\Asymptote\GUI\xasy2asy.py", line 79, in start
    universal_newlines=True)
  File "E:\download\sci\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "E:\download\sci\WinPython-64bit-3.5.3.1Qt5\python-3.5.3.amd64\lib\subprocess.py", line 955, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

C:\Program Files\Asymptote\GUI>
~~~~

I have checked that the dependencies are added:

~~~~
C:\Program Files\Asymptote\GUI>pip3 install cson numpy pyqt5 PyQt5.sip
Looking in indexes: https://pypi.douban.com/simple
Requirement already satisfied: cson in e:\download\sci\winpython-64bit-3.5.3.1qt5\python-3.5.3.amd64\lib\site-packages (0.8)
Requirement already satisfied: numpy in e:\download\sci\winpython-64bit-3.5.3.1qt5\python-3.5.3.amd64\lib\site-packages (1.11.3+mkl)
Requirement already satisfied: pyqt5 in e:\download\sci\winpython-64bit-3.5.3.1qt5\python-3.5.3.amd64\lib\site-packages (5.9.2)
Collecting PyQt5.sip
  Using cached https://pypi.doubanio.com/packages/01/71/a5c61d42751504fc51e54c18f581272f23f14c33fecab0ffd3ad848a5489/PyQt5_sip-12.8.1-cp35-cp35m-win_amd64.whl
Requirement already satisfied: speg in e:\download\sci\winpython-64bit-3.5.3.1qt5\python-3.5.3.amd64\lib\site-packages (from cson) (0.3)
Requirement already satisfied: sip<4.20,>=4.19.4 in e:\download\sci\winpython-64bit-3.5.3.1qt5\python-3.5.3.amd64\lib\site-packages (from pyqt5) (4.19.6)
Installing collected packages: PyQt5.sip
Successfully installed PyQt5.sip
~~~~

And the file https://sourceforge.net/projects/tumagcc/files/rsvg-convert-2.40.20.7z is already extracted, and the binary file is put in the PATH.

Any ideas how to fix this issue?
Thanks.

BTW: I have send this same post in the forum: [Help](https://sourceforge.net/p/asymptote/discussion/409349/), but I'm not sure why my post are waiting for administrator's verification, so I post it here again. Sorry about the noise.

**Comment by asmwarrior** [comment]
It looks like the python script can't find the asy.exe in the file `xasy2asy.py`.

~~~~
    def start(self):
        try:
            if sys.platform[:3] == 'win':
                self.asyProcess = subprocess.Popen([self.asyPath] + self.args,
                                                stdin=subprocess.PIPE, stderr=subprocess.PIPE,
                                                universal_newlines=True)
                self.ostream = self.asyProcess.stdin
                self.istream = self.asyProcess.stderr
            else:
                self.asyProcess = subprocess.Popen([self.asyPath] + self.args,close_fds=False)
        finally:
            atexit.register(self.cleanup)
~~~~

But I don't know how to config the environment.

I have set the the environment variable `PATH`, which includes the path of  `asy.exe`, also I set the `ASYMPTOTE_DIR` as the same path.  But still the same error happens.

**Comment by asmwarrior** [comment]
OK, the problem is solved by use such command to start the xasy.

`C:\Program Files\Asymptote\GUI>python xasy.py --asypath "C:/Program Files/Asymptote/asy.exe"`

This argument is found by debugging and reading the source code of GUI.

**Comment by asmwarrior** [comment]
I think the document about how to use/start the xasy should be added, otherwise, people will meet this same issue.

**Comment by johncbowman** [comment]
The correct way to start Xasy under MSWindows is simply to click the Xasy icon.

**Comment by johncbowman** [comment]
Note: the installer used to add Asymptote to your path automatically. However, a couple of years ago we decided this was best left to the user. So to use Xasy you first need to add %PROGRAMFILES%\Asymptote (or whatever you chose as the installation directory) to your PATH environment variable.

**Comment by johncbowman** [comment]
For users that don't want to add Asymptote to their path, I have changed the installer to add
--asypath "$INSTDIR\asy.exe" to the xasy shortcut and start menu entry. I have updated
asymptote-2.69-setup.exe on sourceforge so please download a new version and try clicking the icon.
It's strange why no one reported that the icon isn't working before.

I also noticed that sourceforge by default is serving asymptote-2.69-setup-i386_32.exe to 64 bit systems so I have changed the name to asymptote-2.69-setup-32.exe. This explains the mystery of why so many MSWindows users are downloading the 32 bit version (which doesn't garbage collect well).

**Comment by asmwarrior** [comment]
Good work John.

BTW, I think I found another issue of running xasy under Windows, I will create another issue.
