### ISSUE TITLE
Array Issues in plain.asy

### ISSUE THREAD

**Issue by molecules1** [vectorgraphics/asymptote#210]
I am getting this error
`plain.asy: 263.3: reading array of length 4 with out-of-bounds index 4`
pointing at
`real clock=a[4];`
whenever I try to compile.  I [posted about this on the TeX Stack Exchange ](https://tex.stackexchange.com/questions/583833/asymptote-figures-not-rendering-in-vs-code)and there was no solution, so can someone take a look at this?  Thanks!

Also, I have had many errors with .latexmkrc (I am using VS Code with LaTeX Workshop, with MiKTeX).   
It shows this error:
```
Rule 'cusdep asy pdf c:/FileLocation/File', function 'asy'
   failed with return code = 256
```
These are the contents of the file:
```
sub asy {return system("asy '$_[0]'");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
```
Again, any help is greatly appreciated, and I have no idea if this is a bug or if it just has to do with my installation.

**Comment by johncbowman** [comment]
This means you are mixing Asymptote versions; you probably also got a warning message:

warning [version]: using possibly incompatible version 2.xx of plain.asy

Make sure that your asy version is using the base *.asy files that were shipped with it (for example, by uninstalling any old asy versions before installing the latest version, 2.69).
