### ISSUE TITLE
xasy under Windows: add text failed

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#211]
When I try to add some text inside the xasy editor, I see it just failed when I click the left mouse button in the editor.
From the command line, I see such message:

This is the command I start/open the xasy.
```
D:\Program Files\Asymptote\GUI>python xasy.py --asypath "D:/Program Files/Asymptote/asy.exe"
```

This is the error message happens when I try to add some text
```
D:/Program Files/Asymptote/plain_shipout.asy: 71.14: runtime: Command exited abnormally: dvisvgm -n -v3 --tmpdir=/cygdrive/c/Users/myusername/AppData/Local/Temp/dvisvgmBwXfel -o./xasyData_2zw205n8/_0.svg
 ./xasyData_2zw205n8/_0_.dvi --bbox=249.52bp 118.483bp 309.74bp 131.734bp
```

Note: I think the path `/cygdrive/c/Users/...` does not exit under Windows.

**Comment by johncbowman** [comment]
The cause of the problem is that cygwin tries to translate TEMP. I have replaced this with
%LOCALAPPDATA%\Temp
and will try to build a new version soon. In the meantime, you should be able to work around the problem by installing cygwin.

**Comment by johncbowman** [comment]
Also make sure that you have dvisvgm 2.9.1 or later installed.

**Comment by asmwarrior** [comment]
I can wait for the next release.
I have the latest MikTex, and the dvisvgm is 2.11.1.

**Comment by asmwarrior** [comment]
> 
> 
> The cause of the problem is that cygwin tries to translate TEMP. I have replaced this with
> %LOCALAPPDATA%\Temp
> and will try to build a new version soon. In the meantime, you should be able to work around the problem by installing cygwin.

I can confirm that the 2.70 version fixed this issue.

BTW: I see when I save the asy file from the GUI, I see there is a `KEY` argument, for example:

~~~~
label(KEY="0",Label("ddd",(-196,-61),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="1",Label("",(-72,-51),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="2",Label("abc",(-209,-140),p=rgb(0,0,0)+0.5,align=(0, 0)));
draw(KEY="3",(-388,-120)--(17,-96),rgb(0,0,0)+0.5);
~~~~

What does the `KEY` used for?

**Comment by johncbowman** [comment]
The KEY is used to identify transformed objects.

**Comment by asmwarrior** [comment]
> 
> The KEY is used to identify transformed objects.

OK, I see.
But, I think the KEY parameter should be mentioned in the Asymptote.pdf(document), for example, the `draw` command or the `label` command. I just checked it, it is not mentioned there.
