### ISSUE TITLE
Example in the „flowchart” section of the manual produces mess

### ISSUE THREAD

**Issue by marszw** [vectorgraphics/asymptote#213]
In the manual, at the bottom of p. 154 (Asymptote 2.69), there is an example of how to use the flowchart module. It once worked, but now produces all blocks drawn one on top of the other. Please, see the result:
[pr.pdf](https://github.com/vectorgraphics/asymptote/files/6018735/pr.pdf)

**Comment by johncbowman** [comment]
Page 154 of https://asymptote.sourceforge.io/doc/index.html
looks fine to me. Also see the flowchartdemo example on https://asymptote.sourceforge.io/gallery/flowchartdemo.asy

Maybe you have overridden something locally. To track this down, try running
`asy -V doc/flowchartdemo -config "" -vv`

**Comment by marszw** [comment]
OK, I just forgot to copy the
`size(0,300);`
line from the manual to the code - that's why.

Sorry, I bothered you.
