### ISSUE TITLE
Remove local character encoding

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#214]
The Debian checker tool reports that there are files containing local (not utf-8) encodings. I created a [patch](https://raw.githubusercontent.com/debian-tex/asymptote/master/debian/patches/local_charset.patch) for this. Consider to apply it to your repository. Thanks!

**Comment by johncbowman** [comment]
Thanks; I have applied the patch. Most of the accents still appear fine in emacs, but not GuibÃ©
in base/interpolate.asy. I wonder why?
