### ISSUE TITLE
xasy.py: missing xasyVersion

### ISSUE THREAD

**Issue by grozin** [vectorgraphics/asymptote#216]
grozin@bilbo ~/asymptote/asymptote-2.69/GUI $ ./xasy.py 
Traceback (most recent call last):
  File "/home/grozin/asymptote/asymptote-2.69/GUI/./xasy.py", line 6, in <module>
    from Window1 import MainWindow1
  File "/home/grozin/asymptote/asymptote-2.69/GUI/Window1.py", line 8, in <module>
    import xasyVersion
ModuleNotFoundError: No module named 'xasyVersion'
grozin@bilbo ~/asymptote/asymptote-2.69/GUI $ find -name '*.py' | xargs fgrep xasyVersion
./xasyArgs.py:import xasyVersion
./xasyArgs.py:                        version='xasy v{0}'.format(xasyVersion.xasyVersion))
./setup.py:import xasyVersion
./setup.py:    version=xasyVersion.xasyVersion,
./Window1.py:import xasyVersion
./Window1.py:        Qw.QMessageBox.about(self,"xasy","This is xasy "+xasyVersion.xasyVersion+"; a graphical front end to the Asymptote vector graphics language: https://asymptote.sourceforge.io/")

Is GUI supposed to be installed by setuptools? (currently this does not work because setup.py tries ti import xasyVersion)

**Comment by johncbowman** [comment]
xasyVersion.py is created by the normal install procedure (we don't use setuptools):

gunzip asymptote-x.xx.src.tgz
tar -xf asymptote-x.xx.src.tar
cd asymptote-x.xx
./configure
make all
make install
