### ISSUE TITLE
libncurses.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by linwaytin** [vectorgraphics/asymptote#219]
Hi, I installed the binary package following [the doc](https://asymptote.sourceforge.io/doc/UNIX-binary-distributions.html#UNIX-binary-distributions).
I got the following error when I ran `asy` 
```
asy: error while loading shared libraries: libncurses.so.6: cannot open shared object file: No such file or directory
```
I do have ncurse installed, but I can only find `libncursesw.so.6` and `libncurses.so.5` on my system. Are these equivalent to `libncurses.so.6`?

My system is Manjaro Linux.

**Comment by johncbowman** [comment]
They are not the same: you will either need to update your ncurses to version 6 or compile your own
binary that is compatible with version 5 of the ncurses library.

**Comment by linwaytin** [comment]
Thank you.
