### ISSUE TITLE
Wrong expansion of revision in Bourne Shell

### ISSUE THREAD

**Issue by mojca** [vectorgraphics/asymptote#22]
This has been reported by Karl Berry about a problem in `Makefile.in`, about the line
```
if test ! -e revision.cc -o "$(revision)" != "$(last)"; then \
```
See also #21.

> There's another, more difficult, problem.  The expansion of that line is:
> 
>   `if test ! -e revision.cc -o "2.37" != "\1"; then     \`
> 
> That `\1` is clearly not intended.  It comes from:
> 
> `last = $(shell cat revision.cc | sed -e 's/.*\"\(.*\)\";/\\1/')`
> 
> which is trying to pick out the revision number from `revision.cc`:
> `const char *REVISION="2.37";`
> 
> 1) It would be better to use `:=` than `=` on `$(shell)` lines.  That way the
> shell run only happens once, which is much simpler for expansion and
> debugging.
> 
> 2) I'm not sure that will solve the problem, though.  What works for me
> to use `\1` instead of `\\1`, but I can imagine that some shells would not
> be happy with that either.  In which case I'm left with changing
> `revision.cc` to look like:
> 
> `const char *REVISION= "2.37";`
> 
> And then use something like
> `last := $(shell awk '{print $$NF}' | sed 's/";//g')`
> 
> There should definitely be no need to \-quote the `"` in this context.
> 
> 3) Another alternative, simpler in some ways, would be not to expect
> users to run this complicated version target at all.  After all, a
> person simply compiling unmodified source never expects, or wants, to
> change the version.  They expect to compile what you give them.  I.e.,
> remove version as a dependency for asy (and probably do other things).

**Comment by johncbowman** [comment]
Fixed in commit 563d53bf8eba994e903e460361f30d93f6a5da14.
