### ISSUE TITLE
M1 Mac binary?

### ISSUE THREAD

**Issue by supakorn-ras** [vectorgraphics/asymptote#221]
I'm not a Mac user, but I should leave this here:

Are there plans to release Asymptote as a native M1 mac binary? It seems we have an incentive to do so with performance gains

**Comment by johncbowman** [comment]
Hopefully Mojca, our friendly neighbourhood MacPorts maintainer :-) will be able to maintain an m1 port as well. This site suggests that OpenGL applications still work on the m1 chip, despite OpenGL being deprecated by Apple:

https://www.geeks3d.com/20210202/apple-silicon-m1-mac-mini-arm-test-opengl/

**Comment by mojca** [comment]
Asymptote works natively on M1 on both package managers, and MacTeX 2021 will ship universal build (x86_64 + arm64) as well.
