### ISSUE TITLE
xasy crash when I click Menu->Options->Settings

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#222]
Hi, I use a portable Python([WinPython](https://winpython.github.io/), this doesn't add any changes to the windows system.

So, I start the xasy by the python prompt(WinPython Command Prompt started from the winpython):

C:\Program Files\Asymptote\GUI>python xasy.py --asypath "C:/Program Files/Asymptote/asy.exe"

When I first click `Menu->Options->Settings`, a Windows notepad is opened, and the setting file is opened. Also it looks like the setting file has `LF` as the `EOL`, then notepad can't wrap the line. Now, I close the notepad.

The next time, I click the menu item again, then xasy just crashed.

Here is the crash call stack I see in the command line:

````
Traceback (most recent call last):
  File "C:\Program Files\Asymptote\GUI\Window1.py", line 365, in openAndReloadSettings
    subprocess.run(args=self.getExternalEditor(asypath=settingsFile))
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\download\sci\Winpython64-3.8.8.0\WPy64-3880\python-3.8.8.amd64\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
````

I really don't know why it crashes in the second time. 
Thanks.

**Comment by asmwarrior** [comment]
Another issue I see is if `xasy` crashed, the `asy.exe` is running in the background, and use 100% of a one CPU core. I have to kill it in the Windows task manager.

**Comment by johncbowman** [comment]
It may have crashed when notepad got confused and tampered with the UNIX line terminators. Maybe you can suggest a better editor for Windows that is bilingual? Or you can try to convert the default settings file to DOS format and maybe all that is needed is for Windows users to have their own default settings file. Let me know what you find out. Thanks!

**Comment by o5k4r** [comment]
I recently installed xasy v2.64 on Linux and get almost the same error:

```
Traceback (most recent call last):
  File "/usr/share/asymptote/GUI/Window1.py", line 365, in openAndReloadSettings
    subprocess.run(args=self.getExternalEditor(asypath=settingsFile))
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'vi'
Aborted (core dumped)
```
Any help is appreciated ...

**Comment by asmwarrior** [comment]
Hi, I can use another editor for Windows. 
I just open the file: `C:\Users\zyh\.asy\xasyconfig.cson`

Then, I changed the content around line 57. The default is "notepad.exe"

````
Windows:
    externalEditor: "C:\\Program Files\\Notepad++\\notepad++.exe"
````

Now, the first time, I can open the setting file in notepad++, then close the notepad++. Not, when I try to click the settings menu next time, xasy get crashed.

Which means it looks like xasy internal error.

**Comment by asmwarrior** [comment]
Hi, I can use another editor for Windows. 
I just open the file: `C:\Users\username\.asy\xasyconfig.cson`

Then, I changed the content around line 57. The default is "notepad.exe"

````
Windows:
    externalEditor: "C:\\Program Files\\Notepad++\\notepad++.exe"
````

Now, the first time, I can open the setting file in notepad++, then close the notepad++. Not, when I try to click the settings menu next time, xasy get crashed.

Which means it looks like xasy internal error.

**Comment by johncbowman** [comment]
> I recently installed xasy v2.64 on Linux and get almost the same error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/share/asymptote/GUI/Window1.py", line 365, in openAndReloadSettings
>     subprocess.run(args=self.getExternalEditor(asypath=settingsFile))
>   File "/usr/lib/python3.9/subprocess.py", line 505, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'vi'
> Aborted (core dumped)
> ```
> 
> Any help is appreciated ...

We don't support obsolete versions of Asymptote; you first need to upgrade to the latest version (currently 2.70).

**Comment by johncbowman** [comment]
For now there is a simple workaround: if you don't already have a local xasyconfig.cson file when you open the settings the first time, a new one will be created. That allows you to choose an externalEditor. The default is vi. You need to change that to an editor that is actually installed (notepad, notepad++, emacs). The windows override at the bottom of the file is apparently being ignored in this situation.

**Comment by johncbowman** [comment]
Fixed in c2e38436032772e7d4a9ab5b093e0bb9ab03e59d.

To apply this fix to the 2.70 release, simply replace GUI/xasyOptions.py with

https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/GUI/xasyOptions.py

**Comment by asmwarrior** [comment]
> To apply this fix to the 2.70 release, simply replace GUI/xasyOptions.py with
> 
> https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/GUI/xasyOptions.py

I just use this new py file. I have the xasyconfig.cson

~~~~
externalEditor: "vi"

...
...

# Overrides

Windows:
    externalEditor: "C:\\Program Files\\Notepad++\\notepad++.exe"
~~~~

Then I just close the Notepad++ without change anything. After that, I click the setting dialog again, and Notepad++ opened, and I still change nothing, and close the Notepad++, now, xasy hangs.

If I change the xasyconfig.cson to some thing like:
~~~~
externalEditor: "C:\\Program Files\\Notepad++\\notepad++.exe"

...
...

# Overrides

Windows:
    externalEditor: "C:\\Program Files\\Notepad++\\notepad++.exe"
~~~~

Then, there is no hang when I close the setting file editor for the second time.

**Comment by johncbowman** [comment]
Please try again but first remove your local xasyconfig.cson file from %USERPROFILE%\.asy
If that still doesn't work, let's wait for the next release, which will ship with the new xasyOptions.py.

**Comment by asmwarrior** [comment]
> 
> 
> Please try again but first remove your local xasyconfig.cson file from %USERPROFILE%.asy
> If that still doesn't work, let's wait for the next release, which will ship with the new xasyOptions.py.

I just tried this, and it works OK! Thanks.

**Comment by o5k4r** [comment]
> > I recently installed xasy v2.64 on Linux and get almost the same error:
> > ```
> > Traceback (most recent call last):
> >   File "/usr/share/asymptote/GUI/Window1.py", line 365, in openAndReloadSettings
> >     subprocess.run(args=self.getExternalEditor(asypath=settingsFile))
> >   File "/usr/lib/python3.9/subprocess.py", line 505, in run
> >     with Popen(*popenargs, **kwargs) as process:
> >   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: 'vi'
> > Aborted (core dumped)
> > ```
> > 
> > 
> > Any help is appreciated ...
> 
> We don't support obsolete versions of Asymptote; you first need to upgrade to the latest version (currently 2.70).

I just wanted to point out that the error has nothing to do with the new version. It happens in the exactly same functions with almost the same line numbers.

**Comment by johncbowman** [comment]
If you want to apply the fix, you will need to upgrade to the latest stable asy version, 2.70 (which you should do anyway; there is no reason not to). Otherwise you will have to manually apply the patch and hope it is compatible with an older version.
