### ISSUE TITLE
I can not create polygonal line, but only multiple line segment in xasy GUI

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#223]
Here is the screen cast gif.

It looks like all the line segments are not connected, can I just create polygonal line? Maybe I'm missing some option?

![can_not_create_polygonal_line](https://user-images.githubusercontent.com/561818/112081344-7a7d2100-8bbe-11eb-9422-ab3b8b9b3f7a.gif)

**Comment by johncbowman** [comment]
Be careful not to move the mouse when you lift the pen. Otherwise you will draw 2 disconnected polygonal lines. The Xasy front end to Asymptote is still experimental; we are aware that many features are missing (for example, you currently cannot edit an existing object through the GUI).

This kind of discussion is better suited for https://sourceforge.net/p/asymptote/discussion/409349

**Comment by asmwarrior** [comment]
> 
> 
> Be careful not to move the mouse when you lift the pen. Otherwise you will draw 2 disconnected polygonal lines. 

Thanks for the help. That's the trick indeed, I haven't find any where mentions this kinds of operation. I even can't find any video tutorial about how to use the xasy.

> The Xasy front end to Asymptote is still experimental; we are aware that many features are missing (for example, you currently cannot edit an existing object through the GUI).

I see it can edit some existing object, such as drag the line end points for either straight line or bezier line. 

> 
> This kind of discussion is better suited for https://sourceforge.net/p/asymptote/discussion/409349

The bad thing about SF's forum is that sometime it blocks my post, for example, this post is months ago, and still get blocked. See the image below:

![sf_forum_error](https://user-images.githubusercontent.com/561818/112087699-67238300-8bc9-11eb-8df5-12b0e7c840d7.png)

**Comment by asmwarrior** [comment]
I see my posts in sourceforge are shown in the forum now, thanks.
But the strange thing is I can't reply there, I do not know why. I even can't find a reply entry control in the page. See image shot below:

![can_not_reply](https://user-images.githubusercontent.com/561818/112115185-ddd57600-8bf3-11eb-96cb-ca22605259b9.png)

**Comment by johncbowman** [comment]
You need to be authenticated (anonymous posts aren't allowed, to prevent
the forum from being spammed).
Maybe you were emailed a verification link that you need to confirm? Check
your account settings.

**Comment by asmwarrior** [comment]
> 
> You need to be authenticated (anonymous posts aren't allowed, to prevent the forum from being spammed). Maybe you were emailed a verification link that you need to confirm? Check your account settings.

Hi, John, it looks like my ID was not allowed to reply in the Asymptote's SF forum, but I can't post reply on other SF forum.
I tested today, and I was indeed logged into Sourceforge. The reply text control is disabled in Asymptote's forum, but not others.

This is quite strange, can you help to check whether Asymptote has some black list?

I have already contact SF's official help(I create a private ticket in their help service), and I have uploaded the screen shot in https://github.com/vectorgraphics/asymptote/issues/223#issuecomment-804711929 there.

**Comment by johncbowman** [comment]
No one is blacklisted (especially not you!). 

I see that you successfully posted a reply here, so I don't understand what the problem is:
https://sourceforge.net/p/asymptote/discussion/409349/thread/f048f3c300/

**Comment by asmwarrior** [comment]
> No one is blacklisted (especially not you!).

OK, I see.

> I see that you successfully posted a reply here, so I don't understand what the problem is:
> https://sourceforge.net/p/asymptote/discussion/409349/thread/f048f3c300/

I can't reply any more in Asymptote forum exactly after when I posted that reply.

**Comment by johncbowman** [comment]
That may correspond to the change I made in response to your query to not allow moderated posts, only authenticated posts (so that we don't have a backlog of posts silently waiting endlessly for moderation).

Check under Account Settings on Sourceforge that your email address is confirmed ("yes").
Once that is done you should be authenticated and able to post.

**Comment by asmwarrior** [comment]
Some update, I got the reply from the Sourceforge service:

> 
> The project admins changed the permissions to post. It doesn't only affects you but everyone.
> 
> We will get in touch with the project admins to let them know about the impact.
> 
> Best wishes,
> SourceForge Support

The project is the https://sourceforge.net/p/asymptote as I reported.

**Comment by johncbowman** [comment]
The impact of the change I made, in response to your query about moderated posts,
was to remove the ability of anonymous users to make moderated posts, which we don't support. If you have an issue that is important enough to post, you have to be authenticated (this requires confirming your email address). This keeps the list from being spammed, but allows authenticated users to post without moderation.
