### ISSUE TITLE
Is it typos or no?

### ISSUE THREAD

**Issue by trongtat9** [vectorgraphics/asymptote#225]
In the documentation,

`path subpath(path p, int a, int b);`
returns the subpath of p running from node a to node b. If a < b, the direction of the subpath is reversed.

`path subpath(path p, real a, real b);`
returns the subpath of p running from path time a to path time b, in the sense of point(path, real). If a < b, the direction of the
subpath is reversed.

So, by default, a > b !? or this should be " If **a > b**, the direction of the subpath is reversed. "

**Comment by johncbowman** [comment]
Thanks; changed to a > b in bbb1ed004e0962870889e85cf37b3b5ce0ef961b
