### ISSUE TITLE
xasy: inner object can not get selected

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#226]
See the screen cast gif, if a small object is covered by a larger object, then it has no changed to get selected.

I think the object select algorithm should be improved.

![inner_object_cannot](https://user-images.githubusercontent.com/561818/112163221-c7e1a880-8c27-11eb-99c6-78f60c21eb5b.gif)

**Comment by johncbowman** [comment]
Xasy is still experimental and missing many features. A new branch is under development.

**Comment by johncbowman** [comment]
You can raise and lower layers with the mouse wheel (there should eventually be a keystroke for this too).
