### ISSUE TITLE
Duplicate KEY in xasy

### ISSUE THREAD

**Issue by asmwarrior** [vectorgraphics/asymptote#229]
First, sorry if this is only a question, but I still can't post in the SourceForge's forum now.

I have one asy file saved from xasy, here is the content:

~~~~
xmap("0",(119,392,1,0,0,1));
xmap("4",(116,274,1,0,0,1));
xmap("7",(30,10,1,0,0,1));
xmap("5",(-57.1898,25.9657,2.18255,0,0,2.18255));
xmap("2",(29.4112,339.226,5.24032,0,0,5.24032));
xmap("5");
xmap("2",zeroTransform);
//xmap("2",zeroTransform);
label(KEY="0",Label("123",(-295,-116),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="1",Label("44444",(-70,-25),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="2",Label("$a^3=8$",(-213,-43),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="2",Label("$a^3=8$",(-35,-80),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="4",Label("444444",(124,-92),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="5",Label("4444445555",(-149,-55),p=rgb(0,0,0)+0.5,align=(0, 0)));
label(KEY="1",Label("666",(-52,48),p=rgb(0,0,0)+0.5+fontsize(24),align=(0, 0)));
label(KEY="2",Label("666",(-106,90),p=rgb(0,0,0)+0.5+fontsize(24),align=(0, 0)));
label(KEY="3",Label("rrrerer",(-241,168),p=rgb(0,0,0)+0.5+fontsize(24),align=(0, 0)));
label(KEY="4",Label("rrrerer",(40,-89),p=rgb(0,0,0)+0.5+fontsize(24),align=(0, 0)));
label(KEY="5",Label("rrrerer",(74,-140),p=rgb(0,0,0)+0.5+fontsize(24),align=(0, 0)));
draw(KEY="7",(-517,63)..controls (-243,59) and (-146.893,238.133)..(-32,248)..controls (92.9036,258.727) and (102.339,71.0475)..(207,13)..controls (326,-53) and (479,-32)..(618,70),rgb(0,0,0)+0.5);

size((0,0,1,0,0,1)); // Resize to initial xasy transform
~~~~

I have several questions:

1, The KEY are duplicated, is it OK?
2, What does the `xmap` function mean?
3, Any guidelines about how to use those generated asy file in a latex document? I just press the "Export" menu item, and the exported pdf does not show all the contents of the above asy. See below image shot, so those code should be manually adjusted to build a correct pdf. 

![wrongpdf](https://user-images.githubusercontent.com/561818/112230647-2af72d80-8c70-11eb-8e8c-243c234c949e.png)

**Comment by johncbowman** [comment]
There should not be duplicate keys; this is a bug and I changed your title to reflect that. The counter associated with manually drawn items isn't recalculated between Xasy runs. More development will happen on Xasy this summer. Please be patient; this code is still very experimental and it is only really
useful for repositioning objects in existing asy code. For existing asy code, the virtual KEY argument of an asy function call associated with a transformed object refers to the line number and column after the opening parenthesis in that call. None of this is documented and is still subject to change.

**Comment by asmwarrior** [comment]
Hi, thanks for the explanation. The current usage is that I can draw some object with xasy, and then tweak the generated asy file to generate a final pdf.

Now, here is a simple example:

~~~~
xmap("0",(414.687,-72.0005,2.06247,0,0,2.06247));
xmap("3",(4,146,1,0,0,1));
xmap("4",(-1,244,1,0,0,1));

draw(KEY="0",(20.5079,-16)..controls (20.5079,10.2379) and (-0.762111,31.5079)..(-27,31.5079)..controls (-53.2379,31.5079) and (-74.5079,10.2379)..(-74.5079,-16)..controls (-74.5079,-42.2379) and (-53.2379,-63.5079)..(-27,-63.5079)..controls (-0.762111,-63.5079) and (20.5079,-42.2379)..cycle,rgb(0,0,0)+0.5);

draw(KEY="1",(142,-11)--(68.2968,-62.4474)--(149.703,-100.553)--cycle,rgb(0,0,0)+0.5);

draw(KEY="2",(-263,-116)--(-188,50),rgb(0,0,0)+0.5);

draw(KEY="3",(-156,-104)--(-52,-97)--(33,47)--(244,-9),rgb(1,0,0)+3.0);

label(KEY="4",Label("abc",(346,-100),p=rgb(0,0,0)+0.5,align=(0, 0)));

import graph;
xaxis("$x$");
yaxis("$y$");

size((0,0,1,0,0,1)); // Resize to initial xasy transform
~~~~

Please note the three lines were added by the tweak stage.
~~~~
import graph;
xaxis("$x$");
yaxis("$y$");
~~~~

Now, the problem is the generated pdf, the two axis does not span the width and height of the whole picture. The the image shot below. Is it because some `xmap` functions is involved in this asy code?

![tweak_asy](https://user-images.githubusercontent.com/561818/112417168-f6639e80-8d61-11eb-9c77-cc96c198ba03.png)

BTW: what does the 6 parameters in xmap's parameter `(414.687,-72.0005,2.06247,0,0,2.06247)` means? I see it is a transformation, but I don't know its definition of each values, is it something like [Transformation matrix - Wikipedia](https://en.wikipedia.org/wiki/Transformation_matrix)? It allows shift, rotate and scale?

Also, I don't understand the 6 parameters in the last line `size((0,0,1,0,0,1)); // Resize to initial xasy transform` means.

Thanks.

**Comment by johncbowman** [comment]
Yes, the deferred drawing routines don't yet take account of the xmap
transformations.

https://asymptote.sourceforge.io/doc/Transforms.html#Transforms
