### ISSUE TITLE
bool operator ==(real a, real b) is true or false ?

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#230]
```
unitsize(1cm);
import geometry;
path ligne1=(-3,1){dir(45)}..(-1,2)..{dir(10)}(4,0);
path ligne2=(-3,-1){dir(45)}..(0,3)..(1.5,-1)..{dir(80)}(3,2);
ligne2=shift(0,-3)*ligne2;

path subpath_ligne1=subpath(ligne1,reltime(ligne1,0.2),reltime(ligne1,0.45));
path testpath=subpath(ligne2,reltime(ligne2,0.33),reltime(ligne2,1));
path subpath_ligne2=subpath(testpath,0,arctime(testpath,arclength(subpath_ligne1)));

write(arclength(subpath_ligne1) == arclength(subpath_ligne2)); // false
write((point) (arclength(subpath_ligne1),0) == (point) (arclength(subpath_ligne2),0)); // true
```
Does Asymptote have a built-in function for testing the equivalence between two real numbers?

**Comment by johncbowman** [comment]
The answer to the question in your title is that it depends on whether the IEEE double precision floating point representations of a and b are equal or not. As is taught in any numerical analysis course, you should take care when using operator == on floating point types without specifying a tolerance;
numerical precision issues can cause surprises!

If you want to get consistent results in your example, change the last two lines to

```
EPS=0; // Try commenting this line out!
write(abs(arclength(subpath_ligne1)-arclength(subpath_ligne2)) < EPS); 
write((point) (arclength(subpath_ligne1),0) == (point) (arclength(subpath_ligne2),0));
```
