### ISSUE TITLE
Is this a strange behavior of miterlimit?

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#231]
Code:
```
unitsize(1cm);
pair[] z;
z[0]=(3,1);
z[1]=(0,0);
z[2]=(3,0);
// draw(shift(-5,0)*(z[0]--z[1]--z[2]),scale(30)*.8red);
draw(z[0]--z[1]--z[2],miterjoin+scale(30)*.8green);
draw(shift(5,0)*(z[0]--z[1]--z[2]),miterjoin+miterlimit(5)+scale(30)*.8blue);
for (int i=0; i<z.length; ++i){
  dot(scale(0.5)*((string) i),z[i],dir(90));
  dot(scale(0.5)*((string) i),shift(5,0)*z[i],dir(90));
}
shipout(bbox(2mm,invisible));
```
What do you see if you uncomment `// draw(shift(-5,0)*(z[0]--z[1]--z[2]),scale(30)*.8red);`?
On my computer, Win 7 + Notepad++ +TexLive.
[Image](https://imgur.com/9aZjm1O)

**Comment by johncbowman** [comment]
I never finished implementing bounds for this case back in 2009 and was expecting to hear about this someday. Congratulations, you are the first to notice! We will try to fix it for the next release.

**Comment by justonlyasy** [comment]
Additional: As defined in `plain_paths.asy`, **real[] times(path p, real x)** and **real[] times(path p, explicit pair z)** should have **fuzz** or not?

**Comment by johncbowman** [comment]
In commit 2d4c3cde07d7498301f337277522c69586deae76 I added the missing fuzz parameters.
