### ISSUE TITLE
gsl.cc, can it be improved and updated the new functions? 

### ISSUE THREAD

**Issue by trongtat9** [vectorgraphics/asymptote#232]
The current stable version of GSL is [GSL-2.6](https://www.gnu.org/software/gsl/) but gsl.cc is now 2.0. I'm sure that it have more fixed bugs or new functions.
Can Asymptote do a new release for it?

**Comment by johncbowman** [comment]
What specific functions would you like to add? We can add required functions upon request.

**Comment by trongtat9** [comment]
Sorry but, you can tell me know why does gsl.cc which you have written not support **ALL** functions? Because, [GSL](https://www.gnu.org/software/gsl/doc/html/index.html) has not only special functions but also more and more other functions. An example about [the accuracy of gsl compare with Asymptote internal computation](https://tex.stackexchange.com/a/538575/236162).
Asymptote with the support of [GSL](https://www.gnu.org/software/gsl/doc/html/index.html) is a special point to draw almost mathematical figures.

**Comment by johncbowman** [comment]
If you look at gsl.cc you will see that the interface between the GSL library and the asy virtual machine
requires substantial hand coding for each desired GSL function. The link you refer to has nothing to do with the version of GSL. Approximating the value of a special function using a graphical technique is not going to be as good as an analytical treatment. Adding support for more functions in a new version of GSL is not going to change the situation. 

By the way, Asymptote compiles fine with GSL 2.3 (the latest on Fedora 30); I haven't yet tried linking against GSL 2.6 but no issues have been reported.
