### ISSUE TITLE
ghostscript-9.54.0 breaks asy install

### ISSUE THREAD

**Issue by balducci** [vectorgraphics/asymptote#234]
hello

recently released ghostscript-9.54.0 breaks asy install (make install)
with:

    ----8<----
    cd doc && make man
    make[1]: Entering directory '/home/balducci/tmp/install-us-d/asymptote-7581.d/asymptote-7581/doc'
    ../asy -dir ../base -config "" -render=0 -f pdf -noprc CAD1.asy
    Error: /rangecheck in .installpagedevice
    Operand stack:
       --nostringval--   --dict:215/221(ro)(L)--   --nostringval--   --nostringval--   --nostringval--   false   --nostringval--
    Execution stack:
       %interp_exit   .runexec2   --nostringval--   restore   --nostringval--   2   %stopped_push   --nostringval--   restore   restore   false   1   %stopped_push   1990   1   3   %oparray_pop   1989   1   3   %oparray_pop   1988   1   3   %oparray_pop   1894   1   3   %oparray_pop   restore   1875   1   3   %oparray_pop   restore   restore
    Dictionary stack:
       --dict:760/1123(ro)(G)--   --dict:0/20(G)--   --dict:75/200(L)--
    Current allocation mode is local
    Last OS error: No such file or directory
    GPL Ghostscript 9.54.0: Unrecoverable error, exit code 1
      _shipout(prefix,f,currentpatterns,format,wait,view,t);
              ^
    ../base/plain_shipout.asy: 104.11: runtime: shipout failed
    make[1]: *** [Makefile:42: CAD1.pdf] Error 1
    make[1]: Leaving directory '/home/balducci/tmp/install-us-d/asymptote-7581.d/asymptote-7581/doc'
    ---->8----

No problems with ghostscript-9.53 (after https://github.com/vectorgraphics/asymptote/issues/176)

thanks a lot for your valuable work

ciao
-gabriele

**Comment by johncbowman** [comment]
What version of asy are you using? I can't reproduce this. The following works fine for me using bbb1ed004e0962870889e85cf37b3b5ce0ef961b:
```
cd doc
../asy -dir ../base -gs=/usr/local/src/ghostscript-9.54.0-linux-x86_64/gs-9540-linux-x86_64  -config "" -render=0 -f pdf -noprc CAD1.asy

```

**Comment by balducci** [comment]
> What version of asy are you using? I can't reproduce this. The following works fine for me using [bbb1ed0](https://github.com/vectorgraphics/asymptote/commit/bbb1ed004e0962870889e85cf37b3b5ce0ef961b):

apologies: I have tried to build with a ghostscript-9.54.0 from archlinux and it works (with asymptote master)

Since I install ghostscript from source, most probably the problem is somewhere in my installation script  for gs (that script has worked for ages, though)

Thank you very much for taking the time to look into this: I now have a definite direction to go for fixing things
