### ISSUE TITLE
Stray -I/usr/include/tirpc

### ISSUE THREAD

**Issue by dmacks** [vectorgraphics/asymptote#237]
Building asymptote-2.69 on OS X 10.13, I don't have /usr/include/tirpc, but an -I for it is hardcoded into the compiler flags. According to configure.ac, this seems to be for support of tirpc/rpc/rpc.h, which don't have anywhere on my system. But config.h *does* define HAVE_RPC_RPC_H and ./configure reports:

```checking for library containing xdrstdio_create... none required```

Is this #define mis-named (should be XSTREAM_H)? Should there be separate autoconf tests for a certain header (with possible added -I search paths if necessary) vs a function that might not need it?

**Comment by johncbowman** [comment]
Under macOS Big Sur (OS 11.0.1) no tirpc library is required or included in the compiler flags for the current git version of asy.
The system version of rpc should work out of the box under Mac OS. You can test your setup with the example here:

https://www.math.ualberta.ca/~bowman/xstream.html

**Comment by dmacks** [comment]
configure.ac, starting at line 230 (git head):
```
INCL=$INCL" -I/usr/include/tirpc"

if test "$OSTYPE" = "msdos"; then
CPPFLAGS=$CPPFLAGS" -D__MSDOS__ -I/usr/include/w32api -I/usr/include -DCALLBACK=__stdcall $INCL"
else
CPPFLAGS=$CPPFLAGS" $INCL"
fi
```

So -I/usr/include/tirpc appears to be passed to the compiler. The rest of my comments were trying to decipher what exactly was being tested or needed, as soon as I saw commands like:
```
++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -DUSEGC  -D_THREAD_SAFE -pthread -DFFTWPP_SINGLE_THREAD -I/sw/include -I. -I/sw/include/gc  -I/usr/include/tirpc -std=c++11 -Os -MD -o camperror.o -c camperror.cc
```
scrolling by. Though it did compile successfully.

**Comment by johncbowman** [comment]
-I/usr/include/tirpc is just a search path. It will ignored if you don't have it. The configure test pertains to the library flag -ltirpc.

**Comment by dmacks** [comment]
Ah, that makes sense. Confusing to see it is all (suggested I was missing something or needed to port some third-party library to enable some feature).
