### ISSUE TITLE
View (-V) flag does not work in non-interactive shell?

### ISSUE THREAD

**Issue by jasonhan-vassar** [vectorgraphics/asymptote#240]
Hi, I'm running `asy -V ./file.asy` in a non-interactive shell (spawned by a text editor) and the output is not being viewed. When the shell is interactive, `-V` works as intended. Is this intentional? If not, can anyone reproduce this?

**Comment by johncbowman** [comment]
Yes, this is intentional (how could you view in a non-interactive shell?)

**Comment by jasonhan-vassar** [comment]
I was under the impression `-V` opens the output file with the default program. Is that not what it does? I was hoping the flag was an easy way to do this.
