### ISSUE TITLE
When drawing this graph, in Asymptote and in WolframAlpha online, I get two different outputs, why?

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#242]
I want to draw this function
![181372147_10158407658933657_7093156983402451569_n](https://user-images.githubusercontent.com/52594258/116988939-4b001f00-acfb-11eb-81de-45b53b57fcfa.jpg)

Here is my Asymptote code,

```
//settings.render=15;

import graph3;
import palette;
size(10cm);
currentprojection=orthographic(4,2,3);

real f(pair z) {return (z.x==z.y) ? 0 : z.x^2*z.y^2/(z.x^2*z.y^2+(z.x-z.y)^2);}

surface s=surface(f,(-5,-5),(5,5),nx=12,Spline);
s.colors(palette(s.map(zpart),Rainbow()));
draw(s,meshpen=black+0.7bp,render(merge=true));

draw(Label("$y$",1),(0,0,0)--(0,6,0),red,Arrow3);
draw(Label("$x$",1),(0,0,0)--(6,0,0),red,Arrow3);
draw(Label("$z$",1),(0,0,0)--(0,0,5),red,Arrow3);

label("$z=\frac{x^2y^2}{x^2y^2+(x-y)^2}$",(1,3,5),NE);
```
![workspace (1)](https://user-images.githubusercontent.com/52594258/116989388-dda0be00-acfb-11eb-8bc9-91e52f815f91.png)

And this is a WolframAlpha output,
![Capture](https://user-images.githubusercontent.com/52594258/116989588-22c4f000-acfc-11eb-950e-e913afd533b6.PNG)

Please help!
Thanks.

**Comment by asmwarrior** [comment]
They are not the same function, do they?
At least for the condition`if (x==y)`, the asymptote output is `0`, while the WolframAlpha is `1`.

**Comment by justonlyasy** [comment]
Yes, the WolframAlpha is 1 if (x==y).
