### ISSUE TITLE
Can Asymptote make all separate files have the same effect as bool global; of animation.asy?

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#244]
My code,
```
settings.prc=false;
settings.render=5;
import graph3;
import palette;
import math; // for sinh,cosh

size(6cm);

currentprojection=orthographic(1,2,1);

string[] files;
typedef triple Triple(pair);
Triple f(real x){
  return new triple(pair t){
    real u=t.x,v=t.y;
    real a=  cos(x)*sinh(v)*sin(u)+sin(x)*cosh(v)*cos(u);
    real b=  -cos(x)*sinh(v)*cos(u)+sin(x)*cosh(v)*sin(u);
    real c=  u*cos(x)+v*sin(x);
    return (a,b,c);
  };
}
int numberofframes=3;

real[] theta=uniform(-pi,pi,numberofframes);
path3 boundingbox = circle((1,2,1), r=4, normal=(1,2,1));
for (int i=0; i <= numberofframes; ++i)
{
files[i]="T"+(string) i;
picture pic;
draw(pic, boundingbox);
surface s=surface(f(theta[i]),(-pi,-pi/2),(pi,pi/2),20,Spline);
s.colors(palette(s.map(zpart),Rainbow()));
draw(pic,s,meshpen=black+0.6bp,render(merge=true));
add(pic);
shipout(files[i],bbox(invisible));
erase();
}
```
I want to know how to replace two commands
```
path3 boundingbox = circle((1,2,1), r=4, normal=(1,2,1));
draw(pic, boundingbox);
```
in Asymptote. 
My problem is all separate files _have no the same size_. And if I use module animation.asy, I will get _error: out of memory_.
![T0](https://user-images.githubusercontent.com/52594258/118281573-908ccb00-b4f7-11eb-826a-84e2aec97d5c.png)

**Comment by justonlyasy** [comment]
I used this `trick` for [my answer](https://tex.stackexchange.com/a/615968/236162). However, I still look forward to a good method in `Asymptote`.

**Comment by johncbowman** [comment]
I'm not sure what the issue is here or what your question is. I ran your example with both Asymptote version 2.70 and 2.73 and the sizes of the generated eps files are all the same. For Asymptote 2.73, the bounding boxes of the generated eps files are identical:

%%HiResBoundingBox: 211.679994 334.889990 382.579934 505.817985
