### ISSUE TITLE
Crashes and wrong results with opacity in Ubuntu

### ISSUE THREAD

**Issue by fmariofilho** [vectorgraphics/asymptote#246]
I have been (like many others it seems) having very strange results when trying to use opacity. The code I am compiling is:

```
settings.outformat = "pdf";
settings.prc = false;

import three;

size(4cm);

draw(unitsphere, material(palegray + opacity(0.25), shininess=0.5));
draw(circle(c=0.5Z, r=sqrt(1 - 0.5^2), normal=Z));
draw(circle(c=0.8Z, r=sqrt(1 - 0.8^2), normal=Z));
```
On my MacBook running asy version 2.41 and ghostscript 9.21 I get the expected result.

On my Ubuntu system I get wildly different results:

- With asy 2.67 installed with the package manager, I simply get segmentation fault.
- With asy 2.70 (latest version, compiled by me from source), I get a ghostscript error (/undefined in .setfillconstantalpha) when using ghostscript 9.50
- When I remove the opacity, I don't get an error but the resulting image is garbled (see attachment).

I tried to install asy 2.41 and ghostscript 9.21 on my Ubuntu system to see if it would work: it doesn't.
[link.pdf](https://github.com/vectorgraphics/asymptote/files/6496281/link.pdf)

**Comment by johncbowman** [comment]
We don't support obsolete software. You need to upgrade to asy 2.70 and ghostscript 9.53. Don't waste time on old versions.
In particular, ghostscript versions are unfortunately not backwards compatible.

Make sure that you have OpenGL support (your attachment shows flattened postscript produced with settings.render=0 or on a system lacking OpenGL support; this is _not_ normally what one wants). If you don't want to install the required GPU libraries, you may still be able to produce WebGL output with settings.outformat="html". So see what support you have:

asy --version

The opacity bug in OpenGL is well known and not limited to Asymptote. A workaround is being developed: https://github.com/vectorgraphics/asymptote/issues/35
