### ISSUE TITLE
asymptote.py does not work

### ISSUE THREAD

**Issue by gtrain111** [vectorgraphics/asymptote#25]
Post from https://sourceforge.net/p/asymptote/discussion/409349/thread/f2e59550/
Operating system: Windows 10
TeX Distribution: Miktex
Asymptote Version: 2.38

When using asymptote in python (through the asymptote.py package), either no output is produced or error message is given. 
My code (from this link: http://asymptote.sourceforge.net/doc/Interactive-mode.html):

```
from asymptote import *
g=asy()
g.size(200)
g.draw("unitcircle")
g.send("draw(unitsquare)")
g.fill("unitsquare, blue")
g.clip("unitcircle")
g.label("\"$O$\", (0,0), SW")
```

The asymptote.py file is in C:\Python27\Lib\site-packages\asymptote.py. It contains the following (unedited from default) lines:

```
    # Python module to feed Asymptote with commands
    # (modified from gnuplot.py)
from subprocess import *
class asy:
    def __init__(self):
        self.session = Popen(["asy", "-quiet", "-interactive"],stdin=PIPE)
        self.help()
    def send(self, cmd):
        self.session.stdin.write(cmd+'\n')
        self.session.stdin.flush()
    def size(self, size):
        self.send("size(%d);" % size)
    def draw(self, str):
        self.send("draw(%s);" % str)
    def fill(self, str):
        self.send("fill(%s);" % str)
    def clip(self, str):
        self.send("clip(%s);" % str)
    def label(self, str):
        self.send("label(%s);" % str)
    def shipout(self, str):
        self.send("shipout(\"%s\");" % str)
    def erase(self):
        self.send("erase();")
    def help(self):
        print "Asymptote session is open.  Available methods are:"
        print "    help(), size(int), draw(str), fill(str), clip(str), label(str), shipout(str), send(str), erase()"
    def __del__(self):
        print "closing Asymptote session..."
        self.send('quit');
        self.session.stdin.close();
        self.session.wait()

if __name__=="__main__":
    g = asy()
    g.size(200)
    g.draw("unitcircle")
    g.send("draw(unitsquare)")
    g.fill("unitsquare, blue")
    g.clip("unitcircle")
    g.label("\"$O$\", (0,0), SW")
    raw_input("press ENTER to continue")
    g.erase()
    del g
```

When I execute my program in pycharm, it usually gives the error
-: 4.1: syntax error
error: could not load module '-'
If I am executing line by line from the console, the asymptote window opens, but as I execute my commands, no output is given. 
How can I fix this?

**Comment by johncbowman** [comment]
Thanks for pointing this out.
asymptote.py has been fixed to work with recent versions of Asymptote:

https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/base/asymptote.py
