### ISSUE TITLE
A bit problem with bool alias(T[] a, T[] b)

### ISSUE THREAD

**Issue by trongtat9** [vectorgraphics/asymptote#250]
Please check the following code

```
int[] A=sequence(5);
int[] C=sequence(new int(int x){ return x;},5);
int[] a={1,2,3,4};
int[] b={1,2,3,4};
write(alias(A,C)); // false
write(alias(a,b)); // false
write(alias(A,A)); // true
write(alias(b,b)); // true
```
As in the documentation,

bool alias(T[] a, T[] b)
`returns true if the arrays a and b are identical;`

**Comment by johncbowman** [comment]
In the first two cases, the arrays are distinct, even though they contain the same values.
Probably you meant to use all(a==b) instead.
