### ISSUE TITLE
3d paths (path3) get rendered wrong.

### ISSUE THREAD

**Issue by doeblerh** [vectorgraphics/asymptote#26]
Under some circumstances, path3 does not render properly. A minimal example is included. The red dots depict where the path (black line) should be rendered. They differ quite dramatically. The problem occurs in OpenGL view (asy -V) as well as in rendering to eps.

Asymptote versions: 2.38, 2.39-26
OS: arch linux
glibc 2.24-2

[minimal.asy.txt](https://github.com/vectorgraphics/asymptote/files/435612/minimal.asy.txt)

![minimal](https://cloud.githubusercontent.com/assets/21227649/17946483/dc319300-6a48-11e6-97d1-020886c60cf4.png)

**Comment by johncbowman** [comment]
In svn, I have reduced defaultrender.tubegranularity from 0.005 to 0.001. If this happens again,
you can adjust this value further or use thin() to draw an OpenGL thin line (thick lines aren't universally supported in OpenGL so we have to draw a tube).
