### ISSUE TITLE
Error: open_stackdumpfile: Dumping stack trace to asy.exe.stackdump

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#262]
Considering the following code:

```
import graph;

unitsize(1cm);
typedef real newreal(real);

newreal f(real a){ 
  return new real(real x){ 
    return cbrt(x^2)+sqrt(5-x^2)*sin(a*pi*x);
  };
}

guide yourgraph1=graph(f(10),-sqrt(5)+sqrtEpsilon,0,500);
guide yourgraph2=graph(f(10),0,sqrt(5)-sqrtEpsilon,500);

draw(yourgraph1,blue);
draw(yourgraph2,red);
label("$f(x)=\sqrt[3]{x^2}+\sqrt{5-x^2}.\sin(a\pi x)$",(0,3.5));
shipout(bbox(mm,invisible));
```
When I do not use `sqrtEpsilon`, I get the error `open_stackdumpfile: Dumping stack trace to asy.exe.stackdump`.
If I use `realEpsilon` instead of `sqrtEpsilon`, I also get the above error.

My machine: Windows 7 64bit, 8GB Ram.

**Comment by johncbowman** [comment]
That example runs fine for me under Windows 10. You probably have an installation issue.
Be sure to use ghostscript 9.53.3 (not the broken 9.54.0 version):

https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9533/gs9533w64.exe

We also recommend TeXLive, not MikTeX.
See
https://sourceforge.net/p/asymptote/discussion/409349/thread/8f504d057a/
