### ISSUE TITLE
Cannot fill noncyclic contours

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#263]
I want to reproduce this image in Asymptote but ...
![qymGO](https://user-images.githubusercontent.com/52594258/129507146-04ac4b17-267d-4774-b450-9492ad1d2769.png)
Here is my code,
```
import graph;
import palette;
import contour;

size(350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=100;
int Divs=15;

bounds range=bounds(0,5.1);

real[] Cvals=uniform(range.min,range.max,Divs);
guide[][] g=contour(f,a,b,Cvals,N);
pen[] Palette=quantize(BWRainbow(),Divs);

pen[][] interior=interior(g,extend(Palette,grey,black));
fill(g,interior);
draw(g);
limits(a-(0.3,0.3),b+(0.3,0.3));
xaxis("$x$",BottomTop,LeftTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
yaxis("$y$",LeftRight,RightTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
shipout(bbox(mm,invisible));
```
![Capture](https://user-images.githubusercontent.com/52594258/129507261-5fc3f33d-6ea8-4fe5-b8f4-d4be35f3f04d.PNG)

Can Asymptote fill for uncyclic contours like my image?

**Comment by yangxing844** [comment]
maybe you can try to make all the cycle and fill them first and then use  ```clip```   command to clip the part you want?
```   
import graph;
import palette;
import contour;

size(350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=100;
int Divs=15;

bounds range=bounds(0,1.1);

real[] Cvals=uniform(range.min,range.max,Divs);
guide[][] g=contour(f,a,b,Cvals,N);
pen[] Palette=quantize(BWRainbow(),Divs);

pen[][] interior=interior(g,extend(Palette,grey,black));
fill(g,interior);
draw(g);

clip(box((-2.6,-2.6),(2.6,2.6)));
xaxis("$x$",BottomTop,LeftTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
yaxis("$y$",LeftRight,RightTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
```   
this is the output 
![learn](https://user-images.githubusercontent.com/48230905/132443195-976ce2f3-68c9-4ae8-bbf5-c75e0361e166.png)

**Comment by johncbowman** [comment]
The suggested solution works in this instance but we still need a general solution for cases that cannot be extended to closed contours (for example, horizontal contour lines).

This is actually a very old issue that got postponed when we transitioned from sourceforge to github:
https://sourceforge.net/p/asymptote/bugs/84/

**Comment by johncbowman** [comment]
Good news: 13 years after the original bug report was submitted, I have finally found a much simpler solution: simply quantize a color density image (see imagecontour.asy). If you draw the contour lines wide enough (or draw the image at high-enough resolution), pixelization artifacts will be hidden and what results gives the illusion of vector graphics without the complexity of trying to fill noncyclic (unclosed) curves. The quantized image is less accurate but more appealing than the unquantized one (compare the attached images), especially for pedagogical purposes.

I will commit an update tomorrow that supports this functionality and then close this issue. I may replace fillcontour.asy (which has caused confusion, due to this unresolved issue) with the quantized example, even though the name fillcontour is perhaps a bit misleading.

![imagecontourstep](https://user-images.githubusercontent.com/13231852/147808485-92c533fd-d855-4bd2-b7ed-fdff724ae88b.png)

![imagecontour](https://user-images.githubusercontent.com/13231852/147808585-86f69bf7-b23c-4500-a2bb-345d9cf5352d.png)

**Comment by justonlyasy** [comment]
You can review fillcontour.asy to remove duplicate code.

**Comment by justonlyasy** [comment]
I cannot get a desired output, can you give me a suggestion?
The contour lines is not same with...
```
import graph;
import palette;
import contour;

size(350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=15;
int divs=1;
int n=Divs*divs;

defaultpen(1bp);
pen Tickpen=black;
pen tickpen=gray+0.5*linewidth(currentpen);
pen[] Palette=quantize(BWRainbow(),n);

bounds range=image(f,Range(0,5.1),a,b,600,Palette,n);

real[] Cvals=uniform(range.min,range.max,Divs);

draw(contour(f,a,b,Cvals,N),Tickpen+squarecap+beveljoin);

limits(a-(0.3,0.3),b+(0.3,0.3));
xaxis("$x$",BottomTop,LeftTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
yaxis("$y$",LeftRight,RightTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
```
![image](https://user-images.githubusercontent.com/52594258/147877281-483fc678-b70e-42f8-8358-2fbc9475c609.png)

**Comment by johncbowman** [comment]
Your color density plot was not produced on the full data Range. Start with the example 
https://asymptote.sourceforge.io/gallery/2Dgraphs/fillcontour.asy
and adapt it to your function (keeping only the major contours):
![test](https://user-images.githubusercontent.com/13231852/147881492-6c299cc2-5505-47d7-b5e0-6805ea02d685.png)

```
import graph;
import palette;
import contour;

size(350,350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=15;

defaultpen(1bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);

real[] Cvals=uniform(range.min,range.max,Divs);
draw(contour(f,a,b,Cvals,N,operator --),Tickpen+squarecap+beveljoin);

xaxis("$x$",BottomTop,LeftTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
yaxis("$y$",LeftRight,RightTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
```

**Comment by johncbowman** [comment]
The contour line caps in this example could be improved by changing squarecap to extendcap and slightly cropping:

![test](https://user-images.githubusercontent.com/13231852/147882079-6eec5f16-54ea-47e2-9499-3c52e2834253.png)

```
import graph;
import palette;
import contour;

size(350,350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=15;

defaultpen(1bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);

real[] Cvals=uniform(range.min,range.max,Divs);
draw(contour(f,a,b,Cvals,N,operator --),Tickpen+extendcap+beveljoin);

pair eps=(1,1)*0.02;
limits(a+eps,b-eps);
crop();

xaxis("$x$",BottomTop,LeftTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
yaxis("$y$",LeftRight,RightTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
```

**Comment by justonlyasy** [comment]
Excuse me, the last curiosity.

This code runs approximately **98%** in my desired picture

```
// settings.render=8;
import graph;
import palette;
import contour;

size(350,350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=16;

defaultpen(1bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);

real[] Cvals=uniform(range.min,range.max,Divs);
draw(contour(f,a,b,Cvals,N),Tickpen+squarecap+beveljoin);

crop(); // before the limits command.
limits(a-(0.3,0.3),b+(0.3,0.3));

xaxis("$x$",BottomTop,LeftTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
yaxis("$y$",LeftRight,RightTicks(Size=4,Ticks=new real[]{-6,-4,-2,0,2,4,6}));
```
except for

![workspace (1)](https://user-images.githubusercontent.com/52594258/148091138-7e55e31d-122d-4ea5-8268-966311cd2368.png)

Does this work normally? Can we delete them?

**Comment by johncbowman** [comment]
I don't know what 98% refers to.

Those circled marks are contour lines. If you don't want them, you can crop them out.
The crop command has to go after the limits command and the limits command should reduce, not expand the range in order for this to work. See the example I already posted.
Putting crop before the limits command has no effect.

**Comment by johncbowman** [comment]
If you are simply trying to get (-6,-6) and (6,6) to show up on your axes, here's how
(or if for some reason you want a gap around the colour density image, you can use the commented draw commands instead):

 
![test](https://user-images.githubusercontent.com/13231852/148139488-fa7084ae-0d95-4e5a-b8fa-a210c24b12d4.png)



```
import graph;
import palette;
import contour;

size(350,350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=16;

defaultpen(1bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);

real[] Cvals=uniform(range.min,range.max,Divs);
draw(contour(f,a,b,Cvals,N),Tickpen+extendcap+beveljoin);

pair eps=(1,1)*0.03;
limits(a+eps,b-eps);
crop();

draw(a,invisible);
draw(b,invisible);

//draw(a*1.05,invisible);
//draw(b*1.05,invisible);

xaxis("$x$",BottomTop,LeftTicks(Size=4),above=true);
yaxis("$y$",LeftRight,RightTicks(Size=4),above=true);

```

**Comment by justonlyasy** [comment]
Done, 99.99%...
Thanks again.

```
import graph;
import palette;
import contour;

size(350,350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=16;

defaultpen(.9bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);

real[] Cvals=uniform(range.min,range.max,Divs);

Cvals.pop(); // <--- This command solves "Those circled marks are contour lines".

draw(contour(f,a,b,Cvals,N),Tickpen+extendcap+beveljoin);

crop(); // I don't know the reason "The crop command has to go after the limits command" but this works as expected.
limits(a-(0.3,0.3),b+(0.3,0.3));
draw(box(a,b),cyan+opacity(.5));

xaxis("$x$",BottomTop,LeftTicks(Size=4,size=2));
yaxis("$y$",LeftRight,RightTicks(Size=4,size=2));
```
![image](https://user-images.githubusercontent.com/52594258/148193624-3a5441e8-f9ac-41ad-b8f4-14b163b2c78f.png)

**Comment by johncbowman** [comment]
The crop command, implemented properly, would fix the flaw shown in your image.
It belongs _after_ the call to limits. The result below looks much better; you'll need Asympote version 2.75-33 (already available on http://asymptote.ualberta.ca). I will likely release a new version later today.

![test](https://user-images.githubusercontent.com/13231852/148455332-e1f35b21-a0af-44d2-aada-7529c84f7e39.png)

```
import graph;
import palette;
import contour;

size(350,350);

settings.gsOptions="-r1200x1200";

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}

int N=200;
int Divs=16;

defaultpen(.9bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);

real[] Cvals=uniform(range.min,range.max,Divs);

Cvals.pop(); // Optionally remove final contour line

draw(contour(f,a,b,Cvals,N),Tickpen+extendcap+beveljoin);

pair eps=(1,1)*0.03;
limits(a+eps,b-eps);
crop();

draw(box(a+eps,b-eps),cyan+opacity(0.5));

pair gap=(1,1)*0.3;
draw(a-gap,invisible);
draw(b+gap,invisible);

xaxis("$x$",BottomTop,LeftTicks(Size=4,size=2),above=true);
yaxis("$y$",LeftRight,RightTicks(Size=4,size=2),above=true);

```

**Comment by justonlyasy** [comment]
With your new code, when I comment `draw(box(a+eps,b-eps),cyan+opacity(0.5));` and see the **svg** output on http://asymptote.ualberta.ca/. Is it normal? (For my computer, pdf and png are normal.)
