### ISSUE TITLE
Constructing new User-defined operators

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#269]
In the main documentation,

The following symbols may be used with operator to define or redefine operators on structures
and built-in types:
```
+ - * / % ^ ! < > == != <= >= & | ^^ .. :: -- --- ++
<< >> $ $$ @ @@ <>
```
Why does Asymptote not have a combined construction like this
```
path operator --+(pair A, pair B)
{
  return A--(A+B);
}
```
As in the code above, I use operators `--` and `+` to connect them to `--+`!

**Comment by johncbowman** [comment]
The operator --+ would likely not have widespread use. Asymptote inherited --- from metapost. There are syntactical considerations in defining new operators that place restrictions on the allowable operators. Choose one of the available possibilites.
Perhaps ++ would be a good choice.
