### ISSUE TITLE
intersectionpoints line and parabola error?

### ISSUE THREAD

**Issue by quanhinh9** [vectorgraphics/asymptote#271]
Hi, 

I use intersectionpoints function of parabola and line but get error.

My code in http://asymptote.ualberta.ca:

```asy
import geometry;
import graph;
unitsize (1cm);
		
point A = (-4, 3), B =(4, 2), C=(-4, -2), D = (2, 2), F = (0, 3); 
parabola pa = parabola(F, line(A, B)); draw(pa);
draw(line(A, B));
line l = line (C, D); draw(l, Cyan);
point [] pv = intersectionpoints(pa, parallel(pa.V, l));
dot(Label("$pv_1$", align = SE), pv[1]);
```
point pv[1] does not exist?

**Comment by KevinArlin** [comment]
It looks like your line does not intersect your parabola.

**Comment by johncbowman** [comment]
![workspace](https://user-images.githubusercontent.com/13231852/147439619-a16a8cca-eb7a-4978-953e-2018bfeb8b75.png)
I don't know the geometry package very well, but you first want to draw a line segment, not an infinite `line(A,B)`. An indeed, when you do this, you see that KevinArlin is correct: the black curves do not intersect:

```
import geometry;
import graph;
unitsize (1cm);
		
point A = (-4, 3), B =(4, 2), C=(-4, -2), D = (2, 2), F = (0, 3); 
line L=line(A,false,B,false);
parabola pa = parabola(F, L); draw(pa);
draw(L);
line l = line (C, D); draw(l, Cyan);
point [] pv = intersectionpoints(pa, parallel(pa.V, l));
```
