### ISSUE TITLE
Opacity issue in asymptote

### ISSUE THREAD

**Issue by AsyUser** [vectorgraphics/asymptote#276]
I am using Asymptote 2.70 (with gs 9.54.0). Opacity is working fine when using pdf as output format, but it is completely ignored when using asymptote inline in my latex code.

Here's a minimal latex code:

\documentclass{article}
\usepackage[inline]{asymptote}
\begin{document}
	\begin{asy}
		//settings.outformat="pdf";
		unitsize(1cm);
		fill(unitcircle, red+opacity(.5));
		fill(shift((.5,0))*unitcircle, blue+opacity(.5));
	\end{asy}
\end{document}

If I uncomment the command settings.outformat="pdf", then everything is fine, the generated pdf file (I am using pdflatex) has the correct transparency. But with this command commented, opacity settings are completely ignored.

In case this is relevant, I am using linux (opensuse tumbleweed).

**Comment by johncbowman** [comment]
There are two issues: first of all, don't use gs9.54; it is broken. Fortunately that bug was fixed in version 9.55.
Second, you will need to install the latest git version or else wait for the upcoming 2.71 release.

**Comment by AsyUser** [comment]
Thanks for the info!
