### ISSUE TITLE
Unchecked rpc/types.h dependency

### ISSUE THREAD

**Issue by hfiguiere** [vectorgraphics/asymptote#288]
Between 2.70 and now, asymptote started expecting `rpc/types.h` to be available (building on Linux). 

However:
- `configure` properly check for RPC and defines `HAVE_RPC_RPC_H` if available. 
- `HAVE_RPC_RPC_H` is used in various places to NOT include `xstream.h`
- v3d code added does not follow that rule and include `xstream.h` unconditionally

So asymptote build fail.

A few more notes:
- glibc removed the RPC includes a while ago, so some older distribution like Debian stable still have it. Fedora doesn't, it only has `/usr/include/rpc/netdb.h`. So that could explain why you don't see the error.
- Build fail because of that when using `freedesktop-sdk` that is base system for Flatpak.
- I could not even build on plain Fedora 35 because I fall into a Makefile infinite loop. I haven't figured out the bug (will file anther issue for that), so I'm having trouble coming up with a patch yet.

**Comment by johncbowman** [comment]
There is some confusion here.

To support v3d, you need to install libtirpc-devel; we haven't relied on glibc for its (broken) rpc headers for many years now...

Before the 2.71 release, v3dfile.h and v3dfile.cc were already guarded by
#ifdef HAVE_RPC_RPC_H

But I see now that this guard is missing from pair.h, triple.h, and oPRCFile.h.

Not having XDR support is far from ideal; it much better to simply install libtirpc-devel
before configuring.

By the way we don't currently check for
rpc/netdb.h
If you are also missing this standard file, a workaround is to configure with --disable-lsp.

**Comment by hfiguiere** [comment]
I'm was just saying ` rpc/netdb.h` is the only include in `rpc/*`.

**Comment by johncbowman** [comment]
Fixed in  827f4188c785a80199c9499122b04256667880bb.
