### ISSUE TITLE
the svg output is different from the pdf or png output

### ISSUE THREAD

**Issue by justonlyasy** [vectorgraphics/asymptote#292]
Consider this code which is compiled on http://asymptote.ualberta.ca/
```
settings.render=10;
import graph;
import palette;
import contour;

size(350,350);

pair a=(-6,-6);
pair b=(6,6);

real f(real x, real y) {return (x/5)^2+(y/3)^2;}
int N=200;
int Divs=16;

defaultpen(.9bp);
pen Tickpen=black;
pen[] Palette=quantize(BWRainbow(),Divs);

bounds range=image(f,a,b,3N,Palette,Divs);
real[] Cvals=uniform(range.min,range.max,Divs);
Cvals.pop();
draw(contour(f,a,b,Cvals,N),Tickpen+extendcap+beveljoin);

crop();
limits(a-(0.3,0.3),b+(0.3,0.3));

xaxis("$x$",BottomTop,LeftTicks(Size=4,size=2));
yaxis("$y$",LeftRight,RightTicks(Size=4,size=2));
```
the svg ouput is
![image](https://user-images.githubusercontent.com/52594258/148330108-24b49d6f-5228-400e-8513-2252ebcec3e7.png)
while the png output is
![image](https://user-images.githubusercontent.com/52594258/148330250-ba861712-dcaf-4151-af1e-0b92a49297b6.png)
and the pdf output is
![image](https://user-images.githubusercontent.com/52594258/148330327-ce7286a8-5ed9-490a-b79c-e5e1f922787a.png)

**Comment by johncbowman** [comment]
Your crop command is still in the wrong place. I will post one more update to your example in issue #263 that resolves this issue too.
