### ISSUE TITLE
Right-Handed Coordinate System

### ISSUE THREAD

**Issue by abrombo** [vectorgraphics/asymptote#297]
The default 3D coordinate system is left-handed.  Is there a way to specify a right-handed 3D coordinate system?

**Comment by johncbowman** [comment]
The default coordinate system is of course right-handed:

```
import graph3;

size(0,200);
size3(200,IgnoreAspect);

scale(Linear,Linear,Log);

xaxis3("$x$",0,1,red,OutTicks(2,2));
yaxis3("$y$",0,1,red,OutTicks(2,2));
zaxis3("$z$",1,30,red,OutTicks(beginlabel=false));
```
![axis3](https://user-images.githubusercontent.com/13231852/151067062-fb4a2f7f-666b-48dc-94b9-4735f435608a.png)
