### ISSUE TITLE
geometry.asy documentation cannot be reached

### ISSUE THREAD

**Issue by chennisden** [vectorgraphics/asymptote#301]
The page [https://asymptote.sourceforge.io/doc/geometry.html](https://asymptote.sourceforge.io/doc/geometry.html) points to [http://www.piprime.fr/files/asymptote/geometry/](http://www.piprime.fr/files/asymptote/geometry/). As far as I can see, that website does not exist.

**Comment by johncbowman** [comment]
Try prepending https://web.archive.org/web/20201130113133/
to those links; I've already updated https://asymptote.sourceforge.io/links.html
