### ISSUE TITLE
What is the purpose of LSP, please ?

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#303]
Building on linux, all I can discover is that it is a microsoft protocol for editors. I cannot see how people using vim or nano on linux to edit their files could use it, therefore I am reluctant to add the extra dependencies.

Maybe I'm missing something, particularly since it defaults to enabled in configure without testing for dependencies ?

**Comment by johncbowman** [comment]
See https://asymptote.sourceforge.io/doc/Language-server-protocol.html#index-LSP on how to use LSP under Linux.
In fact that is the only platform (other than Windows Subsystem for Linux) that Asymptote currently supports LSP on.

From https://en.wikipedia.org/wiki/Language_Server_Protocol:

> LSP was originally developed for Microsoft Visual Studio Code and is now an open standard. On 2016 June 27, Microsoft announced a collaboration with Red Hat and Codenvy to standardize the protocol's specification. The protocol is supported and has been adopted by the three companies.[2][3] Its specification is hosted and developed on GitHub.

**Comment by johncbowman** [comment]
I don't use vim or nano but if they provide support for LSP, equivalent instructions for these editors would be welcome contributions.
