### ISSUE TITLE
Improve error reporting by configure

### ISSUE THREAD

**Issue by gaponenko** [vectorgraphics/asymptote#307]
Hello,

In some cases errors reported by the congigure script are misleading.  For example here

https://sourceforge.net/p/asymptote/discussion/409349/thread/d7ef545b21/

configure complained about libm while the actual problem had nothing to do with it.
It would be nice to fix that.

Thank you,
Andrei

**Comment by johncbowman** [comment]
The real problem was a legacy compiler so this will be solved in time once everyone upgrades.
