### ISSUE TITLE
Log scaling not applied

### ISSUE THREAD

**Issue by srtaylor** [vectorgraphics/asymptote#31]
Log-Log scaling on currentpicture works for me as expected, but not on any other picture.  E.g. this minimal example works as expected:
`import graph;`
`scale(Log,Log);`
`size(200,IgnoreAspect);`
`real f (real x) {return x^2;}`
`draw(graph( f, 1, 16 ) );`
`xaxis("$x$",BottomTop,RightTicks);`
`yaxis("$y$",LeftRight,LeftTicks);`

but the following code (which should given identical output) does not: log scale isn't applied, and the axis ticks are wrong:
`import graph;`
`picture pic;`
`scale(pic,Log,Log);`
`size(pic,200,IgnoreAspect);`
`real f (real x) {return x^2;}`
`draw(pic, graph( f, 1, 16 ) );`
`xaxis(pic,"$x$",BottomTop,RightTicks);`
`yaxis(pic,"$y$",LeftRight,LeftTicks);`
`shipout(pic);`

I need to get this working so I can draw multiple graphs on one picture.  Have I done something subtly wrong here?

**Comment by oguibe** [comment]
Hello

Please replace 
`draw(pic, graph( f, 1, 16 ) );`
by
`draw(pic, graph( pic,f, 1, 16 ) );`

O.G.

**Comment by srtaylor** [comment]
Thank you!
