### ISSUE TITLE
Port Asymptote's rendering engine to Vulkan

### ISSUE THREAD

**Issue by jamievlin** [vectorgraphics/asymptote#311]
Right now, macOS users do not have access to per-pixel ordered transparency or other compute shader dependent functions. 

Moreover, OpenGL is being phased out by Apple which means OpenGL won't be getting more updates on Mac. 

What we can do is to port asy's render engine to Vulkan, then bridge that to metal using MoltenVK.

**Comment by johncbowman** [comment]
Yes, that is indeed our long-term plan. We also plan to port the WebGL code to WebGPU for the same reasons.
