### ISSUE TITLE
Compilation issue 

### ISSUE THREAD

**Issue by malcolmroberts** [vectorgraphics/asymptote#316]
Using c1ec3a89, g++ 9.4.0 on an up-to-date Ubuntu 20.04 LTS, I get the following compilation error after running 

`./autogen.sh  && ./configure --prefix=$HOME/asy -enable-fftw && make`
 
I get the following error:

```
PEN_SOURCE=600 -I/usr/include/readline     -std=c++14 -g -O2 -fno-var-tracking -ILspCpp/include -o gsl.o -c gsl.cc
settings.h:43:19: error: expected unqualified-id before string constant
   43 | extern const char VERSION[];
      |                   ^~~~~~~
```

I get the same error when using the tgz with 2.8.1.

**Comment by johncbowman** [comment]
Perhaps there is an issue in one of your header files. Do a `make clean` and then .`/configure --prefix=$HOME/asy --disable-gc`

**Comment by johncbowman** [comment]
I meant to write
`./configure --prefix=$HOME/asy --disable-gsl`

**Comment by malcolmroberts** [comment]
`./configure --prefix=$HOME/asy --disable-gsl && make clean && make` produced the same result.

**Comment by malcolmroberts** [comment]
I did a `git clean -fdx` and things seem to work now; this may be an issue with generated files not being removed by `make clean`.
