### ISSUE TITLE
Texlive 2016, asy environment, 3D => error

### ISSUE THREAD

**Issue by oguibe** [vectorgraphics/asymptote#32]
Hello 

A colleague has observed that the following simple example gives an error
during the asymptote compilation. 
%%%%%%%%%%%%%%%
\documentclass{article}
\usepackage{asymptote}
\begin{document}
\begin{asy}
import three ;
draw(unitcube);
label("$A$",(0,0,0),S) ;
\end{asy}
\end{document}
%%%%%%%%%%%%%%%

Without `label("$A$',(0,0,0),S)` everything is fine. But with `label` the command `asy name-1.asy` produces
%%%%%%%%%%%%%%
! I can't write on file `.aux'.
\document ...ate \openout \@mainaux \jobname .aux 
                                                  \immediate \write \@mainau...
l.15 \begin{document}
                     
(Press Enter to retry, or Control-D to exit; default file extension is `.tex')
Please type another output file name
! Emergency stop.
\document ...ate \openout \@mainaux \jobname .aux 
                                                  \immediate \write \@mainau...
l.15 \begin{document}
                     
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on .log.
/usr/local/share/asymptote/plain_Label.asy: 655.6: texpath failed
%%%%%%%%%%%%%%

It seems that the command `texpreamble("\input pdftex.def");` (defined in plain.asy) is the origin of the error. With `texpreamble("\input pdftex.def");` the couple asymptote/pdflatex is trying to compile the file `.tex` ?
If I comment  `texpreamble("\input pdftex.def");` everything is fine, but we can have another strange behavior.

I tested today under Linux 64 bits, Debian Sid, Texlive 2016 up to date and Asymptote SVN up to date.

Thanks for advance.
O.G.

**Comment by johncbowman** [comment]
Hi Olivier,

Thanks for reporting this. It is a leftover issue from the graphicx debacle and in fact hit me as well just this morning. Your example was helpful in tracking it down. Try the latest version of
https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/base/plain.asy

**Comment by oguibe** [comment]
Hi John

You're welcome. 
It seems that the Texlive2016 causes some trouble with
Asymptote.

I inform my colleague of the update to test its.

Regards
O.G.

**Comment by johncbowman** [comment]
Yes, the TeXLive 2016 problems arose from an unfortunate backwards-incompatible change to the graphicx package. Hopefully this is now fixed once and for all:

https://github.com/vectorgraphics/asymptote/issues/24
