### ISSUE TITLE
KDE syntax highlighting erratum

### ISSUE THREAD

**Issue by jamadagni** [vectorgraphics/asymptote#320]
Hello. [The docs page on editing modes](https://asymptote.sourceforge.io/doc/Editing-modes.html) says:

> Syntax highlighting support for the KDE editor Kate can be enabled by running asy-kate.sh in the /usr/local/share/asymptote directory and putting the generated asymptote.xml file in ~/.kde/share/apps/katepart/syntax/.

However, this is no longer true with KDE 5. As per [the KDE documentation](https://docs.kde.org/stable5/en/kate/katepart/highlight.html):

> Custom .xml highlight definition files are located in org.kde.syntax-highlighting/syntax/ in your user folder found with qtpaths --paths GenericDataLocation which usually are $HOME/.local/share/ and /usr/share/.

I confirm that the above new location works with latest Kate on Kubuntu 22.04.

Hence the document should be updated to refer to the current path.

While we are at it, it would be good if in the XML file, the `name="asymptote"` be capitalized to `name="Asymptote"`. Makes for nicer reading in the UI.

**Comment by johncbowman** [comment]
Could you please confirm that commit 694902944ba06f3c77dad9bc0bcc4e465fa7e1d4 satisfactorily addresses this issue?

**Comment by jamadagni** [comment]
Hello. Thanks for your attention. The full path is `$HOME/.local/share/org.kde.syntax-highlighting/syntax/` and not just till `share/`.

**Comment by jamadagni** [comment]
Thanks!
