### ISSUE TITLE
Why is call of operator==(point, null) ambiguous?

### ISSUE THREAD

**Issue by jamadagni** [vectorgraphics/asymptote#322]
import geometry;
    point a = null;
    if (a == null) write("yes"); else write("no");

I get:

> -: 1.7: call of function 'operator ==(point, null)' is ambiguous

A point is just another struct right? When the following code is valid:

    struct INT { int i; }
    INT q = null;
    if (q == null) write("yes"); else write("no");

and gives the (expected) output “yes”, I don't see why the same doesn't work for a point? Since the interpreter doesn't give clarity in the error message on what are the ambiguous candidates it is not easy for me to find what is wrong with `operator ==(point, null)`.

To detect an uninitialized input point in a function, I found that `alias(p, null)` is the only way currently. See [this post in the SF.net forum](https://sourceforge.net/p/asymptote/discussion/409349/thread/11224d2c/#e907/96e7).

It would be good if `operator ==(struct, null)` worked uniformly for all structs to detect uninitialized inputs, while one realizes that for non-struct types (which apparently includes `pair`s) this is not possible or only possible with more difficulty in the implementation.

**Comment by johncbowman** [comment]
In commit cb6aeda7ff3c1ed42bb04ed45ba26ce5061797f1 I've added a diagnostic to list ambiguous functions.

The error mesage for this case sheds light on the underlying issue, which has to do with the heavy use of casting
in the contributed module geometry.asy that you are using:

-: 1.33: call of function 'operator ==(point, null)' is ambiguous:

bool(mass a, mass b)
bool[](pair a, pair[] b)

Using alias(a,null) is a good solution.
