### ISSUE TITLE
geometry.asy documentation automatically updatable?

### ISSUE THREAD

**Issue by jamadagni** [vectorgraphics/asymptote#326]
I've been writing some additions for geometry.asy for my recent posts regarding it.

In this connection I notice the <asyxml> comments, but am not sure whether there exists a pipeline to continuously generate documentation from it. 

The existing documentation itself does not reflect the existing API and only links to an old Web Archive version.

I also note that some new (?) functions do not have <asyxml> tags.

I have myself been using the API based on visual scan of geometry.asy and not just the (old) documentation.

Hence I am wondering whether the asyxml tags are meaningful and there is any method to automatically generate the documentation from it. Failing which another method for documentation might need to be chosen and all API whether documented already or not should be documented in that method.

**Comment by johncbowman** [comment]
I think the tool you are looking for is here:
https://github.com/pivaldi/asymptote-geometry-documentation

**Comment by ivankokan** [comment]
A placeholder which we created few years ago: https://github.com/vectorgraphics/asymptote/wiki.
