### ISSUE TITLE
svg output passes invalid option --libgs to dvisvgm

### ISSUE THREAD

**Issue by zoggy** [vectorgraphics/asymptote#33]
Hello,

It seems that `asy` passes an invalid option `--libgs` to dvisvgm to produce SVG output:

````
$ asy -version
Asymptote version 2.37 [(C) 2004 Andy Hammerlindl, John C. Bowman, Tom Prince]
$ dvisvgm --version
dvisvgm 2.0.4
$  asy -f 'svg' -o '/tmp/t.svg' test.asy -v -v -v
[...]
dvisvgm -n --verbosity=3 --libgs=/usr/lib/libgs.so -o/tmp/t.svg --bbox=56.4094bp 53.8583bp 164.409bp 216.108bp /tmp/t_.dvi
unknown option --libgs
/usr/share/asymptote/plain_shipout.asy: 87.10: runtime: shipout failed
````

**Comment by johncbowman** [comment]
You simply need to compile dvisgm with PostScript support.
See [http://dvisvgm.bplaced.net/FAQ]

**Comment by zoggy** [comment]
Thanks. In fact, dvisvgm has PostScript support (`ps` appears in `dvisvgm -l`), but `asy` is not aware of this and passes `--libgs` to `dvisvgm`. There seems to be no way to tell asy not to pass this option.

**Comment by johncbowman** [comment]
You simply need to upgrade dvisvgm; Asymptote requires version 1.5.3 or later.

**Comment by zoggy** [comment]
I'm using dvisvgm 2.0.4 that I compiled myself, and a packaged asymptote 2.37.

**Comment by johncbowman** [comment]
From http://dvisvgm.bplaced.net/FAQ


dvisvgm -h doesn’t list option --libgs and dvisvgm -l doesn’t list entry ps
dvisvgm was built without PostScript support. There’s no way to activate it. Try to get a binary with PS support enabled.

**Comment by zoggy** [comment]
As I stated before `dvisvgm -l` **does** list a `ps` entry, but it has no `--libgs` option. So PS support is enabled, but so enabled that it does not require, and does not support, `--libgs` option.

**Comment by johncbowman** [comment]
Presumably you are in case 1 (see below). The bug here is really in dvisvgm; it should still accept libgs and either use it instead or simply ignore it. In any case you can override with asy --libgs=""
or putting in your config.asy configuration file (in the .asy subdirectory of your home directory): 

```
import settings
libgs=""
```

1.dvisvgm -h doesn’t list option --libgs but dvisvgm -l lists entry ps
libgs was linked during build time.
PostScript support is always enabled.

**Comment by zoggy** [comment]
Thanks for the `--libgs=""` trick, that should do it.

**Comment by zoggy** [comment]
Thanks for the `--libgs=""` trick, that should do it.
