### ISSUE TITLE
Random build failures in parallel build (-jN)

### ISSUE THREAD

**Issue by yurivict** [vectorgraphics/asymptote#331]
I noticed that the FreeBSD port fails spuriously when built with -j8.

There is some problem with dependencies.

**Comment by johncbowman** [comment]
Does it happen when you configure with --disable-lsp?

**Comment by yurivict** [comment]
It doesn't happen with ```--disable-lsp```.
I just updated the FreeBSD port and added this argument.

Thanks for your help!

**Comment by yurivict** [comment]
Sorry, this bug is about -jN.

No, -jN still breaks the build.

**Comment by yurivict** [comment]
To be precise: Boost issues are gone with ```--disable-lsp```, but the -jN issue is still there.

**Comment by johncbowman** [comment]
I can't reproduce this issue. If you can isolate the problem, a pull request would be welcome.

**Comment by johncbowman** [comment]
Can someone check if parallel builds now work properly with the latest git version?

**Comment by johncbowman** [comment]
The makefile dependency issues should be fixed in commit 430c7a661c060568720f6d65e611a2087ea1dde6
