### ISSUE TITLE
Inconsistent usage of <TAB> and  spaces

### ISSUE THREAD

**Issue by albert-github** [vectorgraphics/asymptote#336]
In the file `LspCpp/include/LibLsp/lsp/general/initialize.h` we see:
https://github.com/vectorgraphics/asymptote/blob/f7557e41a68a0580a19c90d775f0d8f2d92de026/LspCpp/include/LibLsp/lsp/general/initialize.h#L29-L30

there is no indication of a `tab-size` in the file but when using indentations by means of a `<tab>` this should be done consequently.
Best is **never** to use `<tab>`s, they are killing for understanding the code (when used inconsistently) and comment.

**Comment by johncbowman** [comment]
Next time please make a pull request directly in the source repo for the LspCpp code:
https://github.com/vectorgraphics/LspCpp
