### ISSUE TITLE
Incorrect start tag

### ISSUE THREAD

**Issue by albert-github** [vectorgraphics/asymptote#337]
The documentation line:
https://github.com/vectorgraphics/asymptote/blob/f7557e41a68a0580a19c90d775f0d8f2d92de026/LspCpp/include/LibLsp/lsp/IProgressMonitor.h#L80

contains an incorrect start tag `</code>` this should be `<code>`

**Comment by johncbowman** [comment]
Next time please make a pull request directly in the source repo for the LspCpp code:
https://github.com/vectorgraphics/LspCpp
