### ISSUE TITLE
asymptote, lualatex and otf fonts

### ISSUE THREAD

**Issue by cjorssen** [vectorgraphics/asymptote#34]
I don't know if it is a bug or a feature request but asyptote does not seem to be ready to handly otf fonts via lualatex ([as reported](http://tex.stackexchange.com/q/350116/8425)). Is it mandatory to produce a dvi file then converted by dvips? Should luatex be used in pdf output mode?

Thanks.

**Comment by johncbowman** [comment]
In svn I just made a tiny change so that in addition to xelatex, the lualatex and luatex engines now use
the pdf processor to generate 3D labels.

**Comment by cjorssen** [comment]
Great! Thanks. I'll test it ASAP.
