### ISSUE TITLE
Awkward syntax highlighting in vim

### ISSUE THREAD

**Issue by MamnoonSiam** [vectorgraphics/asymptote#342]
Not sure if the following vim syntax highlighting of inline asymptote codes is intended or not:
![image](https://user-images.githubusercontent.com/32074720/188012245-f11e8d22-8e83-4ee7-b901-a94fe838ad94.png)

Either way, it is quite unpleasant and distracting.

**Comment by johncbowman** [comment]
The vim syntax highlighting in `asy.vim` is for Asymptote code only. If you try
`vim latexusage.tex`
it shouldn't look anything like the above example. Maybe what you are showing is a result of some external TeX syntax highlighting script you are using?
The only syntax highlighting that we ship for inline Asymptote code is for Emacs:
https://asymptote.sourceforge.io/doc/Editing-modes.html#index-lasy-mode
