### ISSUE TITLE
Displaying labels including imported images seems to be problematic

### ISSUE THREAD

**Issue by Matin-Macktoobian** [vectorgraphics/asymptote#344]
Setup:

Windows 10
Asymptote 2.83
Ghostscript 10.0.0

---------------------------
After compiling 

```
import geometry;
import math;

size(7cm,0);

real theta=degrees(asin(0.5/sqrt(7)));

pair B=(0,sqrt(7));
pair A=B+2sqrt(3)*dir(270-theta);
pair C=A+sqrt(21);
pair O=0;

pair Ap=extension(A,O,B,C);
pair Bp=extension(B,O,C,A);
pair Cp=extension(C,O,A,B);

perpendicular(Ap,NE,Ap--O,blue);
perpendicular(Bp,NE,Bp--C,blue);
perpendicular(Cp,NE,Cp--O,blue);

draw(A--B--C--cycle);

draw("1",A--O,-0.25*I*dir(A--O));
draw(O--Ap);
draw("$\sqrt{7}$",B--O,LeftSide);
draw(O--Bp);
draw("4",C--O);
draw(O--Cp);

dot("$O$",O,dir(B--Bp,Cp--C),red);
dot("$A$",A,dir(C--A,B--A),red);
dot("$B$",B,NW,red);
dot("$C$",C,dir(A--C,B--C),red);
dot("$A'$",Ap,dir(A--Ap),red);
dot("$B'$",Bp,dir(B--Bp),red);
dot("$C'$",Cp,dir(C--Cp),red);

Label(graphic("piicon.png","width=2.5cm, bb=0 0 147 144"),Ap,5ENE);
```
by 

`asy.exe -f pdf <file_name>.asy`,

in which `piicon.png` may be found [here](https://github.com/vectorgraphics/asymptote/blob/master/examples/piicon.png), one expects the following output

![tttttt](https://user-images.githubusercontent.com/63607514/192949718-178f6379-5ddf-47d8-a90a-4c1edca3cb73.png)

But, the insertion of the last label (including the png file above), as the last line of the code intends, does not happen:

![qqqqqq](https://user-images.githubusercontent.com/63607514/192949981-270382bb-9a60-42cf-ab07-36bfcf398fdf.png)

**Comment by johncbowman** [comment]
You are missing the line:
`settings.tex="pdflatex";`

**Comment by Matin-Macktoobian** [comment]
Adding 

`settings.tex="pdflatex";`

to the code above, say,

```
import geometry;
import math;

settings.tex="pdflatex";

size(7cm,0);

real theta=degrees(asin(0.5/sqrt(7)));

pair B=(0,sqrt(7));
pair A=B+2sqrt(3)*dir(270-theta);
pair C=A+sqrt(21);
pair O=0;

pair Ap=extension(A,O,B,C);
pair Bp=extension(B,O,C,A);
pair Cp=extension(C,O,A,B);

perpendicular(Ap,NE,Ap--O,blue);
perpendicular(Bp,NE,Bp--C,blue);
perpendicular(Cp,NE,Cp--O,blue);

draw(A--B--C--cycle);

draw("1",A--O,-0.25*I*dir(A--O));
draw(O--Ap);
draw("$\sqrt{7}$",B--O,LeftSide);
draw(O--Bp);
draw("4",C--O);
draw(O--Cp);

dot("$O$",O,dir(B--Bp,Cp--C),red);
dot("$A$",A,dir(C--A,B--A),red);
dot("$B$",B,NW,red);
dot("$C$",C,dir(A--C,B--C),red);
dot("$A'$",Ap,dir(A--Ap),red);
dot("$B'$",Bp,dir(B--Bp),red);
dot("$C'$",Cp,dir(C--Cp),red);

Label(graphic("piicon.png","width=2.5cm, bb=0 0 147 144"),Ap,5ENE);
```
does not change anything, compared to the reported output. Please note that I don't use the (pdf)LaTeX-based workflow

```
(pdf)LaTeX <file_name>
asy.exe <file_name>-*
(pdf)LaTeX <file_name>
```

Instead, as stated in the post above, I just run 

`asy.exe -f pdf <file_name>.asy`

**Comment by johncbowman** [comment]
Yes, otherwise you would simply create the Label without actually applying it. The original example is posted here:
[orthocenter.asy](https://asymptote.sourceforge.io/gallery/orthocenter.asy)
