### ISSUE TITLE
Referring to Asymptote in Publications?

### ISSUE THREAD

**Issue by kevinmatthes** [vectorgraphics/asymptote#348]
I would like to name Asymptote as a reference in a paper.  Is there any preferred citation I can use therefore?

So far, I used to cite Asymptote using the following BibTeX entry which I derived from the official manual.  For the paper, I would like to make sure that the citation meta data I use are according to the preferences of the Asymptote project.

```
@manual{asymptote:2.69
, author = {{H}ammerlindl, {A}ndy and {B}owman, {J}ohn and {P}rince, {T}om}
, title = {{A}symptote}
, subtitle = {{T}he {V}ector {G}raphics {L}anguage}
, date = {2020}
, version = {2.69}
}
```

Is this BibTeX entry suitable for citing Asymptote or should I rather use some other / further meta data instead?

**Comment by johncbowman** [comment]
That looks fine (except that it would be better to cite the current stable version, 2.83). The braces around the capital letters shouldn't be there; leave the capitalization up to your bst file.
You could also add
url={https://asymptote.sourceforge.io/}
