### ISSUE TITLE
Vertex colors with transparency yield weird results in 3D

### ISSUE THREAD

**Issue by HeinrichApfelmus** [vectorgraphics/asymptote#35]
The following example illustrates that something is wrong with Asymptote's rendering of transparency in 3D:

![transparency-3d-bug](https://cloud.githubusercontent.com/assets/564592/22419358/6e078972-e6dd-11e6-8ed0-1874b5701dbd.png)

The example consists of two greenish spheres behind an orange plane, which is partially transparent (`orange+opacity(0.8)`). The left sphere was intended to be partially transparent as well, its vertices are shaded with a gradient that includes a tiny bit of transparency (`…+opacity(0.99)`). The right sphere is almost the same, except that it is fully opaque (`…+opacity(1)`). Clearly, the rendering of the sphere on the left is wrong, the green color should not be able to cut through the orange plane.

This example is for demonstration of the issue. My actual use case consists of solid where I have chosen the vertex colors to be partially transparent, so that one can look "behind" the solid as well. One example of this would be a partially transparent globe where one can partially see the continents on the side that does not face the camera.

The version of Asymptote that I am using is

    $ asy --version
    Asymptote version 2.23 [(C) 2004 Andy Hammerlindl, John C. Bowman, Tom Prince]

The complete `.asy` file for generating the picture:

    settings.outformat = "png";
    settings.render = 16;

    import three;
    import palette;
    import graph3;
    size(5cm,0);

    currentprojection = perspective((-0.8,1,1.5));

    void setcolor(surface s, pen p) {
      s.colors( palette(s.map(xpart), Gradient(p,p) ) );
    }

    draw( box((-2,-2,-1),(2,2,1)), black );

    surface s;
    s = shift(-1Z) * surface( box((-2,-2), (2,2)) );
    setcolor(s, blue);
    draw(s);

    s = shift(1Z) * surface( box((-2,-2), (2,2)) );
    setcolor(s, orange+opacity(0.8));
    draw(s);

    // sphere
    surface mkSphere(pen[] cs) {
      triple f(pair z)   { return expi(z.x,z.y); }
      real   g(triple v) {
        real z = zpart(v);
        return (z*z*z);
      }
      surface s = surface(f,(0,0),(pi,2pi),41,Spline);
      s.colors( palette(s.map(g), cs ) );
      return s;
    }

    surface s = shift(0.5X+0.5Y) * mkSphere( Gradient(green+opacity(0.99), 0.9*white, green) );
    draw(s);

    surface s = shift(-0.5X-0.5Y) *  mkSphere( Gradient(green+opacity(1), 0.9*white, green) );
    draw(s);

**Comment by johncbowman** [comment]
You need to update to Asymtpote 2.39. We don't support old versions.

**Comment by HeinrichApfelmus** [comment]
Sorry for reporting this problem with an old version of Asymptote.

Unfortunately, the issue persists in newer versions.

I have compiled Asymptote 2.40git from source, and the example now results in a segmentation fault:

    $ cd asymptote-2.40git/
    $ wget http://hboehm.info/gc/gc_source/gc-7.4.2.tar.gz
    $ wget http://www.ivmaisoft.com/_bin/atomic_ops/libatomic_ops-7.4.2.tar.gz
    $ ./autogen.sh
    $ ./configure
    [..]
    $ make --version
    GNU Make 3.81
    [..]
    $ make all
    [..]
    $ ./asy -dir ./base -config "" -noprc ../transparency-3d-bug.asy
    Segmentation fault: 11


Other examples seem to work normally. In particular, the manual `doc/asymptote.pdf` is built correctly without problems.

TeXLive-2016 is bundled with Asymptote version 2.38, which produces the following picture, which is not correct either:

![transparency-3d-bug](https://cloud.githubusercontent.com/assets/564592/22621185/c702ab80-eb1d-11e6-8a12-b384e4493194.png)

**Comment by johncbowman** [comment]
Yes, that is how the example should look with OpenGL (which as is well known, doesn't handle transparency perfectly). The segmentation fault you are reporting is likely coming from your graphics library. Which version of freeglut are you using? I recommend freeglut-3.0.0.

Your code runs fine on my machine with asy 2.40-1, even under valgrind.

**Comment by HeinrichApfelmus** [comment]
> Yes, that is how the example should look with OpenGL (which as is well known, doesn't handle transparency perfectly)

... Oh. That was news to me.

I just have looked around on the internet a bit, and it seems to me that while using OpenGL transparency naïvely will fail, there are still methods to ensure that scenes are rendered correctly, for example [depth peeling][1].

Wouldn't it be sensible to implement this in Asymptote? As far as I understand, Asymptote is a scene description language, and I was under the impression that rendering should be independent of particular technology artefacts like OpenGl not sorting triangles before blending colors. At least, that's how I would like it as a mathematician. 😄 

  [1]: http://www.opengl-tutorial.org/intermediate-tutorials/tutorial-10-transparency/

> Which version of freeglut are you using? I recommend freeglut-3.0.0.

Actually, I'm on OS X 10.6. It seems that the `configure` script simply picks up the resident `OpenGL` system library (framework).

**Comment by johncbowman** [comment]
Yes, if you are only drawing triangles, you can split them along any intersections (that tutorial didn't even consider this possibility) and then sort the pieces. However, we are rendering smooth Bezier surfaces and before version 2.39, Asymptote delegated all rendering to the GLU library. That library is deprecated so, in preparation for the ultimate demise of the GLU library, as of version 2.39, Asymptote uses it's own in-house renderer for Bezier triangles, curves, and surfaces. So yes, it should now be possible to implement splitting and sorting at the triangle level. I'll reopen this issue as a reminder.

Can you recompile with
```
make clean
make CFLAGS=-g
```
and use the debugger (or valgrind) to produce a traceback that shows were the segmentation fault occurred? Do any other 3D examples that use OpenGL (i.e. not ones from the manual) fail?
There are many 3D examples in the Asymptote gallery and some of them use transparency.

**Comment by HeinrichApfelmus** [comment]
> So yes, it should now be possible to implement splitting and sorting at the triangle level

Great! 😄 

> Can you recompile with
>        make clean
>        make CFLAGS=-g

Yes… and now it produces a good `.png` file without segfault! 😮  However, if I run

    make clean
    make

again, the obtained `asy` executable will segfault again when trying to render my example. ><

(Note: I am actually on OS X 10.9, sorry for the confusion.)

**Comment by johncbowman** [comment]
What happens when you compile with
`make CFLAGS="-g -O2"`

If that doesn't work, also try -O.

**Comment by johncbowman** [comment]
A partial workaround for this OpenGL bug is now implemented in
commit 31c6630d550fab51331756a4d78bc6f199b226ea

I didn't implement triangle splitting yet but transparent triangles for a single material are now sorted by their centroid depth.

I also fixed a seg fault in beziercurve.h so perhaps that issue is now resolved too.
![test](https://cloud.githubusercontent.com/assets/13231852/22866496/c64dbdca-f134-11e6-9459-36186675c439.png)

**Comment by johncbowman** [comment]
P.S. To avoid degenerate patches at the poles you should slightly adjust the theta endpoints. For example:
`surface s = surface(f,(sqrtEpsilon,0),(pi-10*sqrtEpsilon,2pi),41,Spline);`

![test](https://cloud.githubusercontent.com/assets/13231852/22872344/c98bbbae-f175-11e6-868f-fac7c6269b2d.png)

**Comment by HeinrichApfelmus** [comment]
Much better, thanks! 😄 

The segmentation fault no longer happens for me with commit af2b9b1592e3849c5e5c986fd92c745076eedb22 .

The picture is much better as well! The treatment of transparency does not yet seem to be perfect, though. If I apply your suggested fix concerning degeneracy, and now also reduce the transparency of the left sphere as a whole, changing the following two lines,

    // ...
    surface s = surface(f,(sqrtEpsilon,0),(pi-10*sqrtEpsilon,2pi),41,Spline);
    // ...
    surface s = shift(0.5X+0.5Y) * mkSphere( Gradient(green, 0.9*white, green)+opacity(0.1) );

, then I get the following picture:

![transparency-3d-bug](https://cloud.githubusercontent.com/assets/564592/22976828/a264683c-f38c-11e6-8101-149e91ec280a.png)

The left sphere is almost invisible, except for a green piece with a weird shape. The lower boundary of this piece is shaped like a straight, horizontal line, which indicates that this rendering is probably not correct.

**Comment by johncbowman** [comment]
This issue is fixed in commit  c7878da529adde75a929a755dae7a42b2e9a3486.

**Comment by johncbowman** [comment]
The problem with this modified example is that triangle splitting of transparent triangles with overlapping depths has not yet been implemented.

**Comment by johncbowman** [comment]
Fixed (for non-legacy OpenGL environments, meaning everywhere except MacOS X and WebGL)
in master branch and upcoming 2.71 release.

**Comment by asmwarrior** [comment]
Great work!
I'm hoping the 2.71 will release soon.

**Comment by asmwarrior** [comment]
I add some forum links, I guess/hope that the next release will fix the bugs reported in the forum, see:

[Asymptote / Discussion / Help: Artifacts in 3D rendering of transparent surfaces](https://sourceforge.net/p/asymptote/discussion/409349/thread/6d2d289d/?limit=25#d3c6/b6bb)

and

[Asymptote / Discussion / Help: Status on OpenGL transparency bug](https://sourceforge.net/p/asymptote/discussion/409349/thread/d5d3aaeffb/?limit=25#bcd9)
