### ISSUE TITLE
Unpacking iterable

### ISSUE THREAD

**Issue by AvidSeeker** [vectorgraphics/asymptote#350]
I usually need to unpack a list of points of arrays of points. Like this:

```asy
pair A,B,C;
A = tABC[0]; B = tABC[1]; C = tABC[2];
```

In python, one can have

```python
A,B,C = triangle_arr
```

to unpack values of the list to A,B,C. Would be great to have a feature similar to this.

**Comment by johncbowman** [comment]
Being a C-like language, Asymptote doesn't support unpacking list elements to named variables.
