### ISSUE TITLE
Consistency of coordinate systems of returned `point`s of inversion-related functions in `geometry.asy`

### ISSUE THREAD

**Issue by yarusome** [vectorgraphics/asymptote#355]
I am working on a new PR to fix all the bugs in the inversion section of `geometry.sty`, but one issue holds me back for now.

Since the returned values of many functions in this section are `point`s or `inversion`s, which has `point`s as members, and each `point` may in a different coordinate system, it seems necessary to decide what convention to follow when fixing the bugs to achieve consistency of the returned `point`s. Here are a few proposals:

  1. All the returned `point`s must be in `currentcoordsys`.
  2. All the returned `point`s must be in `defaultcoordsys`.
  3. Decide case by case which coordinate system the returned `point` must be in for each function, and when there is no obviously rational choice, choose `currentcoordsys` (or `defaultcoordsys`).

This might also affect consistency with other sections of `geometry.asy`, and the documentation needs fixes to reflect this. (Incidentally, the TeX source file of the doc is nowhere to be found now since `https://www.piprime.fr` seems to have shut down.)

**Comment by johncbowman** [comment]
Fortunately I found a local copy of the documentation that I have now uploaded here:

https://github.com/vectorgraphics/asymptote-geometry-documentation

**Comment by johncbowman** [comment]
You may need to apply these two pull requests:  https://github.com/pivaldi/asymptote-geometry-documentation/pulls
I can add you as a developer on the above fork of this repo on request.

**Comment by yarusome** [comment]
Then I'd go with the first proposal for now. After the patches have been merged, the doc fixes will be in a different PR.
