### ISSUE TITLE
Problems with SVG export after upgrading to ghostscript 10

### ISSUE THREAD

**Issue by gdietl** [vectorgraphics/asymptote#357]
I have problems of generating SVG output since ghostscript has upgraded to version 10. When downgrading gs to version 9.56.1 everything works as intended. However, with the new version, I get the error
```
ERROR: Ghostscript is required to process EPS files
    shipout3(prefix,f,preview ? nativeformat() : format,
            ^
/usr/local/share/asymptote/three.asy: 2896.13: runtime: shipout failed
```

**Comment by johncbowman** [comment]
I tried ghostscript-10.0.0-linux-x86_64 and it fortunately it works fine.
You probably have an installation issue. The ERROR message has nothing to do with Asymptote; 
it is coming from dvisvgm (use the -vv asy option to see how dvisvgm is being called).
First focus on getting your new ghostsript installation to work with dvisvgm.
