### ISSUE TITLE
Unified and complete documention of the module `setting`

### ISSUE THREAD

**Issue by yarusome** [vectorgraphics/asymptote#359]
In the current documention, Chapter 9 lists various command-line options, followed by a few paragraphs mentioning some configuration variables in the module `settings`. However:

  1. There're a lot of other configuration variables scattered among other chapters.
  2. The documented configuration variables are not complete, e.g. `pngdriver` mentioned in #358.

Moreover, since the module `settings` is internal, it's rather difficult, if not impossible, to find a suitbale configuration variable quickly.

So I propose to list *all* the configuration variables in a single section in the documentation while maintaining the current appearances of configuration variables in other chapters. I could also make a PR if I could know where all the variables appear in the source codes.

**Comment by johncbowman** [comment]
Actually I already addressed this an hour ago (use the -e option):

commit 37f564040bec2ff6059f5c4872950be17586b885 (HEAD -> master, origin/master, origin/HEAD, stencil)
Author: John Bowman <bowman@ualberta.ca>
Date:   Tue Jan 3 20:37:17 2023 -0700

    Add option to show summary of environment settings.
