### ISSUE TITLE
Question about python scripts(?)

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#366]
The Debian lintian tool reports

`W: asymptote-x11: executable-not-elf-or-script [usr/share/asymptote/GUI/icons_rc.py]`
`W: asymptote-x11: executable-not-elf-or-script [usr/share/asymptote/GUI/ContextWindow.py]`

, which means "there is a file with x bit set, but it is neither an ELF binary, nor recognized as script". Indeed in both files the Shebang line is missing. After adding the line the warning vanishes. Unfortunately I'm not a programmer and I don't know if that approach is the right one (and if these files are scripts) or if rather the x bit should be removed.

Please let me know, how to get rid of the warning. Many thanks!

**Comment by johncbowman** [comment]
The simplest solution is to add the shebang
#!/usr/bin/env python3
at the beginning of ContextWindow.py
for consistency with the other files (even though unlike xasy.py it won't get executed from the command line). And you can remove the x bit from autogenerated file icons_rc.py.
