### ISSUE TITLE
window10    xasy  GUI  install fail

### ISSUE THREAD

**Issue by a405457747** [vectorgraphics/asymptote#368]
hello,please help me 

So hard to install : 
i am  run  "python xasy.py"
ModuleNotFoundError: No module named 'pyUIClass'

**Comment by johncbowman** [comment]
This indicates an installation problem on your MSWindows 10 system. Please uninstall any existing versions of Asymptote and install Asymptote 2.85 from https://sourceforge.net/projects/asymptote/files/
Then follow these instructions:
https://asymptote.sourceforge.io/doc/GUI-installation.html
