### ISSUE TITLE
Build failure when HAVE_GL is not defined

### ISSUE THREAD

**Issue by vbgl** [vectorgraphics/asymptote#37]
When trying to build asymptote version 2.39, on mac OS X, without OpenGL support, the following error is produced:

```
clang++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -DUSEGC  -D_THREAD_SAFE -pthread -DFFTWPP_SINGLE_THREAD  -g -O2 -g -O3 -ansi   -I. -I/nix/store/6mgacccigzqvb3q0rq6r667arxq0xpng-asymptote-2.39/include/gc -I/usr/include/gc -o beziertriangle.o -c beziertriangle.cc
In file included from beziertriangle.cc:8:
./drawsurface.h:36:3: error: unknown type name 'BezierCurve'
  BezierCurve R;
  ^
./drawsurface.h:142:3: error: unknown type name 'BezierCurve'
  BezierCurve R;
  ^
2 errors generated.
```

On the same build environment, version 2.38 builds fine (and works!).

I think the problem is related to commit 1d32440f4abd08287e4b9672c98e41139540607c, by @johncbowman.

**Comment by johncbowman** [comment]
Sorry I meant to check this before the release. It is fixed now. But for 3D support you really should compile with OpenGL support.
