### ISSUE TITLE
Asy.exe creates .pdf-file with incompatible content when using hatch package

### ISSUE THREAD

**Issue by JoAlSchmidt** [vectorgraphics/asymptote#370]
.asy-file (pattern_test.asy):
```
import patterns;
add("hatch",hatch(1mm));
fill(scale(20)*unitsquare, pattern("hatch"));
```
shell command:
`$ asy -k -f pdf pattern_test.asy`

testing the produced .pdf-file for compatitlity e.g. using [https://www.check4print.com/](https://www.check4print.com/) yields the result:
`Your file contains transfer functions which is not allowed in PDF/X standard`

**Comment by johncbowman** [comment]
You can disable transfer functions by specifying the command line option  
-gsOptions="-dTransferFunctionInfo=/Apply".
We will make this the default in the next release.
