### ISSUE TITLE
[Bug] file names with dots are truncated

### ISSUE THREAD

**Issue by avidseeker** [vectorgraphics/asymptote#373]
```
asy ch1.5-angles.asy
```
Outputs:
```
ch1.eps
```

**Comment by johncbowman** [comment]
The pattern following the dot is assumed to be the file extension. Just replace the first dot in your file name with a hyphen (-).

**Comment by avidseeker** [comment]
Shouldn't it be "the pattern following *the last* dot" instead of the first? following [Bash and Python ](https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash) behavior in detecting filenames.

**Comment by johncbowman** [comment]
Yes, in fact Asymptote was suppose to work that way too but the extensions were getting stripped multiple times.
