### ISSUE TITLE
input(string filename) fails

### ISSUE THREAD

**Issue by dafadey** [vectorgraphics/asymptote#382]
input() fails for missing file making error(file) completely useless

testing code:
Welcome to Asymptote version 2.86 (to view the manual, type help)
> write(error(input("trololo", check="true")));
-: 1.6: runtime: Cannot open file "trololo"

**Comment by johncbowman** [comment]
First of all, check is a boolean not a string, so you need to remove the quotes enclosing true.

If you want to mask the above error you need to set check=false:

Then you can say

 `write(error(input("trololo",check=false)));`

**Comment by dafadey** [comment]
Thanks a lot! Please add this to documentation. I just got it my self by tweaking with asy source. It is really counter-intuitive!
btw, I saw -O1 in config files do you guys build with just O1?

**Comment by johncbowman** [comment]
To quote from the documentation:

`If the optional boolean argument check is false, no check will be made that the file exists.`

If you look in configure.ac, you will see that the default optimization is -O3.
