### ISSUE TITLE
wrong color in SVG output

### ISSUE THREAD

**Issue by hbghlyj** [vectorgraphics/asymptote#388]
In Asymptote [gallery](https://asymptote.sourceforge.io/gallery/) the example [venn3.svg](https://asymptote.sourceforge.io/gallery/venn3.svg) compared with [venn.svg](https://asymptote.sourceforge.io/gallery/venn.svg) on the left:
The intersection of big red circle `A` and big green circle `B` should be yellow, but it is white:
![image](https://github.com/vectorgraphics/asymptote/assets/53823634/d952eb6a-0afe-4d60-a19a-a2ab8450fdf5)
I compiled the code [venn3.asy](https://asymptote.sourceforge.io/gallery/venn3.asy) and exported HTML is fine, but exported SVG has wrong color: the yellow region appears white

**Comment by hbghlyj** [comment]
In the exported SVG, I find the yellow region is hidden by the white region:
![image](https://github.com/vectorgraphics/asymptote/assets/53823634/3e485173-b7bd-472d-8eb0-bc0e1e319b26)
I moved the white region, then I see the yellow region under it.

**Comment by johncbowman** [comment]
Thanks; fixed in commit aa9f81bad9478bfe8b2ab5fc5376c19c6c79c708: Avoid broken dvisvgm reassign-clippaths optimization.
