### ISSUE TITLE
-prc command-line option not working

### ISSUE THREAD

**Issue by marszw** [vectorgraphics/asymptote#39]
Contrary to what the documentation on p. 164 says, Asymptote executable ignores any value for the command-line option `-prc`. Here is a transcript:
```
C:\Program Files (x86)\Asymptote\asy.exe" -f pdf -prc false -render 0 pr.asy 
error: could not load module 'false'
```
And the same for the value `true`:
```
C:\Program Files (x86)\Asymptote\asy.exe" -f pdf -prc true -render 0 pr.asy 
error: could not load module 'true'

```
I am running Asymptote 2.41 on Windows 10.

Thank you.

**Comment by johncbowman** [comment]
The correct options are -prc and -noprc.
