### ISSUE TITLE
Error initializing offscreen context: Depth=0 when render != 0

### ISSUE THREAD

**Issue by hshackle** [vectorgraphics/asymptote#392]
I'm running into problems with Aymptote if I try to run it with `settings.render` set to anything other than 0. I am running Asymptote 2.86-2 on Arch Linux, downloaded from the Arch repository. I took the following minimal example from the Asymptote tutorial:
```
settings.outformat="png";
settings.render = 16;
import three;
size(1cm,0);
draw((0, 0, 0) -- (1, 1, 1), linewidth(2pt)); 
```
and running `asy -vv test.asy` gives the following output:

```
Using configuration directory /home/hshackle/.asy
Using history /home/hshackle/.asy/history
Welcome to Asymptote version 2.86git
cd /home/hshackle
Processing test
Loading plain from /usr/share/asymptote/plain.asy
Including plain_constants from /usr/share/asymptote/plain_constants.asy
Loading version from /usr/share/asymptote/version.asy
Including plain_strings from /usr/share/asymptote/plain_strings.asy
Including plain_pens from /usr/share/asymptote/plain_pens.asy
Including plain_paths from /usr/share/asymptote/plain_paths.asy
Including plain_filldraw from /usr/share/asymptote/plain_filldraw.asy
Including plain_margins from /usr/share/asymptote/plain_margins.asy
Including plain_picture from /usr/share/asymptote/plain_picture.asy
Loading plain_scaling from /usr/share/asymptote/plain_scaling.asy
Loading simplex from /usr/share/asymptote/simplex.asy
Loading plain_bounds from /usr/share/asymptote/plain_bounds.asy
Including plain_scaling from /usr/share/asymptote/plain_scaling.asy
Including plain_prethree from /usr/share/asymptote/plain_prethree.asy
Including plain_Label from /usr/share/asymptote/plain_Label.asy
Including plain_arcs from /usr/share/asymptote/plain_arcs.asy
Including plain_boxes from /usr/share/asymptote/plain_boxes.asy
Including plain_shipout from /usr/share/asymptote/plain_shipout.asy
Including plain_markers from /usr/share/asymptote/plain_markers.asy
Including plain_arrows from /usr/share/asymptote/plain_arrows.asy
Including plain_debugger from /usr/share/asymptote/plain_debugger.asy
Loading test.asy from test.asy
Loading three from /usr/share/asymptote/three.asy
Loading math from /usr/share/asymptote/math.asy
Loading embed from /usr/share/asymptote/embed.asy
Including three_light from /usr/share/asymptote/three_light.asy
Including three_surface from /usr/share/asymptote/three_surface.asy
Loading bezulate from /usr/share/asymptote/bezulate.asy
Loading interpolate from /usr/share/asymptote/interpolate.asy
Loading graph_splinetype from /usr/share/asymptote/graph_splinetype.asy
Including three_margins from /usr/share/asymptote/three_margins.asy
Including three_tube from /usr/share/asymptote/three_tube.asy
Including three_arrows from /usr/share/asymptote/three_arrows.asy
adjusting camera to (4.98354040694537,4.00353062344247,2.04114065779814)
adjusting target to (0.483540406945365,0.50353062344247,0.541140657798142)
Allocating osmesa_buffer of size 1024x768x4x1
Offscreen context settings: Depth=0 Stencil=0 Accum=0
Error initializing offscreen context: Depth=0
```
There is no issue if I use `settings.render = 0`, but this leads to a very low-quality image.

**Comment by johncbowman** [comment]
Check asy --version. You need to install the missing OpenGL libraries and reconfigure.

**Comment by user202729** [comment]
Looks like same issue as #361 .

For me, it works if the version is

```
$ asy --version
Asymptote version 2.87-25 [(C) 2004 Andy Hammerlindl, John C. Bowman, Tom Prince]

ENABLED OPTIONS:
V3D      3D vector graphics output
WebGL    3D HTML rendering
OpenGL   3D OpenGL rendering
```

On Arch Linux, for some reason the `asymptote` package uses offscreen rendering by default. As a workaround, `asymptote-git` can be used.

**Comment by johncbowman** [comment]
If `asy --version` shows  

`OpenGL   3D OSMesa offscreen rendering`

it must have been configured with --enable-offscreen, which is only intended for headless servers with no GPU card (like  http://asymptote.ualberta.ca/).

**Comment by user202729** [comment]
Yes, but the no-offscreen rendering has a quirk that a window pops up every time I compile asymptote.

Which library would I need to install to get off-screen rendering to work? (I assume OSMesa? but I already have it installed:

```
$  ls /usr/lib/libOSMesa* -1
/usr/lib/libOSMesa.so
/usr/lib/libOSMesa.so.8
/usr/lib/libOSMesa.so.8.0.0
```

as mentioned above I was just using the standard `asymptote` package on Arch Linux)

**Comment by user202729** [comment]
With some debugging work, I have reduced the problem to:

```cpp
#include <iostream>
#include <cstdlib>
#include <GL/osmesa.h>

using namespace std;

int screenWidth = 800;
int screenHeight = 600;
unsigned char* osmesa_buffer;
OSMesaContext ctx;

int main() {
	cout << "Allocating osmesa_buffer of size " << screenWidth << "x"
			 << screenHeight << "x4x" << sizeof(GLubyte) << endl;
	osmesa_buffer = new unsigned char[screenWidth * screenHeight * 4 * sizeof(GLubyte)];
	if (!osmesa_buffer) {
		cerr << "Cannot allocate image buffer." << endl;
		exit(-1);
	}

	const int attribs[] = {
		OSMESA_FORMAT, OSMESA_RGBA,
		OSMESA_DEPTH_BITS, 16,
		OSMESA_STENCIL_BITS, 0,
		OSMESA_ACCUM_BITS, 0,
		OSMESA_PROFILE, OSMESA_CORE_PROFILE,
		//OSMESA_PROFILE, OSMESA_COMPAT_PROFILE,
		OSMESA_CONTEXT_MAJOR_VERSION, 4,
		OSMESA_CONTEXT_MINOR_VERSION, 3,
		0, 0
	};

	ctx = OSMesaCreateContextAttribs(attribs, NULL);
	//ctx = OSMesaCreateContextExt(OSMESA_RGBA, 16, 0, 0, NULL);
	if (!ctx) exit(-1);

	if (!OSMesaMakeCurrent(ctx, osmesa_buffer, GL_UNSIGNED_BYTE, screenWidth, screenHeight)) {
		cerr << "OSMesaMakeCurrent failed." << endl;
		exit(-1);
	}

	int z = 0, s = 0, a = 0;
	glGetIntegerv(GL_DEPTH_BITS, &z);
	glGetIntegerv(GL_STENCIL_BITS, &s);
	glGetIntegerv(GL_ACCUM_RED_BITS, &a);
	  cout << "Offscreen context settings: Depth=" << z << " Stencil=" << s
			   << " Accum=" << a << endl;

	if (z <= 0) {
		cerr << "Error initializing offscreen context: Depth=" << z << endl;
		exit(-1);
	}

	OSMesaDestroyContext(ctx);
	delete[] osmesa_buffer;

	return 0;
}
```

Running the code above will output
```
Allocating osmesa_buffer of size 800x600x4x1
Offscreen context settings: Depth=0 Stencil=0 Accum=0
Error initializing offscreen context: Depth=0
```

on my machine.

I observe that:

* If the line `		OSMESA_PROFILE, OSMESA_CORE_PROFILE,` is commented and the line `		//OSMESA_PROFILE, OSMESA_COMPAT_PROFILE,` is uncommented, then it will works well.

* If `OSMesaCreateContextExt` is used instead, then it will also work well.

Any idea what is going on? I'm not very familiar with OpenGL, so I'm not sure what's the difference between the core and compatibility profile (but note that the default profile is the compatibility profile)

In any case, whether or not you can reproduce the issue, I think we can just try to create the context the first way, then if depth = 0 then delete the context and recreate it the second way. There should be no harm?

(side note: problem is currently the official Arch Linux build of the package uses
 offscreen rendering. I think there is no disadvantage to using offscreen rendering?)

**Comment by johncbowman** [comment]
There shouldn't be any problem using OSMESA_COMPAT_PROFILE so I have made that change.
But offscreen mode is only meant for a headless server lacking a GPU card or monitor. It isn't meant for normal interactive use:

In offscreen mode you will not have **any** interactive capability to adjust the camera position or zoom in on the scene (using the -V option). That means that you will only see 2D projections of your scene rather than true 3D vector graphics output. So if you want 3D vector graphics you **must** configure with --disable-offscreen. If Arch Linux is accidentally distributing a headless version of Asymptote that is a mistake that should be reported.

Incidentally, the brief OpenGL window that you see with --disable-offscreen (the default configuration option) is a normal feature of OpenGL. Either ignore it or specify the -iconify option on the command line to hide the rendering window used to project 3D graphics to 2D when the -noV option is specified (the default under UNIX).

Fortunately, all of these concerns will disappear when we migrate from OpenGL to Vulkan (hopefully in the 2.88 release). There won't be any phantom windows opening and, if absolutely needed, you will be able to control offscreen mode from the command line.

**Comment by user202729** [comment]
(The actual reason I complain about the brief window is https://github.com/vectorgraphics/asymptote/issues/423 . Normal user won't find it a trouble because the `glutHideWindow();` is already there.)

**Comment by vEnhance** [comment]
> Good point. I guess this can be raised to the Arch Linux package maintainer...

The account registration on the Arch bug tracker is currently disabled, so I've gone and filed the issue for you:

https://gitlab.archlinux.org/archlinux/packaging/packages/asymptote/-/issues/1
