### ISSUE TITLE
Automatic shipout still executing, even after manual call

### ISSUE THREAD

**Issue by thornoar** [vectorgraphics/asymptote#396]
The documentation reads,
```
A shipout() command is added implicitly at file exit if no previous shipout commands have been executed.
```
However, it seems as if the `shipout()` command was added __always__. Here is a minimal working example file `test.asy`:
```
draw(unitcircle);
shipout(prefix = "picture", format = "pdf");
```
After compilation, __two__ files are added in the directory, `picture.pdf` and `test.eps`, while it should be only `picture.pdf`. What is even more interesting, if I remove the `prefix` keyword from `shipout` and specify only the format, then only `test.eps` results after compilation, without any `pdf` file.

OS: Manjaro Linux
Asymptote: 2.86git

Thank you for any help in advance.

**Comment by johncbowman** [comment]
Yes, this changed in commit 451a260ae50d02867c1e54726a68d8af2c55761d but the documentation was not updated.

**Comment by johncbowman** [comment]
If you shipout to the defaultprefix, the implicit shipout will override the specified format. Use 
`settings.outformat="pdf";`
instead.

**Comment by thornoar** [comment]
The problem still stands, however, when shipouting to a non-defaultprefix. Is there maybe a constant for enabling/disabling automatic shipout? A nice thing would also be to have something like `settings.outprefix`

**Comment by johncbowman** [comment]
What problem still stands? If you shipout to a non-default prefix, you will get two output files, as now documented (unless you erase currentpicture at the end of the file; see for example Koch1.asy).

**Comment by thornoar** [comment]
I suppose you are saying that Asymptote now works exactly as it is supposed to, to which I fully agree. My comment was more that it shouldn't really be supposed to work like that (imho), and I was only asking if there was a way not to produce this extra file each time after manual shipout. Since there seems to be none (apart from `exit()`ing thereafter), this should be considered closed indeed. Thank you in any case, your reply was helpful!

**Comment by johncbowman** [comment]
To suppress the implicit shipout, add `erase();` at the end of your file.
