### ISSUE TITLE
Consult pkg-config to find gsl, fftw, and tirpc.

### ISSUE THREAD

**Issue by mojca** [vectorgraphics/asymptote#40]
The libraries `ffwt` and `gsl` come with `lib/pkgconfig/fftw3.pc` and `lib/pkgconfig/gsl.pc`.
It would be nice if `configure.ac` would try to consult `pkg-config` to find them.

**Comment by johncbowman** [comment]
Good idea. I've never used pkgconfig. Can you give me an example of what information we could use?
For example, it might be nice if the gsl/gsl_sf.h header file could be automatically located but it isn't obvious to me how to do this. I tried

 `pkg-config --cflags gsl`

but nothing was returned.

**Comment by mojca** [comment]
I get
```sh
> pkg-config --cflags gsl
-I/opt/local/include
```

See https://autotools.io/pkgconfig/pkg_check_modules.html for `PKG_CHECK_MODULES`.

**Comment by johncbowman** [comment]
The man page for pkgconf explains why nothing was returned on my system for gsl:

 ```
pkg-config --cflags --keep-system-cflags gsl
-I/usr/include 

```
Now that I finallly understand pkg-config I should be able to implement the necessary changes in the near future.

**Comment by gaponenko** [comment]
There is also the gsl-config script,  which seems to be more robust than pkg-config:  on my system with GSL installed from source pkg-config does not find the library, while

$ gsl-config --cflags
-I/data/src/gsl/my/include
