### ISSUE TITLE
Add class names to drawing commands for svg shipout

### ISSUE THREAD

**Issue by ProgramComputer** [vectorgraphics/asymptote#402]
Currently, SVG is drawn based on the order of drawing commands on asymptote. Adding classes in ASY before shipout will ease future SVG animation uses in ECMAScript. Maybe legend from draw could be used but it's preferable to be able to add multiple classes such as "id27 group2".

Below is an example ASY and sample use case HTML of SVG after I put in classes and IDs manually
https://gist.github.com/ProgramComputer/f8062118e55462b88bfdb2e776cdf0df

**Comment by johncbowman** [comment]
Here's an example of how to added a class counter to circle objects. Hopefully you don't really need these labels added to "<use" since those are generated by dvisvgm. Feel free to extend this to other required objects and submit a pull request.

**Comment by ProgramComputer** [comment]
@johncbowman 
> Here's an example of how to added a class counter to circle objects. Hopefully you don't really need these labels added to "<use" since those are generated by dvisvgm. Feel free to extend this to other required objects and submit a pull request.

Is the example a hyperlink? I don't see it in your comment.

**Comment by johncbowman** [comment]
Sorry, here is the example:
`
[svgclass.txt](https://github.com/vectorgraphics/asymptote/files/13272657/svgclass.txt)
`
