### ISSUE TITLE
suggestion about config.asy documentation

### ISSUE THREAD

**Issue by ifmihai** [vectorgraphics/asymptote#41]
I'm a newbie, just installed asymptote.
I wanted to correctly link psview to asymptote.
I presumed config.asy must be there somewhere on the hdd.
I did a full search, nothing found.
After more searching on the web, i realized the file must be created by me.

This bit of info should be in the docs,
ideally both near psview installation information,
and in configuration file section.

It would save time and frustration.

**Comment by johncbowman** [comment]
The documentation already states:

Typically the configuration file _is placed_ in the .asy directory in the user's home directory...

Configuration variables are most easily set as Asymptote variables in an _optional_ configuration file config.asy

I'm not sure how to make this any more clear but if you have any suggestions, I will consider them.
