### ISSUE TITLE
inradius() does not working as expected

### ISSUE THREAD

**Issue by ElegantSimplicity** [vectorgraphics/asymptote#415]
From geometry.asy, for calculating inradius of a triangle, I found that inradius() does not working as expected.

```
// http://asymptote.ualberta.ca/
import geometry;
unitsize(1cm);

pair A = (0,0), B=(5,0), C = (1,3.5);

pair J = incenter(A,B,C);  // correct
pair r = inradius(A,B,C);  // incorrect 
real rr = abs(J-reflect(A,B)*J)/2;  // correct but not convernient

draw(circle(J,rr),red);
draw(circle(J,r),blue);

draw(A--B--C--cycle);

label("$A$", A, SW);
label("$B$", B, SE);
label("$C$", C, N);
dot("$J$", J, red);

```

**Comment by justonlyasy** [comment]
The function inradius() is a **real** type, not **pair**. Take a look at the geometry.asy file, line [5439](https://github.com/vectorgraphics/asymptote/blob/master/base/geometry.asy#L5439),
`abs(IC - projection(A, B) * IC) ` is similar to `abs(J-reflect(A,B)*J)/2`.

**Comment by ElegantSimplicity** [comment]
@justonlyasy oh, I have spent time with my naive mistake. Thank you!
