### ISSUE TITLE
freeglut error

### ISSUE THREAD

**Issue by tauzero7** [vectorgraphics/asymptote#42]
asymptote-2.41 issue:

Trying to run a very simple test file with a "settings.render" larger than 0 and command line option "-offscreen" yields "freeglut  ERROR:  Function <glutDisplayFunc> called without first calling 'glutInit'."
```
settings.outformat = "png";
settings.render=8;
settings.prc = false;
size(5cm,0);
import three;
currentprojection=orthographic(5,4,2);
draw(unitcube,magenta);
```
Inserting `init()` after `init_osmesa()` in line 1443 of glrender.cc solved the problem. But I'm not sure if this has any other side effects.

**Comment by johncbowman** [comment]
Thanks for reporting this and the suggested fix. It is now fixed in commit 51ababdae0bb1b3b94e87bd4a005af6f4d417b59
