### ISSUE TITLE
Why does inlineimage delete the main file's aux file?

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#420]
https://github.com/vectorgraphics/asymptote/blob/dd4b63cc1f7cf0c9bdb716db9963b4a0de8e7d27/picture.cc#L385-L390

As far as I can see, deleting the AUX file is inefficient (LaTeX would need to rerun), so we would like to avoid that as much as possible.

So,

* Why are we even deleting the AUX file in the first place?
* In the case of `inlineimage`, why delete it? As far as I can see it still means the image is compiled separately instead of `inlinetex`; and especially if the output figure is not 3D then we don't need to do anything anyway?

------

Update: the `inlineimage` one was first added in
2841f55449b6127d64dd69deea8b046ccc0741a9 and the `inlinetex` one was first added in 9f0071ef25bc9ee8650f0a9cb947e8b32930f366 .

Update: Okay, the point is that the preexisting AUX file may **interfere** with the standalone Asymptote compilation. Good point. I'll think what can be done about this. (In the case where asydir or asylatexdir is not the current directory then I think there's a simpler solution)

**Comment by user202729** [comment]
Actually the point is that the jobname is customized to be the same of the main file...? But looks like the feature is somewhat broken anyway.

Try compiling the following file:

```
\documentclass{article}
\usepackage{asymptote}
\begin{document}
123
\begin{asy}
	label("[\jobname]");
\end{asy}

\end{document}
```

Expected behavior: the `[` and the `]` is visible.

Actual behavior: they're truncated.

**Comment by johncbowman** [comment]
Indeed, the commit message

_In inlinetex mode, avoid interference from pre-existing aux file._ 

answers your question. We don't want to clutter up the working directory with other file prefixes.

Instead of accessing the volatile symbol \jobname, the user should do this to obtain the desired result:
```
\begin{asy}
	label("["+defaultfilename+"]");
\end{asy}

```

**Comment by user202729** [comment]
> Instead of accessing the volatile symbol \jobname, the user should do this to obtain the desired result:

I see. In that case my concern (that jobname must be changed in order to make the values in the measure phase be the same as the actual run) was not a problem

> We don't want to clutter up the working directory with other file prefixes.

This is actually not a problem. Starting from `a.tex` contains

```tex
%! TEX program = pdflatex
\documentclass{article}
\usepackage{asymptote}
\begin{document}
123
\begin{asy}
	label("45");
\end{asy}

\end{document}
```

and type `latexmk`, the following files are generated, **regardless whether the proposed changes are done**:

```bash
$ ls
a-1.asy  a-1.pdf  a.aux  a.fdb_latexmk  a.fls  a.log  a.pdf  a.pre  a.tex
```

In other words, the clean-up appears to be done correctly. So it's not a problem.

Still, it feels like a good idea to randomize the jobname -- just in case there are multiple parallel runs of `asy` in the same directory.

I think implementing the proposed changes would be a good idea.
