### ISSUE TITLE
Suggestion: Give the temporary rendering window a distinctive name

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#423]
I suggest implementing the following:

```diff
--- a/glrender.cc
+++ b/glrender.cc
@@ -2146,7 +2146,7 @@ void glrender(const string& prefix, const picture *pic, const string& format,
     glutInitWindowSize(maxTileWidth,maxTileHeight);
     glutInitDisplayMode(displaymode);
     fpu_trap(false); // Work around FE_INVALID
-    window=glutCreateWindow("");
+    window=glutCreateWindow("Asymptote rendering window");
     fpu_trap(settings::trap());
     glutHideWindow();
   }
```

Reason: I use a *tiling window manager* (xmonad) where window hiding does not really work, so there is a flash on the screen. So I use something like this (irrelevant to the discussion, but basically it ignores the windows with title `Asymptote rendering window`)

```Haskell
myManageHook = composeAll 
   [ title =? "Asymptote rendering window" --> doIgnore
   ]
main = do
   a <- xmobar (def {
        manageHook  = myManageHook <+> manageHook def
      })
   xmonad a
```

For people such that the "hide window" is executed correctly, this should not have any adverse effect, I believe.

**Comment by johncbowman** [comment]
Well, it does have an adverse effect if iconify is true as it makes the icon much larger and more obtrusive. So let's settle on this:

window=glutCreateWindow(Iconify ? "" : "Asymptote rendering window" );

This issue will disappear anyway in the upcoming Vulkan port.

**Comment by user202729** [comment]
That's an interesting perspective (that I didn't think about). Fair point.

That having said, in Windows 10 I think only the icon is displayed when the window is minimized anyway (in the default setting?)
