### ISSUE TITLE
Add documentation for deferred drawing?

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#425]
I'm not sure why but it appears that there's practically no documentation for deferred drawing. While it's mentioned in e.g. https://asymptote.sourceforge.io/doc/Frames-and-pictures.html#add-about or https://asymptote.sourceforge.io/gallery/advection.asy .

There probably need not be too much to say, perhaps just `picture.add(void(frame, transform))` or something like that?

**Comment by charlesstaats** [comment]
This technique is also used in https://asymptote.sourceforge.io/FAQ/section8.html#unitsizes, as well as in my tutorial (section 2.25, "Drawing objects shifted by an unscalable amount"). I agree it would be nice to have it explicitly documented.

**Comment by johncbowman** [comment]
Deferred drawing was documented in this article:
John C. Bowman and Andy Hammerlindl, TUGBOAT: The Communications of the TeX Users Group, 29:2, 288-294 (2008)

http://www.math.ualberta.ca/~bowman/publications/asyTUG.pdf

and is now also documented in the manual:
https://asymptote.sourceforge.io/doc/Deferred-drawing.html
