### ISSUE TITLE
Question about programming language

### ISSUE THREAD

**Issue by abrombo** [vectorgraphics/asymptote#427]
Would you say that the Asymptote programming language is very similar to the Julia programming language?

**Comment by charlesstaats** [comment]
Thank you for your interest. I personally have never used Julia (although I've heard good things about it), so I have no idea.

Note that this is a place to open issues (i.e., bugs and feature requests). I'm not sure if there is currently an appropriate place for fun discussions like this, but creating a thread in the [Help forum](https://sourceforge.net/p/asymptote/discussion/409349/) should at least be more appropriate than opening an issue here. Alternatively, feel free to create a feature request for a forum dedicated to discussing asymptote with no particular request for help. (As always, feature requests may or may not be granted, but it seems like an idea that is, at the very least, not obviously bad. Whether it's good may depend on how many people want to participate in such a discussion.)

**Comment by charlesstaats** [comment]
Closing because this is not actually an issue (although we do, as always, appreciate the commenter's interest).
