### ISSUE TITLE
Postscript error creating svg with libgs.so.10.02

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#434]
For a MWE take the sphere.asy example file and use it to create an svg file.

In my case I add a line at the start:

 settings.outformat="svg";

This used to work, and stopped at some point in the last 6 months. I initially assumed I had been doing something unsupported which had happened to work, and I did not have time to investigate. But the change after 2.87 mentioned on tlbuild caused me to look again.

When it fails, the output, for example using the binary TL pretest, is

PostScript error: undefined in finddeviceOperand stack:
    5  --nostringval--  --nostringval--  --nostringval--  imgdev  jpeg
    shipout3(prefix,f,preview ? nativeformat() : format,
            ^
/home/ken/tlpre/texmf-dist/asymptote/three.asy: 2901.13: runtime: shipout failed

Working through asy-2.85, 2.86 and 2.87 with dvisvgm-3.2 they all work on an x86_64 linux system from last August or September, but not on more recent systems.

The difference seems to be that my recent systems are using libgs.so.10.02
and the working system used libgs.so.10.01.

The changes in ghostscript-10.02.1 include:

·  The old, PostScript based PDF interpreter has been removed, it is no longer available.

·  We've continued to improve the performance of the PDF interpreter written in C and improve it's behaviour in edge and out-of-specification cases.

I'm guessing that the first of those items is what has broken asy. The error occurs during the rendering, and leaves (filename)_.pdf e.g. sphere_.pdf

**Comment by johncbowman** [comment]
This works fine for me:

```
gs
GPL Ghostscript 10.02.1 (2023-11-01)
Copyright (C) 2023 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
GS>quit
[wizard: ~/camp master] asy sphere -f svg

```
However, I am using `dvisvgm 2.13.3`.

**Comment by johncbowman** [comment]
P.S. I just upgraded to TeXLive 2023, which uses dvisvgm 3.0.3 and can reproduce the issue. So it seems like this is really a dvisvgm issue, not an Asymptote issue.

**Comment by johncbowman** [comment]
Before reporting this issue to dvisvgm, I updated to version 3.2.1 of dvisvgm and the problem has already been fixed.
So you either need to update your dvisvgm or downgrade your ghostscript library.
