### ISSUE TITLE
svg breakage with gs-10.03.0

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#435]
After your and Martin's hard work, gs-10.03.0 was released, with a vulnerability fix for the OCR component. At that point I did not yet have asy-2.88, so I installed gs-10.03.0, ran general tests with dvisvgm and ImageMagick, and then used asy-2.87 to run that infernal sphere test.

An error message:
GPL Ghostscript 10.03.0: Can't use an XRef stream before PDF 1.5, ignoring WriteXRefStm directive

The good news was that an svg was created. The bad news is that it was incomplete. gzipped file follows.

[sphere-10030-287.svg.gz](https://github.com/vectorgraphics/asymptote/files/14543560/sphere-10030-287.svg.gz)

The 2.88 release was now available, so I tried that. No error message, but the resulting svg looks as if it started with a similarly missing corner, and then had black lines over the top a bit like a postmark.

[sphere-10030-288.svg.gz](https://github.com/vectorgraphics/asymptote/files/14543566/sphere-10030-288.svg.gz)

I have not yet attempted any other tests with 2.88 except for using 3D in a latex PDF which was ok.

After your comments earlier this week, I'll start here rather than at dvisvgm. If you want to take a break before looking at this I understand, it seems to be a continual pain.

**Comment by johncbowman** [comment]
That problem indicates a problem with your graphics driver; nothing to do with svg or pdf. For example, try
asy -f eps sphere
and view the resulting postscript file. 
For the solution, see 
https://asymptote.sourceforge.io/doc/three.html#index-black-stripes 
or 
https://github.com/vectorgraphics/asymptote/issues/56
