### ISSUE TITLE
Can’t compile LSP – <boost/filesystem/directory.hpp> missing from LspCpp/src/lsp/utils.cpp

### ISSUE THREAD

**Issue by d125q** [vectorgraphics/asymptote#438]
It seems that <boost/filesystem/directory.hpp> is missing from LspCpp/src/lsp/utils.cpp, causing compilation to fail with `no type named 'recursive_directory_iterator' in namespace 'boost::filesystem'`.  Adding
```cpp
#include <boost/filesystem/directory.hpp>
```
to LspCpp/src/lsp/utils.cpp fixes the issue. I am using a development build of Boost: `boost-1.85.0.beta1-14-g99eb5b9aa7`.

**Comment by johncbowman** [comment]
Thanks; applied to https://github.com/vectorgraphics/LspCpp and pulled into the Asymptote sources.

**Comment by johncbowman** [comment]
A better solution is to include the canonical `boost/filesystem.hpp` header instead.
