### ISSUE TITLE
bugs with file name 'Fig1.asy'; Can not output eps file for this file name

### ISSUE THREAD

**Issue by phyliuXL** [vectorgraphics/asymptote#44]
For other file names, Fig.asy,Pic.asy,Fig2.asy,Pic1.asy, e.t.c, After compiling **asy *.asy**, it will give *.eps. For Fig1.asy, it fails.

**Comment by johncbowman** [comment]
asy Fig1.asy -v
Processing Fig1
Wrote Fig1.eps
