### ISSUE TITLE
Feature request: `var oldAsin=asin;` copies the function

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#445]
Currently the behavior is

```
var g=asin;
    ^
a.asy: 1.5: could not infer type of initializer
```

If I understood correctly, the error will be raised when there are multiple overloads of the function in question (`asin` here).
But in this case I think the reasonable option is to copy all options.

**Comment by johncbowman** [comment]
You can't copy all versions of asin to g. Here's an example of how to pick a particular one:
```
typedef real realfcn(real);
var g=(realfcn) asin;
```

**Comment by charlesstaats** [comment]
If I understand correctly, the feature request was that the line

`var g = asin;`

should create multiple variables named `g`, each with a different signature. We already do something like this with `unravel` and `access`; for instance, the line

`from math access intersect as g;`

will result in two different variables named `g` (with different signatures). So the proposed feature should definitely be possible to implement if we were sufficiently motivated.
