### ISSUE TITLE
Bug: unitsize() does not work to set unitsize of other pictures

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#446]
```
unitsize(1cm);
draw(scale(3)*unitcircle); // radius 3cm. for reference

picture p;
unitsize(p, 5cm); // try unsuccessfully to set unitsize of picture p
picture backup=currentpicture;
currentpicture=p;
unitsize(p, 5cm);
unitsize(5cm);

draw(unitcircle);
currentpicture=backup;
add(p);
```

Expected behavior: the last `draw(unitcircle)` draws one with radius 5cm in the final image.

Actual behavior: that circle is drawn with radius 1.

**Comment by user202729** [comment]
In retrospect this looks like the same issue as https://github.com/vectorgraphics/asymptote/issues/450 .

**Comment by johncbowman** [comment]
No, that was a separate issue; see my explanation above.
