### ISSUE TITLE
Documentation of cputime is in Structure section?

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#448]
In the commit 3c46482e8cdd28a52d9c27d620b8c1f605b40b93 , the documentation of `cputime` was moved to Structures section, which looks rather out of place.

I just want to ask if it's intentional.

**Comment by johncbowman** [comment]
It provides an example of a function that returns a structure, so it wasn't totally out of place. But it can also go at the end of the section on Mathematical functions (which isn't a perfect fit either).
