### ISSUE TITLE
Suggestion: `envelope` type don't need `above` passed in

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#454]
Instead, it can just always assume `above=true`.

If the caller wants `above=false`, it can create a new frame and prepend it to the resulting frame itself.

Currently it needlessly duplicate the following code across the 3 types of boxes

```cpp
  frame F;
  if(above == false) {
    filltype.fill(F,g,p);
    prepend(dest,F);
  } else filltype.fill(dest,g,p);
```

Thought?

**Comment by johncbowman** [comment]
A better idea that avoids breaking existing code is in commit c7f016286dffc4cd1805d7541d50e17d05805527.
