### ISSUE TITLE
Why does the bounding box of a frame containing just a label not just the label's bounding box?

### ISSUE THREAD

**Issue by user202729** [vectorgraphics/asymptote#455]
```
frame f;
label(f, "\rule{60pt}{200pt}");
//draw(f,(0,1cm)--(1cm,0));
add(f);
write(max(f)-min(f));
add(new void(frame h, transform t){
  dot(h, min(f), blue);
  dot(h, max(f), blue);
});
```

```
(62.7668742216687,202.243835616438)
```

Surely it should be `(60, 200)`? Running `asy -vvv` shows TeX give Asymptote the correct values.

Note that if you change `200` to `2000` then the second value is `1995` and the black box goes outside the boundary.

I'm suspecting something wrong with
```
const double tex2ps=72.0/72.27;
const double ps2tex=1.0/tex2ps;
```
although changing it to `1` makes it even more wrong.

Looks like there's a padding of 3 TeX point inserted in somewhere...

**Comment by johncbowman** [comment]
There's nothing wrong with those unit conversions: 72.27 TeX points=72.0 Adobe points (bp)=1inch.
You are probably enountering the "Magic dvips offsets" in picture.cc, which were empirically tuned to support dvips.
I once asked the author of dvips Tomas  Rokicki if he knew why they are needed but he didn't know either.
The solution is to use -tex pdflatex.

**Comment by user202729** [comment]
The problem is the same with `pdflatex`. Updated example:

```
settings.tex="pdflatex";
frame f;
dotfactor=2;
label(f, "\rule{60bp}{200bp}");
add(f);
write((max(f)-min(f)));
add(new void(frame h, transform t){
  dot(h, min(f), blue);
  dot(h, max(f), blue);
});
```

Running `asy a.asy` gives

```
[tmp]$ asy a.asy
(62.9910236612702,202.99103362391)
```

where does the extra `2.991` come from? This leads to the dots not being exactly on the corner of the box.

![Image](https://github.com/user-attachments/assets/835fd7d5-5b27-4003-b30a-58060ff300b3)

**Comment by johncbowman** [comment]
The extra space is coming from the default pen width.

When drawing on a picture without a size specification, you are effectively drawing on a frame; it doesn't make sense to try to use deferred drawing here.

Try

```
settings.tex="pdflatex";
frame f;
dotfactor=2;
label(f,"\rule{60bp}{200bp}",fontsize(0.00001pt));
add(f);
write(size(f));
dot(min(f),blue);
dot(max(f),blue);
```
