### ISSUE TITLE
scale command breaks graph output

### ISSUE THREAD

**Issue by badkey** [vectorgraphics/asymptote#459]
Hi, 
trying to plot a log-linear graph to a picture I ran into this problem:
```
import graph;

// some function
real f(real t) {return 1/t;}

picture s;
size(s, 200,200,IgnoreAspect);
//scale(s, Log, Linear);
draw(s, graph(f,1,10000), blue);
xaxis(s, "$x$",BottomTop,LeftTicks);
yaxis(s, "$y$",LeftRight,RightTicks);
add(s.fit());
```
does nicely work unless one uncomments the scale command. The same does work when working without a picture (e.g. using currentpicture). Any hint is appreciated.
Jan-Mark

**Comment by johncbowman** [comment]
Since realMax is 1.79769313486232e+308, the upper x limit needs to be less than 309. Probably you meant 5, not 10000.

**Comment by badkey** [comment]
Thanks a lot - I have overseen this one.  And also Scale() needs the s as I noticed...
