### ISSUE TITLE
Most recent commit breaks my build

### ISSUE THREAD

**Issue by charlesstaats** [vectorgraphics/asymptote#460]
The most recent commit ('Ship with pkg.m4 to support pkg-config.') breaks my build (on MacOS Monterey, version 12.7.5). I have attached the output of the `make` command. Note that this command was run after running `make` on the previous commit (which was successful) and then checking out the more recent commit, so it should be running only what is necessary based on the changes from the most recent commit.

Let me know what else you need me to run to help with debugging.
[output.log](https://github.com/vectorgraphics/asymptote/files/15490168/output.log)

**Comment by johncbowman** [comment]
Your linker is looking for the fftw library, which you likely don't have. Try doing a make clean and running configure again
since this commit fixed a configuration issue regarding pkg-config (which some systems use to find files like tirpc, gsl, fftw, etc.)

**Comment by johncbowman** [comment]
I verified that the master branch builds correctly under MacOS Monterey 12.6.6.

**Comment by charlesstaats** [comment]
After running `make cleanest`, I ran

`./autogen.sh && ./configure CC=clang CXX=clang++ CPPFLAGS=-I/opt/local/include LDFLAGS=-L/opt/local/lib && make &> output2.log`

It did not appear to help. I have attached the result.

Note that the attached log contains only the output from the final `make` command, not autogen or configure.
[output2.log](https://github.com/vectorgraphics/asymptote/files/15491286/output2.log)

**Comment by johncbowman** [comment]
The cause of the problem turned out to be a missing fftw3.pc file. Commit 122092fa8a238ac101e9b7dcd6316be919e069ea attempts to work around such installation issues by choosing a reasonable default (in this case linking against -lfftw3).

**Comment by charlesstaats** [comment]
I can confirm that with the new commit, I can once again build Asymptote.
