### ISSUE TITLE
Fails to build on armel

### ISSUE THREAD

**Issue by hpreusse** [vectorgraphics/asymptote#473]
I have some issues to build the asy package on architecture armel on a Debian box. The issue happens on an official Debian sbuild builder and can be reproduced inside a chroot. The full build log is visible [here](https://buildd.debian.org/status/fetch.php?pkg=asymptote&arch=armel&ver=2.92%2Bds-1&stamp=1728737795&raw=0). I made four attempts, but the build fails always with the same error message:

```
cd .. && ../asy -dir ../base -config "" -render=0 -f png -o png/ shadedtiling.asy
This is pdfTeX, Version 3.141592653-2.6-1.40.26 (TeX Live 2025/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
LaTeX2e <2024-06-01> patch level 2
L3 programming layer <2024-08-16>

(/usr/share/texlive/texmf-dist/tex/latex/tools/.tex File ignored)
! I can't find file `shadedtiling_.tex'.
<*> ...\input \nonstopmode\input shadedtiling_.tex
```
So the call of asy itself, does not generate the intermediate TeX file or it is deleted to early. I've created an "strace -f" of the asy call, it is [attached](https://github.com/user-attachments/files/17351686/shadedtiling.zip). Sorry, I currently don't have more input.
I had the same issue on [mips64el](https://buildd.debian.org/status/logs.php?pkg=asymptote&arch=mips64el), but after repeating the build, the issue was gone. So I expect some kind of timing issue. I set the "ulimit -c" to unlimited, but no core dump was created, so asy does not crash. Let me know if anything else is needed. Many thanks!

**Comment by johncbowman** [comment]
It might be a parallelization issue. Does
`make all -j1`
work?

**Comment by hpreusse** [comment]
> It might be a parallelization issue. Does `make all -j1` work?
> 
Did not try, but I can call the command as described alone and it fails. So it is not issue caused by the building process.

**Comment by johncbowman** [comment]
What exactly do you mean by "command as described alone" and "it fails"?
In the top level source directory, does
`./asy -dir base doc/shadedtiling`
produce an error and if so please post the error message.

**Comment by johncbowman** [comment]
P.S. If that succeeds, the next test to try is:
`./asy -dir base doc/shadedtiling -fpng -vv`

**Comment by hpreusse** [comment]
> P.S. If that succeeds, the next test to try is: `./asy -dir base doc/shadedtiling -fpng -vv`

Attached.
[debug_1.txt](https://github.com/user-attachments/files/17354847/debug_1.txt)

**Comment by johncbowman** [comment]
The option `-vv` simply enables more diagnostics. 

What version of ghostscript are you using?

Please copy and paste exactly this command in the top level source directory:
`./asy -dir base doc/shadedtiling -fpng -vv -k`
and post the output along with the generated file shadedtiling_0.pdf

I notice that you are using an untested version of TeXLive (2025). Have you tried the current 2024 release of pdflatex?

**Comment by hpreusse** [comment]
> The option `-vv` simply enables more diagnostics.
> 
Yes, I would expect that.

> What version of ghostscript are you using?
> 
10.04.0~dfsg-1 (this is the Debian version). Not sure, how many patches are in there.

> Please copy and paste exactly this command in the top level source directory: `./asy -dir base doc/shadedtiling -fpng -vv -k` and post the output along with the generated file shadedtiling_0.pdf
> 
Done that on x86 & armel. Both files are here [shadedtiling_0_armel.pdf](https://github.com/user-attachments/files/17357139/shadedtiling_0_armel.pdf) [shadedtiling_0_x86.pdf](https://github.com/user-attachments/files/17357140/shadedtiling_0_x86.pdf). The x86 file can be processed using pdftotext, the file from armel seems to be broken somehow:

```
hille@rasppi2:~/devel/misc/asymptote-2.92+ds_armel $ pdftotext -layout -nopgbrk shadedtiling_0.pdf
Syntax Error: ExtGState 'R7' is unknown
Syntax Error: ExtGState 'R16' is unknown
Syntax Warning: Bad color space 'R9'
Syntax Error (510): Bad color space (fill)
```
Displaying the file in a pdf viewer also does not give the expected result.

> I notice that you are using an untested version of TeXLive (2025). Have you tried the current 2024 release of pdflatex?
> 
This is the texlive-bin tar ball, which is used in TL 2024 (AFAICT). I have to say I don't have an official TL installation here, just the Debian packages I've built. I've replaced on armel the generated pdf file shadedtiling_0.pdf by the one fron x86 and the pdflatex run for shadedtiling_.tex is successful.

This sehds some light on the issue. Many thanks for your help for now! Please be so kind to keep the ticket open, set it on "wait-for-user", I'll call back. Hilmar

**Comment by hpreusse** [comment]
I'm closing the issue after forwarding the issue to the gs maintainers in Debian. Many thanks for your help!
