### ISSUE TITLE
main.cc:255:3: error: use of undeclared identifier 'rl_cleanup_after_signal'

### ISSUE THREAD

**Issue by ccworld1000** [vectorgraphics/asymptote#474]
When compiling and executing make, an error occurs

main.cc:255:3: error: use of undeclared identifier 'rl_cleanup_after_signal'

src version : 2.93git
os version: macos 13 
cpu : intel

<img width="960" alt="Screenshot 2024-10-14 at 11 03 35" src="https://github.com/user-attachments/assets/65ed409a-7ce9-4faf-ad33-72547f157be2">

**Comment by johncbowman** [comment]
Probably you are using an obsolete version of readline. Make sure you install GNU readline not the old BSD version.
For example see https://ports.macports.org/port/readline/
If for some reason you don't wish to use GNU readline, you can 
`./configure --disable-readline`
 but then you won't have any command line editing or history in asy.
One can also use editline; it will be detected and used automatically if readline is absent.
