### ISSUE TITLE
LaTeX Error: File `hypdoc.sty' not found.

### ISSUE THREAD

**Issue by ccworld1000** [vectorgraphics/asymptote#475]
I downloaded the latest Readline code, recompiled it, and encountered new issues while executing make all

LaTeX Error: File `hypdoc.sty' not found.

<img width="1429" alt="Screenshot 2024-10-14 at 15 28 49" src="https://github.com/user-attachments/assets/bde4ab59-7fa3-4d2f-94d5-5f03f6d7056c">

It seems that there are no compilation scripts for macOS in build scripts

**Comment by johncbowman** [comment]
macOS uses the normal GNU/UNIX build system (the instructions are in the file INSTALL).

You TinyTeX installation isn't complete. You can download hypdoc from https://ctan.org/pkg/hypdoc
Or install the official TeXLive distribution from https://www.tug.org/texlive/

**Comment by johncbowman** [comment]
If you are missing critical dependencies, you may find it easier to install Asymptote via MacPorts:
https://ports.macports.org/port/asymptote/
