### ISSUE TITLE
Question 1: Can the same repeated variables be passed without built-in detection?

### ISSUE THREAD

**Issue by ccworld1000** [vectorgraphics/asymptote#478]
Question 1: Can the same repeated variables be passed without built-in detection?
fg:

real x = 6;
real x = 6;
real x = 6;
real x = 6;
real x = 6;
real x = 6;

Question 2: How to transfer the fixed width and height in tex to the size in asy?
fg:
By obtaining the tex height and width, some calculations may be performed to re pass the new values to the size function in asy.

**Comment by johncbowman** [comment]
Repeated declarations are considered an innocuous error (Asymptote is a tolerant language).

The second (unrelated) question should be posted separately. Don't forget to include a minimal example that clarifies the context of what you are trying to do.
