### ISSUE TITLE
Duplicate declaration

### ISSUE THREAD

**Issue by stefanhusmann** [vectorgraphics/asymptote#48]
Under Arch Linux I get a conflicting declaration

/usr/include/unistd.h:463:12: Fehler: in Konflikt stehende Deklaration für C-Funktion »int usleep(__useconds_t)«
 extern int usleep (__useconds_t __useconds);
            ^~~~~~
glrender.cc:9:16: Anmerkung: vorherige Deklaration von »int usleep(int)«
 extern "C" int usleep(int);

**Comment by johncbowman** [comment]
I don't see that line in glrender.cc. You must be looking at a modified version of the official source code.

**Comment by stefanhusmann** [comment]
No, I pull from here (master). I also deleted the complete clone and cloned again. The line is there.

**Comment by johncbowman** [comment]
Sorry my mistake (I was in another branch). That declaration shouldn't have been committed and is now fixed. Thanks for reporting this.
