### ISSUE TITLE
reading array of length 435545 with out-of-bounds index -435546

### ISSUE THREAD

**Issue by ccworld1000** [vectorgraphics/asymptote#487]
reading array of length 435545 with out-of-bounds index -435546

<img width="564" alt="Screenshot 2024-11-12 at 09 05 21" src="https://github.com/user-attachments/assets/7f1720a6-59f6-4f5f-a28f-bbef8cb178a8">

**Comment by johncbowman** [comment]
Please attach d.obj.

**Comment by ccworld1000** [comment]
I guess it's because the model is too complex, resulting in too much data and causing boundary crossing

**Comment by johncbowman** [comment]
The obj module was designed for reading simple obj files, where simple means:

```
// 1) all vertex statements should come before the face statements;
//
// 2) face informations with respect to texture and/or normal vectors are
// ignored;
//
// 3) face statements only contain positive numbers(no relative positions).
//
// The reading process only takes into account lines starting with "v" or
// "f" or "g"(group).

```
From the error message you received, probably your obj file doesn't satisfy requirement 3. Perhaps you can use another program to simplify it. Or modify obj.asy to handle negative (relative) indices.
