### ISSUE TITLE
Asymptote Flowchart Hanging from Numerous \bm{...} LaTeX functions

### ISSUE THREAD

**Issue by un-term** [vectorgraphics/asymptote#49]
I'm using Asymptote to generate a flowchart within a LaTeX document. The flowchart contains maths equations, parts of which need to be in bold font. Numerous calls of the LaTeX package bold \bm{...} causes asy to hang here:

```
------------
Run number 1 of rule 'cusdep asy tex asy/text-1'
------------
For rule 'cusdep asy tex asy/text-1', running '&do_cusdep( asy )' ...
```

The problem is found on both Mac OS X and Ubuntu.
asy version 2.41
TeX 3.14159265
latexmk 4.52c

The problem can be reproduced by combining the following .asy and .tex code

dia.asy:
```
import flowchart;

for(int i=0; i < 17; ++i) {
block test=roundrectangle("$\bm{F}=\bm{F}_{i-1}+\Delta\bm{F}$", (0,-i*30));
draw(test);
};
```
LaTeX:
```
\documentclass[fleqn]{article}

\usepackage{amsmath}

\usepackage{bm}
\usepackage[inline]{asymptote}
\def\asydir{asy}

\begin{document}

Flowchart test document.

\begin{figure}[ht]
  \centering
  \asyinclude[]{dia.asy}
  \label{fig:Flowchart}
\end{figure}

\end{document}
```
Changing the dia.asy file iterations to` i < 16`, will then compile the PDF with the \bm{...} package.

My current work-around is to avoid using the `\bm{...}` package and instead use `\mathbf{...}`. Unfortunately it means the maths characters are just bold and not in italics.

**Comment by ivankokan** [comment]
Hi! Not sure why, but explicitly adding `texpreamble("\usepackage{bm}");` to `dia.asy` will do.

**Comment by un-term** [comment]
Thanks! Adding the above suggestion fixed the hanging problem.
