### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by mpegjohn** [vectorgraphics/asymptote#51]
I get the below error when compiling on my centos 7 system:

`/usr/include/c++/4.8.2/bits/hashtable.h:727:6: error: no matching function for call to ‘gc_allocator<std::__detail::_Hash_node<std::pair<const sym::symbol, trans::venv::namevalue>, true> >::construct(std::_Hashtable<sym::symbol, std::pair<const sym::symbol, trans::venv::namevalue>, gc_allocator<std::pair<const sym::symbol, trans::venv::namevalue> >, std::__detail::_Select1st, trans::venv::nameeq, trans::venv::namehash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::__node_type*&, const std::piecewise_construct_t&, std::tuple<const sym::symbol&>, std::tuple<>)’
      _M_node_allocator().construct(__n, std::forward<_Args>(__args)...);
      ^
/usr/include/c++/4.8.2/bits/hashtable.h:727:6: note: candidate is:
In file included from memory.h:86:0,
                 from common.h:35,
                 from entry.h:15,
                 from entry.cc:15:
gc-7.6.0/include/gc_allocator.h:142:8: note: void gc_allocator<GC_Tp>::construct(gc_allocator<GC_Tp>::pointer, const GC_Tp&) [with GC_Tp = std::__detail::_Hash_node<std::pair<const sym::symbol, trans::venv::namevalue>, true>; gc_allocator<GC_Tp>::pointer = std::__detail::_Hash_node<std::pair<const sym::symbol, trans::venv::namevalue>, true>*]
   void construct(pointer __p, const GC_Tp& __val) { new(__p) GC_Tp(__val); }
        ^
gc-7.6.0/include/gc_allocator.h:142:8: note:   candidate expects 2 arguments, 4 provided
gmake: *** [entry.o] Error 1
`

**Comment by johncbowman** [comment]
Your gcc compiler is very old; you should update your software. I'm using version 7.2.1.
In the meantime, you might be able to compile with the legacy option make CFLAGS="-g -DNOHASH"
