### ISSUE TITLE
Labels don't appear in PDF when using three and ConTeXt

### ISSUE THREAD

**Issue by danielmatz** [vectorgraphics/asymptote#58]
I'm trying to create a 3d image using ConTeXt to process the labels, but the labels aren't showing up in the PDF.  Here's a simple example:

```
import three;

unitsize(1cm);

draw(O -- X, L=Label("X", position=EndPoint));
draw(O -- Y, L=Label("Y", position=EndPoint));
draw(O -- Z, L=Label("Z", position=EndPoint));
```

And here's the command I'm using:

```
asy -tex context -outformat pdf -outname test.pdf test.asy
```

If I use the same 3d example, but use `-tex pdftex` in the command, the labels appear as expected.

If I instead try a 2d example (below), and continue to use `-tex context`, the labels also appear as expected.

```
unitsize(1cm);

draw((0, 0) -- E, L=Label("X", position=EndPoint));
draw((0, 0) -- N, L=Label("Y", position=EndPoint));
```

**Comment by johncbowman** [comment]
This is not a bug in Asymptote; context doesn't support embedding PRC. The solution is to use a fully functional TeX engine like pdflatex or xelatex.

**Comment by danielmatz** [comment]
OK, thank you for the help!

**Comment by mojca** [comment]
It should be feasible to add support to ConTeXt though if someone who fully understand the needs is willing to work with Hans a bit. We've discussed it in the past, but lacked some motivation and expertise.
