### ISSUE TITLE
empty png and pdf files with some 3D drawings in 2.42

### ISSUE THREAD

**Issue by zarniwhoop73** [vectorgraphics/asymptote#63]
When used from tex files, my tests work ok. But when I try to run some more general tests I'm getting no "subject" on the kleinbottle testfiles I grabbed from Charles Staats' tutorial. I mean that although the background (transparent on the minimal version using render=0, white on the other) is present, the drawn bottle is missing. This is true for both png and pdf output but it worked ok in 2.41 (I've just tested the pngs in that to be certain).

The source file can be found at http://www.linuxfromscratch.org/~ken/other/kleinbottle.asy (apparently I cannot attach a source file to an issue)

Conversely, my variants of the 'torus' image from the same source work fine.

**Comment by johncbowman** [comment]
Thank you for pointing this out. I accidentally broke the real mod operator (%); this is fixed in commit ce6d0daa38fb334ff23f190b74ba10d0aa241acd. It is a serious enough bug that I will make a new release (2.43) tonight.
