### ISSUE TITLE
Floating point exception on Cygwin

### ISSUE THREAD

**Issue by kbrow1i** [vectorgraphics/asymptote#65]
I'm getting a floating point exception while running 'make install' on 64-bit Cygwin.  It occurs while asy-keywords.el is being built, and I reduced the problem to the following:

$ ./asy -dir base -config "" -render=0 -l base/ode.asy
runtime: Floating point exception (core dumped)

[0001-Use-feenableexcept-only-if-_GNU_SOURCE-is-defined.patch.txt](https://github.com/vectorgraphics/asymptote/files/1885386/0001-Use-feenableexcept-only-if-_GNU_SOURCE-is-defined.patch.txt)
The problem began with the following commit:

commit 67b844aecc03a4b08ff8e9a8152d7cf324b4db22
Author: John Bowman <bowman@ualberta.ca>
Date:   Mon Apr 2 21:36:48 2018 -0600

    Check for feenableexcept.

Prior to that commit, feenableexcept was called only if _GNU_SOURCE was defined.  The attached patch restores this behavior, but I'm not sure it's the right fix.  Could there be a problem in base/ode.asy that was simply hidden before?

**Comment by johncbowman** [comment]
I tracked this down to an error in the current version of the 64-bit cygwin1.dll that you are using.
There seems to be a bug in the strtod routine. Perhaps you could report this to Cygwin for us?

This one is broken:
-rwxr-xr-x 1 bowman None 3195569 Feb  2 06:18 /usr/bin/cygwin1.dll

But this version works:
-rwxr-xr-x 1 bowman None 3150640 Sep 12  2017 cygwin1.dll

Fortunately the 1.43 release used the Sep 12 version. Here is asy code showing the minimal example of the bug (presumably a simple C call to strtod with this string will also demonstrate the FPE):

real x=121645100408832000.0;
write(x);

**Comment by kbrow1i** [comment]
Thanks.  I've reported it at https://cygwin.com/ml/cygwin/2018-04/msg00055.html.  By the way, when I boiled it down to a C program, I saw the problem on both 64-bit and 32-bit Cygwin.  And downgrading to the Sep 12 DLL didn't help.

**Comment by johncbowman** [comment]
You are right; the Sept. 12 version doesn't work either. I think the Feb 12, 2017 version (2.7.0) does, but I still need to check the 64-bit version...

**Comment by johncbowman** [comment]
None of the older versions of cygwin1.dll seem to work after all. Until this exceptions is fixed,
there is no choice but to disable them on CYGWIN. This is committed as 2c70c1d965fb0b9fa92f97db2484d3ba4c184f40.

**Comment by kbrow1i** [comment]
This is now fixed in the Cygwin development sources.  The fix will appear in cygwin-2.10.1.
