### ISSUE TITLE
Build saddle.pdf fails

### ISSUE THREAD

**Issue by stefanhusmann** [vectorgraphics/asymptote#67]
Under Arch Linux building the git sources fails at this step:

cd doc && make man
make[1]: Entering directory '/home/haawda/paketierung/meine_Pakete/asymptote-git/src/asymptote/doc'
../asy -dir ../base -config "" -render=0 -f pdf -noprc imagecontour.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc bezier.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc errorbars.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc shadedtiling.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc lineargraph.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc secondaryaxis.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc triangulate.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc eetomumu.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc diatom.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc filegraph.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc axis3.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc HermiteSpline.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc bigdiagonal.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc generalaxis3.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc hatch.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc CDlabel.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc superpath.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc subpictures.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc binarytreetest.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc planes.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc cylinderskeleton.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc legend.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc Hobbydir.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc bezier2.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc elliptic.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc logimage.asy
../asy -dir ../base -config "" -render=0 -f pdf -noprc saddle.asy
../base/three_surface.asy: 2251.6: Trying to use uninitialized value.
make[1]: *** [Makefile:42: saddle.pdf] Error 1

**Comment by johncbowman** [comment]
Sorry, I forgot to commit a change to builtin.cc. It is fixed now.

**Comment by stefanhusmann** [comment]
Works fine now, thanks.
