### ISSUE TITLE
eps files produced have confusing bounding box values

### ISSUE THREAD

**Issue by alick** [vectorgraphics/asymptote#68]
The eps files generated by Asymptote, e.g. [Pythagoras.eps](https://github.com/vectorgraphics/asymptote/files/1926379/Pythagoras.eps.gz) (gzipped since github does not allow eps uploading) contain two bounding box lines, and one of them is incorrect. Besides, folks on [mailing list](https://tug.org/pipermail/tex-k/2018-April/002872.html) pointed out that the eps file uses the operator setpagedevice, which is illegal in EPS. Such eps files cause other eps tools fail to detect the right bounding box.

Source file `Pythagoras.asy`:

    size(0,150);
    import geometry;

    real a=3;
    real b=4;
    real c=hypot(a,b);

    pair z1=(0,b);
    pair z2=(a,0);
    pair z3=(a+b,0);
    perpendicular(z1,NE,z1--z2,blue);
    perpendicular(z3,NW,blue);
    draw(square((0,0),z3));
    draw(square(z1,z2));

    real d=0.3;
    pair v=unit(z2-z1);
    draw(baseline("$a$"),-d*I--z2-d*I,red,Bars,Arrows,PenMargins);
    draw(baseline("$b$"),z2-d*I--z3-d*I,red,Arrows,Bars,PenMargins);
    draw("$c$",z3+z2*I-d*v--z2-d*v,red,Arrows,PenMargins);
    draw("$a$",z3+d--z3+z2*I+d,red,Arrows,Bars,PenMargins);
    draw("$b$",z3+z2*I+d--z3+z3*I+d,red,Arrows,Bars,PenMargins);

Asymptote version: 2.41 (with TeX Live 2017)

Notes: This is not a new issue. See also https://tex.stackexchange.com/q/248736/24521

**Comment by johncbowman** [comment]
Thank you for making us aware of the setpagedevice issue. 

1. We have added the -E option to the dvips command line (commit 60a35767c5becaf6f8a5fcd72584a9d3d316b028).

2. Note that the inner pair of bounding boxes belongs to an embedded file that is not considered by epstopdf. See https://tug.org/pipermail/tex-k/2018-April/002873.html.

3. Asymptote generates the correct bounding box (in this case, 150bp=5.291666cm high, as requested by the user). Note that the bounding box reported by ghostscript is obviously incorrect 
(470.537986bp-326.159990bp=144.377996bp high). If you were to use this bounding box instead, the pdf file generated by epstopdf would be cropped.

**Comment by johncbowman** [comment]
It seems that the reason that this issue only appeared now is due to a recent change between
dvips 5.997 and dvips 5.998, which apparently generates the additional setpagedevice code unless the -E option is specified. We didn't use the -E option previously since the bounding box it generates is only a rough estimate anyway and Asymptote replaces the bounding box with the correctly computed values.
