### ISSUE TITLE
can't install on macos 10.13.4

### ISSUE THREAD

**Issue by GeorgeCo** [vectorgraphics/asymptote#69]
can't install version 2.44 on Macos 10.13.4 using Xcode 9.3

 g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

make all

g++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -DUSEGC  -D_THREAD_SAFE -pthread -DFFTWPP_SINGLE_THREAD  -std=c++11 -g -O3 -I. -I/usr/local/include/gc -I/usr/include/gc -o settings.o -c settings.cc
In file included from settings.cc:18:
In file included from ./common.h:35:
In file included from ./memory.h:13:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/map:1561:65: error: no viable conversion from
      'gc_allocator<std::__1::__value_type<const sym::symbol, trans::tyEntry *>>' to 'const gc_allocator<std::__1::pair<const sym::symbol,
      trans::tyEntry *>>'
          __alloc_traits::select_on_container_copy_construction(__m.__tree_.__alloc()))
                                                                ^~~~~~~~~~~~~~~~~~~~~
./memory.h:146:14: note: in instantiation of member function 'std::__1::multimap<const sym::symbol, trans::tyEntry *, std::__1::less<const
      sym::symbol>, gc_allocator<std::__1::pair<const sym::symbol, trans::tyEntry *> > >::multimap' requested here
GC_CONTAINER(multimap);
             ^
./env.h:61:8: note: in instantiation of member function 'sym::table<trans::tyEntry *>::collapseScope' requested here
    te.collapseScope(); ve.collapseScope();
       ^
/usr/local/include/gc/gc_allocator.h:118:5: note: candidate constructor not viable: no known conversion from
      'std::__1::__tree<std::__1::__value_type<const sym::symbol, trans::tyEntry *>, std::__1::__map_value_compare<const sym::symbol,
      std::__1::__value_type<const sym::symbol, trans::tyEntry *>, std::__1::less<const sym::symbol>, true>,
      gc_allocator<std::__1::__value_type<const sym::symbol, trans::tyEntry *> > >::allocator_type' (aka
      'gc_allocator<std::__1::__value_type<const sym::symbol, trans::tyEntry *> >') to 'const gc_allocator<std::__1::pair<const sym::symbol,
      trans::tyEntry *> > &' for 1st argument
    gc_allocator(const gc_allocator&) throw() {}
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory:1558:69: note: passing argument to
      parameter '__a' here
        select_on_container_copy_construction(const allocator_type& __a)
                                                                    ^
1 error generated.
make: *** [settings.o] Error 1

**Comment by johncbowman** [comment]
We encountered this issue with the TeXLive release. The solution is to downgrade to gc-7.6.0.
This should be detected by configure automatically, but perhaps this is being overridden
by the system version (or on the configure command line):

case "${host_os}" in
    darwin*)
      GCVERSION=7.6.0
      ATOMICVERSION=7.6.0
        ;;
   *)
      GCVERSION=7.6.2
      ATOMICVERSION=7.6.2
        ;;
esac


Also, be sure to compile under High Sierra or El Capitan as I understand that earlier OS versions have broken C++ libraries that can cause segmentation faults. You can run asy binaries compiled under these systems under Yosemite, if desired. Good luck! If you still have trouble, you can always use a precompiled version of 2.44 from MacPorts or TeXLive 2018.

**Comment by Alhadis** [comment]
Don't know if it's relevant or not, but if `${host_os}` is being assigned the output of `uname -s`, then the `case` match needs to be `Darwin*)` (capitalised).

~~~console
$ uname -s
Darwin
~~~

Also, if the GC library is version-locked, it might help to use git submodules instead of a manually-downloaded tarball. Got the same build error just before, and arrived to this issue when I googled `error: no viable conversion from 'gc_allocator`.
