### ISSUE TITLE
Create a Prc file with 3D tags by using C++.

### ISSUE THREAD

**Issue by MiracleVulkan** [vectorgraphics/asymptote#71]
I work under Windows. There is a project requirement to write a prc file with a 3D label. I tried to look at this asympote project to see how this project implements 3D label, but there are too few notes in this project. The code looks a bit difficult, so can you refer to the key function? Thank you,

**Comment by johncbowman** [comment]
The key function, bezulate, is written in Asymptote code:
https://raw.githubusercontent.com/vectorgraphics/asymptote/HEAD/base/bezulate.asy

The details are described in these articles:

http://www.math.ualberta.ca/~bowman/publications/asyTUG3.pdf
http://www.math.ualberta.ca/~bowman/publications/tb98bowman.pdf
http://www.math.ualberta.ca/~bowman/publications/asy3d.pdf

**Comment by johncbowman** [comment]
For a more detailed discussion of the bezulate algorithm, see:

[Surface Parameterization of Nonsimply Connected Planar Bézier Regions, O. Shardt and J. C. Bowman, Computer-Aided Design 44:5, 484.e1-10 (2012). ](http://dx.doi.org/10.1016/j.cad.2011.05.010)

**Comment by MiracleVulkan** [comment]
Thanks very much,Now I know how to write 3D text, but I don't know how to implement Billboard form，Can you give me some hints
