### ISSUE TITLE
Using lualatex fails when outname is in a subdirectory

### ISSUE THREAD

**Issue by tifv** [vectorgraphics/asymptote#75]
Steps to reproduce:
1. Grab some example:
`cp /usr/share/asymptote/examples/markers2.asy .`
2. Create an output directory:
`mkdir output`

3. Run the following:
`asy markers2.asy -f pdf -tex lualatex -outname=output/what.pdf`
4. Observe that it asks for some filename:
```
This is LuaTeX, Version 1.0.4 (TeX Live 2017) 
 restricted system commands enabled.
LaTeX2e <2017/01/01> patch level 3
(using write cache: /home/july/.texlive/texmf-var/luatex-cache/generic)(using read cache: //var/lib/texmf/luatex-cache/generic /home/july/.texlive/texmf-var/luatex-cache/generic)
luaotfload | main : initialization completed in 0.110 secondsBabel <3.10> and hyphenation patterns for 1 language(s) loaded.


lualatex: Not writing to .log (openout_any = p).
! I can't write on file `.log'.
Please type another transcript file name: 
```
and then fails.

(Gentoo Linux, TeXLive 2017.)

**Comment by tifv** [comment]
I see that this is related to #27. I suppose that you consider this issue belonging to lualatex and not to asymptote.

As a temporary fix for myself, I just disabled quotes when engine is lua*tex, so it works except when the directory path contains spaces, which, in my workflow, they never do.
(Patch attached
https://github.com/vectorgraphics/asymptote/files/2607951/lualatex_noquotes-patch.txt.)

**Comment by matthuszagh** [comment]
@tifv are you still using the same patch? Unfortunately, that doesn't seem to work for me with texlive-2019 and asymptote 2.59.

**Comment by tifv** [comment]
@matthuszagh Note that this issue and #27 are related, but not the same. My patch only solves this issue, but not the other.
By the way, commit [41cc1fa](https://github.com/vectorgraphics/asymptote/commit/41cc1fa54e638954177314a0add6b2d3a043257f) seems to resolve this particular issue.
