### ISSUE TITLE
Project picture on a plane

### ISSUE THREAD

**Issue by nojhan** [vectorgraphics/asymptote#78]
_Hi, I'm completely new to Asymptote, but after playing a bit with it, I already like it.
I thought I thus should took this opportunity to raise some problems faced by a naive user like me.
Unless someone think it's a bad idea, I'm going to post everything that bothered me here, as issues, which I guess will probably be mainly API consistency concerns._

For this first post: I did not found a way to project a picture on a plane.
I was playing with `picture slopefield(…)` of the eponymic module and wanted to generate several planes with vector fields in them, and spread them along the z-axis (see the attached picture).
![distrib_mean-covariance_small](https://user-images.githubusercontent.com/285009/50628936-af97ed00-0f3a-11e9-8c2a-86e03f0dc41c.jpg)
In the tutorial, `path3` is indicated as a way to project a `path` into a plane. There is also `planeproject`, which takes a `path3`. `path3` (seems to) only allows projections on axis planes, while `planeproject` is more general. Unfortunately, I did not found their counterpart for `picture`.

I would have expected:
1. `path3` and `planeproject`functions to have the same name (I don't know if it's feasible in Asymptote's language, but at least a similar name).
2. An additional function that would take a `picture`.
3. A mention of `planeproject` in the tutorial (I did not found the tutorial sources in the repository, btw).
4. Maybe a single function to do all of this, while still allowing simple uses like `project(…, plane=XYplane)`.
5. Maybe even something like `project(…, plane=XYplane + 10Z)` if one don't want to play with normals.

Hope this helps.

**Comment by johncbowman** [comment]
I think there is a misunderstanding in this request about what a picture is. Think of it as a (2D or 3D) drawing canvas. The planeproject function has been in the documentation since 2008. The source
for the documentation is in the repository in the file doc/asymptote.texi.
