### ISSUE TITLE
3-to-2D vector scenes engine improvement (render=0)

### ISSUE THREAD

**Issue by nojhan** [vectorgraphics/asymptote#83]
Issue #46 discuss the fact that the `render=0` engine is not complete:
> See the discussion about render=0 throughout the manual. It is intended as a rough attempt to flatten a 3D scene to a 2D vector format (without rendering) and is far from complete (for example, no hidden surface removal).  Try using render=0 on the teapot example and you will see that this option is not intended for general use.
> _Originally posted by @johncbowman in https://github.com/vectorgraphics/asymptote/issues/46#issuecomment-378658531_

I'm posting a new issue to gather information on what could be done about this feature.

A (better) 3-to-2D rendering in Asymptote's context seems feasible, as [sketch](http://sketch4latex.sourceforge.net) (a "3D scene description translator" similar to Asymptote) already done it (note: Sketch development [stopped](https://groups.google.com/d/msg/sketch-users/g6WE0xAuylg/H9kJO6QOCQAJ) and it do not have a raster rendering).
Sketch use the [Newell's algorithm](https://en.wikipedia.org/wiki/Newell%27s_algorithm), which seems quite suited to the task, here is the excerpt [from the related item in the documentation](http://sketch4latex.sourceforge.net/sketch.html#Hidden-surface-removal):
> **4.4.3 Hidden surface removal and polygon splitting**
>Sketch uses the depth sort algorithm for hidden surface removal. This is a very old technique due to Newell.3 It is generally regarded as too slow for real time graphics, but it is ideal for our purpose where speed is not very important.4
> The depth sort algorithm merely sorts objects on a key of increasing z-coordinate, equivalent to decreasing depth. Objects are then drawn in the sorted sequence so that those at the rear of the scene are overwritten by those closer to the viewer. Since this is also how oil painters practice their art, depth sort is sometimes called “the painter's algorithm.”
> In some cases it is impossible to strictly order polygons according to depth. Moreover, even if a correct depth ordering exists, the computation needed to find it may be too complex and slow. In these cases, sketch splits one or more polygons into pieces. The expectation is that the new, smaller polygons will be simpler to order. Sketch uses a BSP (binary space partition) to handle the splitting operation. 

There is also a recent discussion about how to implement a rough illumination of the scene by changing polygons colors, depending on the direction of their normals with respect to the light source:
> Parsing the input ultimately produces a binary space partition data structure that's refined by splitting and then sorted by depth in the hidden surface algorithm. Polygons in this data structure include plane normals computed with Newell's algorithm. The result is rendered as 2d output polygons.  
> You could apply a lighting model on the bsp data structure before or after refinement. Start by looking at bsp.c and bsp.h. 
> This will work fine for objects with planar boundaries. Unfortunately, for shading faceted curved shapes, you really Gouraud-shaded general polygons. PsTricks and Tikz didn't provide them (as I recall, TikZ had triangles only, so triangular decomposition of >3-gons would have been required), and emitting custom postscript looked messy.

How would that be difficult to add to Asymptote?

**Comment by nojhan** [comment]
Additional notes: Sketch is written in C and licensed in GPLv3. The code may thus be compatible with an embedding within Asymptote's code base.

**Comment by johncbowman** [comment]
Actually, some depth sorting is already implemented in Asymptote but this obviously only works for nonintersecting vector objects (Bezier patches or triangles). Otherwise the objects first need to be split.
Splitting Bezier surface is nontrivial but we are developing algorithms for this. If you are not interested in vector graphics (e.g tensor patches), then you can already use an options like -render=4 to get a 2D bitmap. 

Now that Asymptote has its own in-house renderer (instead of the GLU library), a compromise between these two approaches might be to do some prerendering at a specified resolution into triangles, and then render these on a 2D canvas via Gouraud shading. I hope this answers your questions about our future plans.

**Comment by nojhan** [comment]
What I'm looking for is a vector rendering of 3D scene (without Gouraud shading), even if it's without Bezier curves. If I understand well, this is not planned for Asymptote in a near future and no help is needed. Thanks for the answer!
