### ISSUE TITLE
libtirpc dependency on Unbuntu

### ISSUE THREAD

**Issue by Georacer** [vectorgraphics/asymptote#84]
Hello everyone!

I just installed Asymptote binaries in Ubuntu 18.04. Tried to run a basic example.

First a `libosmesa` was missing. Installed it with
`sudo apt install libosmesa6`.

Then, an error for a missing `libtirpc.so.3` was raised.
Neither installing package `libtirpc1` nor `libtirpc-dev` satisfies this dependency.

Any thoughts? Thanks.

**Comment by johncbowman** [comment]
In the next release, libosmesa will be disabled during configuration by default (since it can cause conflicts with NVIDIA cards and is only needed for experimental offscreen rendering).

The libtirpc issue should be reported to Ubuntu since it is not an Asymptote bug.
