### ISSUE TITLE
Assertion failure on Fedora 28

### ISSUE THREAD

**Issue by johnmwu** [vectorgraphics/asymptote#85]
Using the example file "Klein.asy", I obtain the following from terminal:

```
[johnmichaelwu@localhost examples]$ asy
Welcome to Asymptote version 2.44 (to view the manual, type help)
> input Klein;
> > /usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; std::vector<_Tp, _Alloc>::reference = unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
Aborted (core dumped)
```

This issue does not appear when providing the file as a command line argument, i.e

`[johnmichaelwu@localhost examples]$ asy Klein.asy 
`

Runs with no issues. Any ideas?

**Comment by johncbowman** [comment]
That's an obsolete version of Asymptote. Can you try out the latest version (version 2.47) or even better, the latest git version? We are about to release version 2.48 so it would be good to know. Thanks!
