### ISSUE TITLE
invalid normal vector when using arc in three

### ISSUE THREAD

**Issue by nagua** [vectorgraphics/asymptote#87]
Hey,

I'm trying to make a rotation arrow from one vector to another around a rotation axis.
I'm using something like the following code:

```
import three;

triple v1 = (0.794085, 0.547516, 0.263925);
triple v2 = (0.332403, 0.0310806, 0.942625);
triple c = v1 + 0.5 * (v2 - v1);

draw(arc(0.9 * c, 0.9 * v1, 0.9 * v2, c), black);
```

But asymptote is telling me: "three.asy: 2026.10: invalid normal vector". If I remove the check everything is working as I expected. But I also saw that the code checks if the points are on a line (which they are in my example) but the check does not seem to work correctly. I tested it with the 2.47 release in windows.

I tried to understand what the code is doing, but I'm not completly sure why this check should be necessary in the first place.

If I can help with something please tell me!

**Comment by ivankokan** [comment]
Hi @nagua, what do you want to render with `draw(arc(0.9 * c, 0.9 * v1, 0.9 * v2, c), black);`, I am missing the semantics.

**Comment by nagua** [comment]
Hi, this is a drawing for my masterthesis. It basically is an image where I depict a rotation of a "cell" onto a line segment. I just randomly chose two unit vectors that looked like good directions. And I chose the line segment randomnly from 0.8 to 1.2 of v1. And the position of the cell at 0.9. So the cell at 0.9v2 needs to be rotated onto 0.9v1 around the rotation axis c.

So I want to draw the rotation with the arc, centered at c, with the normal vector c from 0.9v1 to 0.9v2. But if it helps I can easily use values greater than 1. This where just values that looked nice on the graphic and the resulting image is filled with the interesting information.

**Comment by ivankokan** [comment]
Hi, I have investigated the issue a bit, and got stuck at this line:
https://github.com/vectorgraphics/asymptote/blob/master/base/three.asy#L2025

At that point, both `v1` and `v2` (arguments) are opposite unit vectors, midpoint of the segment joining them is the origin itself. Also, everything is rotated in a way that `normal` corresponds to z-axis.

What could the condition `abs(v1.z) > fuzz || abs(v2.z) > fuzz` mean?

**Comment by nagua** [comment]
Yeah, that line was exactly the line that I got stuck with too.

After thinking over it for a while I could think that the intended check is, if v1.z and v2.z are equal. Such that they are lying in the same plane with the given normal vector.

So I think that the correct check would be:
```
if (abs(v1.z - v2.z) < realEpsilon)
```

That would at least make sense with the error of "invalid normal vector".

**Comment by johncbowman** [comment]
arc constructs a circle in the XY plane and then rotates into the correct position, so I believe the check as written is correct. The origin of the problem is that the user has colinear points and so an explict normal vector is required, but the specified normal vector (c) is not perpendicular to v2-v1. That is, an invalid normal has been specified. Try changing c to perp(v2-v1), for example.

**Comment by nagua** [comment]
Thank you. Actually, I thought they were orthogonal, but v1 and v2 are not completely unit vector because I rounded them too much. But throwing `unit` at them made it work.
