### ISSUE TITLE
Asymptote terminates and kills parent process if settings.tex is wrong

### ISSUE THREAD

**Issue by tifv** [vectorgraphics/asymptote#88]
Next is a python3 script that demonstrates error. Note: the script writes a file `test.asy`:
```
import subprocess

with open("test.asy", "w") as f:
    f.write(
"""
settings.tex = "whatever";
draw((0,0)--(1,1));
label("$A$", (0,0), SW);
"""
    )

try:
    subprocess.call(['asy', 'test.asy'])
finally:
    print("made it")
```

The script output:
```
Cannot execute whatever
Please put in a file config.asy: 

import settings;
texpath="LOCATION";

where LOCATION specifies the location of the directory containing your whatever engine (whatever).

Alternatively, set the environment variable ASYMPTOTE_TEXPATH
or use the command line option -texpath="LOCATION". For further details, see
http://asymptote.sourceforge.net/doc/Configuring.html
http://asymptote.sourceforge.net/doc/Search-paths.html
Terminated
```

Description: the written `test.asy` file contains `settings.tex = "whatever"`, which of course should cause an error when running `asy`. But in this case Asymptote receives SIGTERM (I suppose), which propagates to the parent python process, so it never reaches its finally clause.

I am not sure about this, but I suppose that any error in Asymptote code shouldn't terminate parent process like this. (In fact, I never realised that parent process can be accidentally terminated by its child.)

I have reproduced it with the git version of Asymptote (on Gentoo Linux).

**Comment by johncbowman** [comment]
Yes, that was admittedly a little heavy-handed. This is fixed now in git.
