### ISSUE TITLE
"matrix must be square" from intersect(line,triangle)

### ISSUE THREAD

**Issue by mattpusey** [vectorgraphics/asymptote#89]
Running this:
```
import three;
intersect((0.5,0.5,-1)--(0.5,0.5,1),surface((0,0,0)--(0,1,0)--(1,0,0)--cycle));
```
Gives this:
`/usr/share/asymptote/three_surface.asy: 1286.9: matrix must be square`

**Comment by johncbowman** [comment]
I've improved the diagnostic for this unimplemented feature:
Intersection of path3 with Bezier triangle is not yet implemented

In the meantime, you can add an extra --cycle to the path3 to produce a Bezier patch:
```
> import three;
> write(intersect((0.5,0.5,-1)--(0.5,0.5,1),surface((0,0,0)--(0,1,0)--(1,0,0)--cycle--cycle)));
0:      0.499998569488525
1:      0.999996662139893
2:      0.500000476837158

```
