### ISSUE TITLE
xasy 2.47 can not display external graphics

### ISSUE THREAD

**Issue by goodluck1982** [vectorgraphics/asymptote#90]
I want to use xasy to combine several pdf figures, e.g.
file:  a.asy

```
settings.tex="pdflatex";
label(graphic("fig1.pdf"));
label(graphic("fig2.pdf));
```
When I use xasy to open the file a.asy, the figures fig1 and fig2 cannot be displayed in xasy.
Only when the cursor is on the figure, say, fig1, the bounding box of fig1 is displayed, but not the figure itself. When the cursor move away, nothing is displayed.

How to make the figures displayed in xasy?

I remember that in an older version such as 2.37, external figures can be displayed in xasy 
 correctly.

**Comment by johncbowman** [comment]
This bug is now fixed for vector EPS files (embedded images, PDF, PNG, and JPG formats are not supported due to limitations of dvisvgm-2.7.4). Also, PostScript clipping within an external EPS file will not work correctly, due to a bug in QtSvg.

**Comment by goodluck1982** [comment]
> This bug is now fixed for vector EPS files (embedded images, PDF, PNG, and JPG formats are not supported due to limitations of dvisvgm-2.7.4). Also, PostScript clipping within an external EPS file will not work correctly, due to a bug in QtSvg.

Yes, dvisvgm do not support converting bitmap pdf to svg.   However, pdftocairo (in package poppler-utils) can convert any pdf to svg.  For other formats such as png, jpg, etc, the command "convert" (in package imagemagick) can convert them to svg. So, is there a way to fix this problem by using pdftocairo and convert? For example, provide a user-configured interface to call the external commands pdftocairo and covert for pdf and png respectively.

**Comment by johncbowman** [comment]
Followup: just a few days after my last post, the author of dvisvgm kindly added support for embedding PDF, PNG, and JPG images, so there is no need to consider adding another dependency:

commit 47651b94e32e3861070cb7c58a0be045ba7489a5
Author: Martin Gieseking <martin.gieseking@uos.de>
Date:   Fri Oct 18 14:34:32 2019 +0200

    psfile: added support for PDF, JPG, PNG, and SVG files

**Comment by goodluck1982** [comment]
I don't know whether the version of dvisvgm used now  supports embedding PDF etc. But I installed the latest v2.65 asymptote (win version) and it still  does not support embedding PDF in xasy.  I directly use the dvisvgm (v2.8.2) command `dvisvgm --pdf  test.pdf` to test and find that the obtained svg file is blank.   And I find that dvisvgm works correctly for  pdf  of vector graphics but not for non-vector graphics.

**Comment by johncbowman** [comment]
Those versions are actually both obsolete. At a minimum, you need to upgrade to dvisvgm 2.9.1 or later,
as specified even in the asy 2.65 manual. I believe it comes with TeXLive 2020.

_The 2.9.1 version of dvisvgm can display SVG output (used by the
xasy editor) for embedded EPS, PDF, PNG, and JPEG images included with the graphic()
function._
 
For full svg functionality you should also upgrade to asy 2.67, which includes many bug fixes.

**Comment by goodluck1982** [comment]
I installed the latest dvisvgm 2.10. It works.
