### ISSUE TITLE
Feature request for xasy: alignment and move by keyboard

### ISSUE THREAD

**Issue by goodluck1982** [vectorgraphics/asymptote#91]
In my work, I usually need to combine several pdf vector figures to form a final one. I find xasy is an excellent tool to do this (in spite of a bug in new version #90 ), even better than Illustrator and Acrobat pro,  Illustrator usually cannot read embedded font correctly, and acrobat decompose all pdf figures to parts without convenience of move as a whole. Further more, xasy supprot LaTeX!

When combining figures,  we usually need to align figures/objects in various ways, as in PowerPoint. And usually we need to finely tune the position of a figure/object by keyboard, e.g. moving a figure/object using the up, down, left, and right keys other than by mouse. Because it's hard to control mouse finely.  The realization of these features will enhance the power of xasy very much!

**Comment by supakorn-ras** [comment]
Definitely a good idea. Will add to the current backlog. Thanks for the suggestion!

**Comment by johncbowman** [comment]
This feature was added on May 1; just make sure that your xasykeymap.cson file configuration file is up 
 to date (it is not overwritten by the installer).
