### ISSUE TITLE
Doesn't work with ngerman package

### ISSUE THREAD

**Issue by scrouthtv** [vectorgraphics/asymptote#93]
`! ngerman: The command "\AsyFile is undefined.`

Regarding the tex version

**Comment by johncbowman** [comment]
Next time please post a minimal example, so we don't have to waste time constructing one and guessing.

It works for me. I tried adding 
\usepackage{ngerman} before \begin{document} in latexusage.tex and "a typesets as ä.
The recommended usage \usepackage[ngerman]{babel}
In Asymptote, outside of TeX, this works also:

import babel;
babel("ngerman");
label('"a');

**Comment by scrouthtv** [comment]
Sorry, I kind of lost track of this issue trying to fix it, but what I think is happening is that ```ifplatform.sty``` does not work with ngerman

**Comment by johncbowman** [comment]
Asymptote doesn't use ifplatform.sty.
