### ISSUE TITLE
outformat png with render doesn't

### ISSUE THREAD

**Issue by teepeemm** [vectorgraphics/asymptote#96]
I recently upgraded to TeXLive 2019 with Asy 2.49, and my asy builds for png have stopped working.  I've narrowed it down to the render option.  If I call
`asy -f png -render 1 axis3.asy -vv`
Then the output ends with
```
Transcript written on axis3_.log.
dvips -R -Pdownload35 -D600 -q -oaxis3_.ps axis3_.dvi
gs -q -dBATCH -P -dSAFER -sDEVICE=eps2write -sOutputFile=/dev/null axis3_.ps
adjusting camera to (5.00536121639911,2.02966119026451,1.88338233197078)
adjusting target to (0.494310649290367,0.4481516926686,0.536476629329728)
```
And no file is made.  On the other hand, if I call
`asy -f png -render 0 axis3.asy -vv`
Then the output ends with
```
Transcript written on axis3_.log.
dvips -R -Pdownload35 -D600 -q -oaxis3_.ps axis3_.dvi
gs -q -dBATCH -P -dSAFER -sDEVICE=eps2write -sOutputFile=/dev/null axis3_.ps
gs -q -dNOPAUSE -dBATCH -P -sDEVICE=pngalpha -dEPSCrop -dSAFER -r72x72 -sOutputFile=axis3.png axis3_.eps
Wrote axis3.png
```
And the expected file is made.  I would like to have higher quality graphics (I was using `-render 4`).  Is there something I can do to make that happen?

**Comment by johncbowman** [comment]
You need to compile with OpenGL support. Check your configure messages to see which libraries are missing.
