### ISSUE TITLE
When I try to "make asymptote.so"

### ISSUE THREAD

**Issue by jdevoto** [vectorgraphics/asymptote#99]
g++ -Wall -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -pthread -DFFTWPP_SINGLE_THREAD -I. -Igc-8.0.4/include -I/usr/include/tirpc -std=c++11 -g -O3 -fno-var-tracking -fPIC -DFOR_SHARED -o types.pic.o -c types.cc
types.cc:28:27: fatal error: types.symbols.h: No such file or directory
 #include "types.symbols.h"

**Comment by johncbowman** [comment]
Probably you just need to first 
`make clean`
I just made a couple of tweaks to the makefile so that it should compile the shared library again
(this is an experimental feature).
